#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Generate Security.framework's public CFString constants from Apple's source.

    gen-constants.py <Security source> <SDK Security headers> <out.c>

Every `extern const CFStringRef kSec...` (and SecKeyAlgorithm, kAuthorization...)
the SDK's public headers declare gets the value Apple's open-source Security
(userland/projects.txt) defines it with: SEC_CONST_DECL(k, "v"),
`k = CFSTR("v")`, and SecPolicy.list's POLICYMACRO lines. Constants the
source doesn't define are listed on stderr (and in the output as a comment),
and fail the build unless they're in EXTRA below, which holds the few Apple
defines only in closed code (each checked against Apple's binary by
finch-security-test).
"""
import os
import re
import sys

src, hdrs, out = sys.argv[1:4]

# Public constants whose definitions aren't in the published source.
EXTRA = {
}
# Declared in the headers but not exported by Apple's Security.
NOT_EXPORTED = {"kSecUseUserIndependentKeychain"}

declared = set()
decl_re = re.compile(r"\bextern\s+const\s+(?:CFStringRef|SecKeyAlgorithm|SecKeyKeyExchangeParameter|CFTypeRef)\b[^;]*?\b((?:kSec|kAuthorization|kCMS)\w+)")
for name in sorted(os.listdir(hdrs)):
    if not name.endswith(".h"):
        continue
    text = open(os.path.join(hdrs, name), encoding="utf-8", errors="replace").read()
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    for stmt in text.split(";"):
        m = decl_re.search(stmt + ";")
        if m and "(" not in stmt.split(m.group(1))[1][:2]:
            declared.add(m.group(1))

values = {}
pat_decl = re.compile(r'SEC_CONST_DECL\s*\(\s*(k\w+)\s*,\s*"((?:[^"\\]|\\.)*)"\s*\)')
pat_cfstr = re.compile(r'\b(k\w+)\s*=\s*CFSTR\s*\(\s*"((?:[^"\\]|\\.)*)"\s*\)')
pat_policy = re.compile(r'^POLICYMACRO\(\s*(\w+)\s*,\s*([0-9.]+)\s*,', re.M)
skip = re.compile(r"/(Regressions|regressions|tests|Tests|SecurityTests|RegressionTests|secdtests|secdxctests)/")
for root, dirs, files in os.walk(src):
    if skip.search(root + "/"):
        continue
    for f in files:
        if not f.endswith((".c", ".m", ".cpp", ".mm", ".list")):
            continue
        p = os.path.join(root, f)
        text = open(p, encoding="utf-8", errors="replace").read()
        if f == "SecPolicy.list":
            for n, oid in pat_policy.findall(text):
                values.setdefault("kSecPolicyApple" + n, "1.2.840.113635.100.1." + oid)
            continue
        for pat in (pat_decl, pat_cfstr):
            for k, v in pat.findall(text):
                values.setdefault(k, v)

missing = []
lines = [
    "/* Generated by userland/Security/gen-constants.py from Apple's Security source. */",
    "#define __CONSTANT_CFSTRINGS__ 1",
    "#include <CoreFoundation/CoreFoundation.h>",
    "",
]
for k in sorted(declared - NOT_EXPORTED):
    v = values.get(k, EXTRA.get(k))
    if v is None:
        missing.append(k)
        continue
    lines.append('__attribute__((visibility("default"))) const CFStringRef %s = CFSTR("%s");' % (k, v))
lines.append("")
lines.append("/* Declared but not defined in the source: %s */" % (" ".join(missing) or "none"))
with open(out, "w") as fh:
    fh.write("\n".join(lines) + "\n")
print("%d constants, %d without a source definition" % (len(declared - NOT_EXPORTED) - len(missing), len(missing)))
if missing:
    print("  " + " ".join(missing), file=sys.stderr)

    sys.exit(1)
