# SPDX-License-Identifier: MIT OR Apache-2.0
my %targets = (
    "finch-arm64e" => {
        inherit_from => [ "darwin64-arm64" ],
        cflags => "-arch arm64e -mmacosx-version-min=26.0 -fvisibility=hidden",
    },
);
