/* SPDX-License-Identifier: MIT OR Apache-2.0 */
/*
 * The core types (UTCoreTypes.h). The header declares them const; they are objects,
 * so they are defined here, away from the header, and set when the framework loads.
 */
#import <Foundation/Foundation.h>

@class UTType;
@interface UTType : NSObject
+ (instancetype)typeWithIdentifier:(NSString *)identifier;
@end

__attribute__((visibility("default"))) UTType *UTType3DContent;
__attribute__((visibility("default"))) UTType *UTTypeAHAP;
__attribute__((visibility("default"))) UTType *UTTypeAIFF;
__attribute__((visibility("default"))) UTType *UTTypeARReferenceObject;
__attribute__((visibility("default"))) UTType *UTTypeAVI;
__attribute__((visibility("default"))) UTType *UTTypeAliasFile;
__attribute__((visibility("default"))) UTType *UTTypeAppleArchive;
__attribute__((visibility("default"))) UTType *UTTypeAppleProtectedMPEG4Audio;
__attribute__((visibility("default"))) UTType *UTTypeAppleProtectedMPEG4Video;
__attribute__((visibility("default"))) UTType *UTTypeAppleScript;
__attribute__((visibility("default"))) UTType *UTTypeApplication;
__attribute__((visibility("default"))) UTType *UTTypeApplicationBundle;
__attribute__((visibility("default"))) UTType *UTTypeApplicationExtension;
__attribute__((visibility("default"))) UTType *UTTypeArchive;
__attribute__((visibility("default"))) UTType *UTTypeAssemblyLanguageSource;
__attribute__((visibility("default"))) UTType *UTTypeAudio;
__attribute__((visibility("default"))) UTType *UTTypeAudiovisualContent;
__attribute__((visibility("default"))) UTType *UTTypeBMP;
__attribute__((visibility("default"))) UTType *UTTypeBZ2;
__attribute__((visibility("default"))) UTType *UTTypeBinaryPropertyList;
__attribute__((visibility("default"))) UTType *UTTypeBookmark;
__attribute__((visibility("default"))) UTType *UTTypeBundle;
__attribute__((visibility("default"))) UTType *UTTypeCHeader;
__attribute__((visibility("default"))) UTType *UTTypeCPlusPlusHeader;
__attribute__((visibility("default"))) UTType *UTTypeCPlusPlusSource;
__attribute__((visibility("default"))) UTType *UTTypeCSS;
__attribute__((visibility("default"))) UTType *UTTypeCSource;
__attribute__((visibility("default"))) UTType *UTTypeCalendarEvent;
__attribute__((visibility("default"))) UTType *UTTypeCommaSeparatedText;
__attribute__((visibility("default"))) UTType *UTTypeCompositeContent;
__attribute__((visibility("default"))) UTType *UTTypeContact;
__attribute__((visibility("default"))) UTType *UTTypeContent;
__attribute__((visibility("default"))) UTType *UTTypeDNG;
__attribute__((visibility("default"))) UTType *UTTypeData;
__attribute__((visibility("default"))) UTType *UTTypeDatabase;
__attribute__((visibility("default"))) UTType *UTTypeDelimitedText;
__attribute__((visibility("default"))) UTType *UTTypeDirectory;
__attribute__((visibility("default"))) UTType *UTTypeDiskImage;
__attribute__((visibility("default"))) UTType *UTTypeEPUB;
__attribute__((visibility("default"))) UTType *UTTypeEXE;
__attribute__((visibility("default"))) UTType *UTTypeEXR;
__attribute__((visibility("default"))) UTType *UTTypeEmailMessage;
__attribute__((visibility("default"))) UTType *UTTypeExecutable;
__attribute__((visibility("default"))) UTType *UTTypeFileURL;
__attribute__((visibility("default"))) UTType *UTTypeFlatRTFD;
__attribute__((visibility("default"))) UTType *UTTypeFolder;
__attribute__((visibility("default"))) UTType *UTTypeFont;
__attribute__((visibility("default"))) UTType *UTTypeFramework;
__attribute__((visibility("default"))) UTType *UTTypeGIF;
__attribute__((visibility("default"))) UTType *UTTypeGZIP;
__attribute__((visibility("default"))) UTType *UTTypeGeoJSON;
__attribute__((visibility("default"))) UTType *UTTypeHEIC;
__attribute__((visibility("default"))) UTType *UTTypeHEICS;
__attribute__((visibility("default"))) UTType *UTTypeHEIF;
__attribute__((visibility("default"))) UTType *UTTypeHTML;
__attribute__((visibility("default"))) UTType *UTTypeICNS;
__attribute__((visibility("default"))) UTType *UTTypeICO;
__attribute__((visibility("default"))) UTType *UTTypeImage;
__attribute__((visibility("default"))) UTType *UTTypeInternetLocation;
__attribute__((visibility("default"))) UTType *UTTypeInternetShortcut;
__attribute__((visibility("default"))) UTType *UTTypeItem;
__attribute__((visibility("default"))) UTType *UTTypeJPEG;
__attribute__((visibility("default"))) UTType *UTTypeJPEGXL;
__attribute__((visibility("default"))) UTType *UTTypeJSON;
__attribute__((visibility("default"))) UTType *UTTypeJavaScript;
__attribute__((visibility("default"))) UTType *UTTypeLinkPresentationMetadata;
__attribute__((visibility("default"))) UTType *UTTypeLivePhoto;
__attribute__((visibility("default"))) UTType *UTTypeLog;
__attribute__((visibility("default"))) UTType *UTTypeM3UPlaylist;
__attribute__((visibility("default"))) UTType *UTTypeMIDI;
__attribute__((visibility("default"))) UTType *UTTypeMP3;
__attribute__((visibility("default"))) UTType *UTTypeMPEG;
__attribute__((visibility("default"))) UTType *UTTypeMPEG2TransportStream;
__attribute__((visibility("default"))) UTType *UTTypeMPEG2Video;
__attribute__((visibility("default"))) UTType *UTTypeMPEG4Audio;
__attribute__((visibility("default"))) UTType *UTTypeMPEG4Movie;
__attribute__((visibility("default"))) UTType *UTTypeMakefile;
__attribute__((visibility("default"))) UTType *UTTypeMessage;
__attribute__((visibility("default"))) UTType *UTTypeMountPoint;
__attribute__((visibility("default"))) UTType *UTTypeMovie;
__attribute__((visibility("default"))) UTType *UTTypeOSAScript;
__attribute__((visibility("default"))) UTType *UTTypeOSAScriptBundle;
__attribute__((visibility("default"))) UTType *UTTypeObjectiveCPlusPlusSource;
__attribute__((visibility("default"))) UTType *UTTypeObjectiveCSource;
__attribute__((visibility("default"))) UTType *UTTypePDF;
__attribute__((visibility("default"))) UTType *UTTypePHPScript;
__attribute__((visibility("default"))) UTType *UTTypePKCS12;
__attribute__((visibility("default"))) UTType *UTTypePNG;
__attribute__((visibility("default"))) UTType *UTTypePackage;
__attribute__((visibility("default"))) UTType *UTTypePerlScript;
__attribute__((visibility("default"))) UTType *UTTypePlainText;
__attribute__((visibility("default"))) UTType *UTTypePlaylist;
__attribute__((visibility("default"))) UTType *UTTypePluginBundle;
__attribute__((visibility("default"))) UTType *UTTypePresentation;
__attribute__((visibility("default"))) UTType *UTTypePropertyList;
__attribute__((visibility("default"))) UTType *UTTypePythonScript;
__attribute__((visibility("default"))) UTType *UTTypeQuickLookGenerator;
__attribute__((visibility("default"))) UTType *UTTypeQuickTimeMovie;
__attribute__((visibility("default"))) UTType *UTTypeRAWImage;
__attribute__((visibility("default"))) UTType *UTTypeRTF;
__attribute__((visibility("default"))) UTType *UTTypeRTFD;
__attribute__((visibility("default"))) UTType *UTTypeRealityFile;
__attribute__((visibility("default"))) UTType *UTTypeResolvable;
__attribute__((visibility("default"))) UTType *UTTypeRubyScript;
__attribute__((visibility("default"))) UTType *UTTypeSVG;
__attribute__((visibility("default"))) UTType *UTTypeSceneKitScene;
__attribute__((visibility("default"))) UTType *UTTypeScript;
__attribute__((visibility("default"))) UTType *UTTypeShellScript;
__attribute__((visibility("default"))) UTType *UTTypeSourceCode;
__attribute__((visibility("default"))) UTType *UTTypeSpotlightImporter;
__attribute__((visibility("default"))) UTType *UTTypeSpreadsheet;
__attribute__((visibility("default"))) UTType *UTTypeSwiftSource;
__attribute__((visibility("default"))) UTType *UTTypeSymbolicLink;
__attribute__((visibility("default"))) UTType *UTTypeSystemPreferencesPane;
__attribute__((visibility("default"))) UTType *UTTypeTIFF;
__attribute__((visibility("default"))) UTType *UTTypeTabSeparatedText;
__attribute__((visibility("default"))) UTType *UTTypeTarArchive;
__attribute__((visibility("default"))) UTType *UTTypeText;
__attribute__((visibility("default"))) UTType *UTTypeToDoItem;
__attribute__((visibility("default"))) UTType *UTTypeURL;
__attribute__((visibility("default"))) UTType *UTTypeURLBookmarkData;
__attribute__((visibility("default"))) UTType *UTTypeUSD;
__attribute__((visibility("default"))) UTType *UTTypeUSDZ;
__attribute__((visibility("default"))) UTType *UTTypeUTF16ExternalPlainText;
__attribute__((visibility("default"))) UTType *UTTypeUTF16PlainText;
__attribute__((visibility("default"))) UTType *UTTypeUTF8PlainText;
__attribute__((visibility("default"))) UTType *UTTypeUTF8TabSeparatedText;
__attribute__((visibility("default"))) UTType *UTTypeUnixExecutable;
__attribute__((visibility("default"))) UTType *UTTypeVCard;
__attribute__((visibility("default"))) UTType *UTTypeVideo;
__attribute__((visibility("default"))) UTType *UTTypeVolume;
__attribute__((visibility("default"))) UTType *UTTypeWAV;
__attribute__((visibility("default"))) UTType *UTTypeWebArchive;
__attribute__((visibility("default"))) UTType *UTTypeWebP;
__attribute__((visibility("default"))) UTType *UTTypeX509Certificate;
__attribute__((visibility("default"))) UTType *UTTypeXML;
__attribute__((visibility("default"))) UTType *UTTypeXMLPropertyList;
__attribute__((visibility("default"))) UTType *UTTypeXPCService;
__attribute__((visibility("default"))) UTType *UTTypeYAML;
__attribute__((visibility("default"))) UTType *UTTypeZIP;

__attribute__((constructor)) static void
set_core_types(void)
{
    @autoreleasepool {
        UTType3DContent = [[UTType typeWithIdentifier:@"public.3d-content"] retain];
        UTTypeAHAP = [[UTType typeWithIdentifier:@"com.apple.haptics.ahap"] retain];
        UTTypeAIFF = [[UTType typeWithIdentifier:@"public.aiff-audio"] retain];
        UTTypeARReferenceObject = [[UTType typeWithIdentifier:@"com.apple.arobject"] retain];
        UTTypeAVI = [[UTType typeWithIdentifier:@"public.avi"] retain];
        UTTypeAliasFile = [[UTType typeWithIdentifier:@"com.apple.alias-file"] retain];
        UTTypeAppleArchive = [[UTType typeWithIdentifier:@"com.apple.archive"] retain];
        UTTypeAppleProtectedMPEG4Audio = [[UTType typeWithIdentifier:@"com.apple.protected-mpeg-4-audio"] retain];
        UTTypeAppleProtectedMPEG4Video = [[UTType typeWithIdentifier:@"com.apple.protected-mpeg-4-video"] retain];
        UTTypeAppleScript = [[UTType typeWithIdentifier:@"com.apple.applescript.text"] retain];
        UTTypeApplication = [[UTType typeWithIdentifier:@"com.apple.application"] retain];
        UTTypeApplicationBundle = [[UTType typeWithIdentifier:@"com.apple.application-bundle"] retain];
        UTTypeApplicationExtension = [[UTType typeWithIdentifier:@"com.apple.application-and-system-extension"] retain];
        UTTypeArchive = [[UTType typeWithIdentifier:@"public.archive"] retain];
        UTTypeAssemblyLanguageSource = [[UTType typeWithIdentifier:@"public.assembly-source"] retain];
        UTTypeAudio = [[UTType typeWithIdentifier:@"public.audio"] retain];
        UTTypeAudiovisualContent = [[UTType typeWithIdentifier:@"public.audiovisual-content"] retain];
        UTTypeBMP = [[UTType typeWithIdentifier:@"com.microsoft.bmp"] retain];
        UTTypeBZ2 = [[UTType typeWithIdentifier:@"public.bzip2-archive"] retain];
        UTTypeBinaryPropertyList = [[UTType typeWithIdentifier:@"com.apple.binary-property-list"] retain];
        UTTypeBookmark = [[UTType typeWithIdentifier:@"public.bookmark"] retain];
        UTTypeBundle = [[UTType typeWithIdentifier:@"com.apple.bundle"] retain];
        UTTypeCHeader = [[UTType typeWithIdentifier:@"public.c-header"] retain];
        UTTypeCPlusPlusHeader = [[UTType typeWithIdentifier:@"public.c-plus-plus-header"] retain];
        UTTypeCPlusPlusSource = [[UTType typeWithIdentifier:@"public.c-plus-plus-source"] retain];
        UTTypeCSS = [[UTType typeWithIdentifier:@"public.css"] retain];
        UTTypeCSource = [[UTType typeWithIdentifier:@"public.c-source"] retain];
        UTTypeCalendarEvent = [[UTType typeWithIdentifier:@"public.calendar-event"] retain];
        UTTypeCommaSeparatedText = [[UTType typeWithIdentifier:@"public.comma-separated-values-text"] retain];
        UTTypeCompositeContent = [[UTType typeWithIdentifier:@"public.composite-content"] retain];
        UTTypeContact = [[UTType typeWithIdentifier:@"public.contact"] retain];
        UTTypeContent = [[UTType typeWithIdentifier:@"public.content"] retain];
        UTTypeDNG = [[UTType typeWithIdentifier:@"com.adobe.raw-image"] retain];
        UTTypeData = [[UTType typeWithIdentifier:@"public.data"] retain];
        UTTypeDatabase = [[UTType typeWithIdentifier:@"public.database"] retain];
        UTTypeDelimitedText = [[UTType typeWithIdentifier:@"public.delimited-values-text"] retain];
        UTTypeDirectory = [[UTType typeWithIdentifier:@"public.directory"] retain];
        UTTypeDiskImage = [[UTType typeWithIdentifier:@"public.disk-image"] retain];
        UTTypeEPUB = [[UTType typeWithIdentifier:@"org.idpf.epub-container"] retain];
        UTTypeEXE = [[UTType typeWithIdentifier:@"com.microsoft.windows-executable"] retain];
        UTTypeEXR = [[UTType typeWithIdentifier:@"com.ilm.openexr-image"] retain];
        UTTypeEmailMessage = [[UTType typeWithIdentifier:@"public.email-message"] retain];
        UTTypeExecutable = [[UTType typeWithIdentifier:@"public.executable"] retain];
        UTTypeFileURL = [[UTType typeWithIdentifier:@"public.file-url"] retain];
        UTTypeFlatRTFD = [[UTType typeWithIdentifier:@"com.apple.flat-rtfd"] retain];
        UTTypeFolder = [[UTType typeWithIdentifier:@"public.folder"] retain];
        UTTypeFont = [[UTType typeWithIdentifier:@"public.font"] retain];
        UTTypeFramework = [[UTType typeWithIdentifier:@"com.apple.framework"] retain];
        UTTypeGIF = [[UTType typeWithIdentifier:@"com.compuserve.gif"] retain];
        UTTypeGZIP = [[UTType typeWithIdentifier:@"org.gnu.gnu-zip-archive"] retain];
        UTTypeGeoJSON = [[UTType typeWithIdentifier:@"public.geojson"] retain];
        UTTypeHEIC = [[UTType typeWithIdentifier:@"public.heic"] retain];
        UTTypeHEICS = [[UTType typeWithIdentifier:@"public.heics"] retain];
        UTTypeHEIF = [[UTType typeWithIdentifier:@"public.heif"] retain];
        UTTypeHTML = [[UTType typeWithIdentifier:@"public.html"] retain];
        UTTypeICNS = [[UTType typeWithIdentifier:@"com.apple.icns"] retain];
        UTTypeICO = [[UTType typeWithIdentifier:@"com.microsoft.ico"] retain];
        UTTypeImage = [[UTType typeWithIdentifier:@"public.image"] retain];
        UTTypeInternetLocation = [[UTType typeWithIdentifier:@"com.apple.internet-location"] retain];
        UTTypeInternetShortcut = [[UTType typeWithIdentifier:@"com.microsoft.internet-shortcut"] retain];
        UTTypeItem = [[UTType typeWithIdentifier:@"public.item"] retain];
        UTTypeJPEG = [[UTType typeWithIdentifier:@"public.jpeg"] retain];
        UTTypeJPEGXL = [[UTType typeWithIdentifier:@"public.jpeg-xl"] retain];
        UTTypeJSON = [[UTType typeWithIdentifier:@"public.json"] retain];
        UTTypeJavaScript = [[UTType typeWithIdentifier:@"com.netscape.javascript-source"] retain];
        UTTypeLinkPresentationMetadata = [[UTType typeWithIdentifier:@"com.apple.linkpresentation.metadata"] retain];
        UTTypeLivePhoto = [[UTType typeWithIdentifier:@"com.apple.live-photo"] retain];
        UTTypeLog = [[UTType typeWithIdentifier:@"public.log"] retain];
        UTTypeM3UPlaylist = [[UTType typeWithIdentifier:@"public.m3u-playlist"] retain];
        UTTypeMIDI = [[UTType typeWithIdentifier:@"public.midi-audio"] retain];
        UTTypeMP3 = [[UTType typeWithIdentifier:@"public.mp3"] retain];
        UTTypeMPEG = [[UTType typeWithIdentifier:@"public.mpeg"] retain];
        UTTypeMPEG2TransportStream = [[UTType typeWithIdentifier:@"public.mpeg-2-transport-stream"] retain];
        UTTypeMPEG2Video = [[UTType typeWithIdentifier:@"public.mpeg-2-video"] retain];
        UTTypeMPEG4Audio = [[UTType typeWithIdentifier:@"public.mpeg-4-audio"] retain];
        UTTypeMPEG4Movie = [[UTType typeWithIdentifier:@"public.mpeg-4"] retain];
        UTTypeMakefile = [[UTType typeWithIdentifier:@"public.make-source"] retain];
        UTTypeMessage = [[UTType typeWithIdentifier:@"public.message"] retain];
        UTTypeMountPoint = [[UTType typeWithIdentifier:@"com.apple.mount-point"] retain];
        UTTypeMovie = [[UTType typeWithIdentifier:@"public.movie"] retain];
        UTTypeOSAScript = [[UTType typeWithIdentifier:@"com.apple.applescript.script"] retain];
        UTTypeOSAScriptBundle = [[UTType typeWithIdentifier:@"com.apple.applescript.script-bundle"] retain];
        UTTypeObjectiveCPlusPlusSource = [[UTType typeWithIdentifier:@"public.objective-c-plus-plus-source"] retain];
        UTTypeObjectiveCSource = [[UTType typeWithIdentifier:@"public.objective-c-source"] retain];
        UTTypePDF = [[UTType typeWithIdentifier:@"com.adobe.pdf"] retain];
        UTTypePHPScript = [[UTType typeWithIdentifier:@"public.php-script"] retain];
        UTTypePKCS12 = [[UTType typeWithIdentifier:@"com.rsa.pkcs-12"] retain];
        UTTypePNG = [[UTType typeWithIdentifier:@"public.png"] retain];
        UTTypePackage = [[UTType typeWithIdentifier:@"com.apple.package"] retain];
        UTTypePerlScript = [[UTType typeWithIdentifier:@"public.perl-script"] retain];
        UTTypePlainText = [[UTType typeWithIdentifier:@"public.plain-text"] retain];
        UTTypePlaylist = [[UTType typeWithIdentifier:@"public.playlist"] retain];
        UTTypePluginBundle = [[UTType typeWithIdentifier:@"com.apple.plugin"] retain];
        UTTypePresentation = [[UTType typeWithIdentifier:@"public.presentation"] retain];
        UTTypePropertyList = [[UTType typeWithIdentifier:@"com.apple.property-list"] retain];
        UTTypePythonScript = [[UTType typeWithIdentifier:@"public.python-script"] retain];
        UTTypeQuickLookGenerator = [[UTType typeWithIdentifier:@"com.apple.quicklook-generator"] retain];
        UTTypeQuickTimeMovie = [[UTType typeWithIdentifier:@"com.apple.quicktime-movie"] retain];
        UTTypeRAWImage = [[UTType typeWithIdentifier:@"public.camera-raw-image"] retain];
        UTTypeRTF = [[UTType typeWithIdentifier:@"public.rtf"] retain];
        UTTypeRTFD = [[UTType typeWithIdentifier:@"com.apple.rtfd"] retain];
        UTTypeRealityFile = [[UTType typeWithIdentifier:@"com.apple.reality"] retain];
        UTTypeResolvable = [[UTType typeWithIdentifier:@"com.apple.resolvable"] retain];
        UTTypeRubyScript = [[UTType typeWithIdentifier:@"public.ruby-script"] retain];
        UTTypeSVG = [[UTType typeWithIdentifier:@"public.svg-image"] retain];
        UTTypeSceneKitScene = [[UTType typeWithIdentifier:@"com.apple.scenekit.scene"] retain];
        UTTypeScript = [[UTType typeWithIdentifier:@"public.script"] retain];
        UTTypeShellScript = [[UTType typeWithIdentifier:@"public.shell-script"] retain];
        UTTypeSourceCode = [[UTType typeWithIdentifier:@"public.source-code"] retain];
        UTTypeSpotlightImporter = [[UTType typeWithIdentifier:@"com.apple.metadata-importer"] retain];
        UTTypeSpreadsheet = [[UTType typeWithIdentifier:@"public.spreadsheet"] retain];
        UTTypeSwiftSource = [[UTType typeWithIdentifier:@"public.swift-source"] retain];
        UTTypeSymbolicLink = [[UTType typeWithIdentifier:@"public.symlink"] retain];
        UTTypeSystemPreferencesPane = [[UTType typeWithIdentifier:@"com.apple.systempreference.prefpane"] retain];
        UTTypeTIFF = [[UTType typeWithIdentifier:@"public.tiff"] retain];
        UTTypeTabSeparatedText = [[UTType typeWithIdentifier:@"public.tab-separated-values-text"] retain];
        UTTypeTarArchive = [[UTType typeWithIdentifier:@"public.tar-archive"] retain];
        UTTypeText = [[UTType typeWithIdentifier:@"public.text"] retain];
        UTTypeToDoItem = [[UTType typeWithIdentifier:@"public.to-do-item"] retain];
        UTTypeURL = [[UTType typeWithIdentifier:@"public.url"] retain];
        UTTypeURLBookmarkData = [[UTType typeWithIdentifier:@"com.apple.bookmark"] retain];
        UTTypeUSD = [[UTType typeWithIdentifier:@"com.pixar.universal-scene-description"] retain];
        UTTypeUSDZ = [[UTType typeWithIdentifier:@"com.pixar.universal-scene-description-mobile"] retain];
        UTTypeUTF16ExternalPlainText = [[UTType typeWithIdentifier:@"public.utf16-external-plain-text"] retain];
        UTTypeUTF16PlainText = [[UTType typeWithIdentifier:@"public.utf16-plain-text"] retain];
        UTTypeUTF8PlainText = [[UTType typeWithIdentifier:@"public.utf8-plain-text"] retain];
        UTTypeUTF8TabSeparatedText = [[UTType typeWithIdentifier:@"public.utf8-tab-separated-values-text"] retain];
        UTTypeUnixExecutable = [[UTType typeWithIdentifier:@"public.unix-executable"] retain];
        UTTypeVCard = [[UTType typeWithIdentifier:@"public.vcard"] retain];
        UTTypeVideo = [[UTType typeWithIdentifier:@"public.video"] retain];
        UTTypeVolume = [[UTType typeWithIdentifier:@"public.volume"] retain];
        UTTypeWAV = [[UTType typeWithIdentifier:@"com.microsoft.waveform-audio"] retain];
        UTTypeWebArchive = [[UTType typeWithIdentifier:@"com.apple.webarchive"] retain];
        UTTypeWebP = [[UTType typeWithIdentifier:@"org.webmproject.webp"] retain];
        UTTypeX509Certificate = [[UTType typeWithIdentifier:@"public.x509-certificate"] retain];
        UTTypeXML = [[UTType typeWithIdentifier:@"public.xml"] retain];
        UTTypeXMLPropertyList = [[UTType typeWithIdentifier:@"com.apple.xml-property-list"] retain];
        UTTypeXPCService = [[UTType typeWithIdentifier:@"com.apple.xpc-service"] retain];
        UTTypeYAML = [[UTType typeWithIdentifier:@"public.yaml"] retain];
        UTTypeZIP = [[UTType typeWithIdentifier:@"public.zip-archive"] retain];
    }
}
