// SPDX-License-Identifier: MIT OR Apache-2.0
// Generated by userland/Combine/gen.py: do not edit.


extension Publisher {
    public func combineLatest<P>(_ other: P) -> Publishers.CombineLatest<Self, P> where P: Publisher, Self.Failure == P.Failure {
        return Publishers.CombineLatest(self, other)
    }
    public func combineLatest<P, T>(_ other: P, _ transform: @escaping (Self.Output, P.Output) -> T) -> Publishers.Map<Publishers.CombineLatest<Self, P>, T> where P: Publisher, Self.Failure == P.Failure {
        return Publishers.CombineLatest(self, other).map(transform)
    }
    public func combineLatest<P, Q>(_ publisher1: P, _ publisher2: Q) -> Publishers.CombineLatest3<Self, P, Q> where P: Publisher, Q: Publisher, Self.Failure == P.Failure, P.Failure == Q.Failure {
        return Publishers.CombineLatest3(self, publisher1, publisher2)
    }
    public func combineLatest<P, Q, T>(_ publisher1: P, _ publisher2: Q, _ transform: @escaping (Self.Output, P.Output, Q.Output) -> T) -> Publishers.Map<Publishers.CombineLatest3<Self, P, Q>, T> where P: Publisher, Q: Publisher, Self.Failure == P.Failure, P.Failure == Q.Failure {
        return Publishers.CombineLatest3(self, publisher1, publisher2).map(transform)
    }
    public func combineLatest<P, Q, R>(_ publisher1: P, _ publisher2: Q, _ publisher3: R) -> Publishers.CombineLatest4<Self, P, Q, R> where P: Publisher, Q: Publisher, R: Publisher, Self.Failure == P.Failure, P.Failure == Q.Failure, Q.Failure == R.Failure {
        return Publishers.CombineLatest4(self, publisher1, publisher2, publisher3)
    }
    public func combineLatest<P, Q, R, T>(_ publisher1: P, _ publisher2: Q, _ publisher3: R, _ transform: @escaping (Self.Output, P.Output, Q.Output, R.Output) -> T) -> Publishers.Map<Publishers.CombineLatest4<Self, P, Q, R>, T> where P: Publisher, Q: Publisher, R: Publisher, Self.Failure == P.Failure, P.Failure == Q.Failure, Q.Failure == R.Failure {
        return Publishers.CombineLatest4(self, publisher1, publisher2, publisher3).map(transform)
    }
}

extension Publishers {
    public struct CombineLatest<A, B>: Publisher where A: Publisher, B: Publisher, A.Failure == B.Failure {
        public typealias Output = (A.Output, B.Output)
        public typealias Failure = A.Failure
        public let a: A
        public let b: B
        public init(_ a: A, _ b: B) {
            self.a = a
            self.b = b
        }
        public func receive<S>(subscriber: S) where S: Subscriber, B.Failure == S.Failure, S.Input == (A.Output, B.Output) {
            let fan = _FinchFanIn<Output, Failure>("CombineLatest", count: 2, downstream: AnySubscriber(subscriber), make: { v in (v[0] as! A.Output, v[1] as! B.Output) })
            subscriber.receive(subscription: fan)
            a.subscribe(fan.side(0, A.Output.self))
            b.subscribe(fan.side(1, B.Output.self))
        }
    }
    public struct CombineLatest3<A, B, C>: Publisher where A: Publisher, B: Publisher, C: Publisher, A.Failure == B.Failure, B.Failure == C.Failure {
        public typealias Output = (A.Output, B.Output, C.Output)
        public typealias Failure = A.Failure
        public let a: A
        public let b: B
        public let c: C
        public init(_ a: A, _ b: B, _ c: C) {
            self.a = a
            self.b = b
            self.c = c
        }
        public func receive<S>(subscriber: S) where S: Subscriber, C.Failure == S.Failure, S.Input == (A.Output, B.Output, C.Output) {
            let fan = _FinchFanIn<Output, Failure>("CombineLatest3", count: 3, downstream: AnySubscriber(subscriber), make: { v in (v[0] as! A.Output, v[1] as! B.Output, v[2] as! C.Output) })
            subscriber.receive(subscription: fan)
            a.subscribe(fan.side(0, A.Output.self))
            b.subscribe(fan.side(1, B.Output.self))
            c.subscribe(fan.side(2, C.Output.self))
        }
    }
    public struct CombineLatest4<A, B, C, D>: Publisher where A: Publisher, B: Publisher, C: Publisher, D: Publisher, A.Failure == B.Failure, B.Failure == C.Failure, C.Failure == D.Failure {
        public typealias Output = (A.Output, B.Output, C.Output, D.Output)
        public typealias Failure = A.Failure
        public let a: A
        public let b: B
        public let c: C
        public let d: D
        public init(_ a: A, _ b: B, _ c: C, _ d: D) {
            self.a = a
            self.b = b
            self.c = c
            self.d = d
        }
        public func receive<S>(subscriber: S) where S: Subscriber, D.Failure == S.Failure, S.Input == (A.Output, B.Output, C.Output, D.Output) {
            let fan = _FinchFanIn<Output, Failure>("CombineLatest4", count: 4, downstream: AnySubscriber(subscriber), make: { v in (v[0] as! A.Output, v[1] as! B.Output, v[2] as! C.Output, v[3] as! D.Output) })
            subscriber.receive(subscription: fan)
            a.subscribe(fan.side(0, A.Output.self))
            b.subscribe(fan.side(1, B.Output.self))
            c.subscribe(fan.side(2, C.Output.self))
            d.subscribe(fan.side(3, D.Output.self))
        }
    }
}

extension Publishers.CombineLatest: Equatable where A: Equatable, B: Equatable {
    public static func == (lhs: Publishers.CombineLatest<A, B>, rhs: Publishers.CombineLatest<A, B>) -> Bool {
        return lhs.a == rhs.a && lhs.b == rhs.b
    }
}

extension Publishers.CombineLatest3: Equatable where A: Equatable, B: Equatable, C: Equatable {
    public static func == (lhs: Publishers.CombineLatest3<A, B, C>, rhs: Publishers.CombineLatest3<A, B, C>) -> Bool {
        return lhs.a == rhs.a && lhs.b == rhs.b && lhs.c == rhs.c
    }
}

extension Publishers.CombineLatest4: Equatable where A: Equatable, B: Equatable, C: Equatable, D: Equatable {
    public static func == (lhs: Publishers.CombineLatest4<A, B, C, D>, rhs: Publishers.CombineLatest4<A, B, C, D>) -> Bool {
        return lhs.a == rhs.a && lhs.b == rhs.b && lhs.c == rhs.c && lhs.d == rhs.d
    }
}
