/*
 * Copyright (c) 2026 The Finch Project contributors.
 * SPDX-License-Identifier: MIT OR Apache-2.0
 *
 * Generated by tools/gen-dyld-versions.py: dyld SDK / min-OS version
 * constants that Apple strips from the published <mach-o/dyld_priv.h>.
 * Form as in earlier dyld releases.
 */
#ifndef _FINCH_DYLD_VERSIONS_H_
#define _FINCH_DYLD_VERSIONS_H_

#define DYLD_MACOSX_VERSION_10_0 0x000A0000
#define dyld_platform_version_macOS_10_0 ({ (dyld_build_version_t){1, 0x000A0000}; })
#define DYLD_MACOSX_VERSION_10_1 0x000A0100
#define dyld_platform_version_macOS_10_1 ({ (dyld_build_version_t){1, 0x000A0100}; })
#define DYLD_MACOSX_VERSION_10_2 0x000A0200
#define dyld_platform_version_macOS_10_2 ({ (dyld_build_version_t){1, 0x000A0200}; })
#define DYLD_MACOSX_VERSION_10_3 0x000A0300
#define dyld_platform_version_macOS_10_3 ({ (dyld_build_version_t){1, 0x000A0300}; })
#define DYLD_MACOSX_VERSION_10_4 0x000A0400
#define dyld_platform_version_macOS_10_4 ({ (dyld_build_version_t){1, 0x000A0400}; })
#define DYLD_MACOSX_VERSION_10_5 0x000A0500
#define dyld_platform_version_macOS_10_5 ({ (dyld_build_version_t){1, 0x000A0500}; })
#define DYLD_MACOSX_VERSION_10_6 0x000A0600
#define dyld_platform_version_macOS_10_6 ({ (dyld_build_version_t){1, 0x000A0600}; })
#define DYLD_MACOSX_VERSION_10_7 0x000A0700
#define dyld_platform_version_macOS_10_7 ({ (dyld_build_version_t){1, 0x000A0700}; })
#define DYLD_MACOSX_VERSION_10_8 0x000A0800
#define dyld_platform_version_macOS_10_8 ({ (dyld_build_version_t){1, 0x000A0800}; })
#define DYLD_MACOSX_VERSION_10_9 0x000A0900
#define dyld_platform_version_macOS_10_9 ({ (dyld_build_version_t){1, 0x000A0900}; })
#define DYLD_MACOSX_VERSION_10_10 0x000A0A00
#define dyld_platform_version_macOS_10_10 ({ (dyld_build_version_t){1, 0x000A0A00}; })
#define DYLD_MACOSX_VERSION_10_11 0x000A0B00
#define dyld_platform_version_macOS_10_11 ({ (dyld_build_version_t){1, 0x000A0B00}; })
#define DYLD_MACOSX_VERSION_10_12 0x000A0C00
#define dyld_platform_version_macOS_10_12 ({ (dyld_build_version_t){1, 0x000A0C00}; })
#define DYLD_MACOSX_VERSION_10_13 0x000A0D00
#define dyld_platform_version_macOS_10_13 ({ (dyld_build_version_t){1, 0x000A0D00}; })
#define DYLD_MACOSX_VERSION_10_14 0x000A0E00
#define dyld_platform_version_macOS_10_14 ({ (dyld_build_version_t){1, 0x000A0E00}; })
#define DYLD_MACOSX_VERSION_10_15 0x000A0F00
#define dyld_platform_version_macOS_10_15 ({ (dyld_build_version_t){1, 0x000A0F00}; })
#define DYLD_MACOSX_VERSION_11_0 0x000B0000
#define dyld_platform_version_macOS_11_0 ({ (dyld_build_version_t){1, 0x000B0000}; })
#define DYLD_MACOSX_VERSION_11_1 0x000B0100
#define dyld_platform_version_macOS_11_1 ({ (dyld_build_version_t){1, 0x000B0100}; })
#define DYLD_MACOSX_VERSION_11_2 0x000B0200
#define dyld_platform_version_macOS_11_2 ({ (dyld_build_version_t){1, 0x000B0200}; })
#define DYLD_MACOSX_VERSION_11_3 0x000B0300
#define dyld_platform_version_macOS_11_3 ({ (dyld_build_version_t){1, 0x000B0300}; })
#define DYLD_MACOSX_VERSION_11_4 0x000B0400
#define dyld_platform_version_macOS_11_4 ({ (dyld_build_version_t){1, 0x000B0400}; })
#define DYLD_MACOSX_VERSION_11_5 0x000B0500
#define dyld_platform_version_macOS_11_5 ({ (dyld_build_version_t){1, 0x000B0500}; })
#define DYLD_MACOSX_VERSION_11_6 0x000B0600
#define dyld_platform_version_macOS_11_6 ({ (dyld_build_version_t){1, 0x000B0600}; })
#define DYLD_MACOSX_VERSION_11_7 0x000B0700
#define dyld_platform_version_macOS_11_7 ({ (dyld_build_version_t){1, 0x000B0700}; })
#define DYLD_MACOSX_VERSION_12_0 0x000C0000
#define dyld_platform_version_macOS_12_0 ({ (dyld_build_version_t){1, 0x000C0000}; })
#define DYLD_MACOSX_VERSION_12_1 0x000C0100
#define dyld_platform_version_macOS_12_1 ({ (dyld_build_version_t){1, 0x000C0100}; })
#define DYLD_MACOSX_VERSION_12_2 0x000C0200
#define dyld_platform_version_macOS_12_2 ({ (dyld_build_version_t){1, 0x000C0200}; })
#define DYLD_MACOSX_VERSION_12_3 0x000C0300
#define dyld_platform_version_macOS_12_3 ({ (dyld_build_version_t){1, 0x000C0300}; })
#define DYLD_MACOSX_VERSION_12_4 0x000C0400
#define dyld_platform_version_macOS_12_4 ({ (dyld_build_version_t){1, 0x000C0400}; })
#define DYLD_MACOSX_VERSION_12_5 0x000C0500
#define dyld_platform_version_macOS_12_5 ({ (dyld_build_version_t){1, 0x000C0500}; })
#define DYLD_MACOSX_VERSION_12_6 0x000C0600
#define dyld_platform_version_macOS_12_6 ({ (dyld_build_version_t){1, 0x000C0600}; })
#define DYLD_MACOSX_VERSION_12_7 0x000C0700
#define dyld_platform_version_macOS_12_7 ({ (dyld_build_version_t){1, 0x000C0700}; })
#define DYLD_MACOSX_VERSION_13_0 0x000D0000
#define dyld_platform_version_macOS_13_0 ({ (dyld_build_version_t){1, 0x000D0000}; })
#define DYLD_MACOSX_VERSION_13_1 0x000D0100
#define dyld_platform_version_macOS_13_1 ({ (dyld_build_version_t){1, 0x000D0100}; })
#define DYLD_MACOSX_VERSION_13_2 0x000D0200
#define dyld_platform_version_macOS_13_2 ({ (dyld_build_version_t){1, 0x000D0200}; })
#define DYLD_MACOSX_VERSION_13_3 0x000D0300
#define dyld_platform_version_macOS_13_3 ({ (dyld_build_version_t){1, 0x000D0300}; })
#define DYLD_MACOSX_VERSION_13_4 0x000D0400
#define dyld_platform_version_macOS_13_4 ({ (dyld_build_version_t){1, 0x000D0400}; })
#define DYLD_MACOSX_VERSION_13_5 0x000D0500
#define dyld_platform_version_macOS_13_5 ({ (dyld_build_version_t){1, 0x000D0500}; })
#define DYLD_MACOSX_VERSION_13_6 0x000D0600
#define dyld_platform_version_macOS_13_6 ({ (dyld_build_version_t){1, 0x000D0600}; })
#define DYLD_MACOSX_VERSION_13_7 0x000D0700
#define dyld_platform_version_macOS_13_7 ({ (dyld_build_version_t){1, 0x000D0700}; })
#define DYLD_MACOSX_VERSION_14_0 0x000E0000
#define dyld_platform_version_macOS_14_0 ({ (dyld_build_version_t){1, 0x000E0000}; })
#define DYLD_MACOSX_VERSION_14_1 0x000E0100
#define dyld_platform_version_macOS_14_1 ({ (dyld_build_version_t){1, 0x000E0100}; })
#define DYLD_MACOSX_VERSION_14_2 0x000E0200
#define dyld_platform_version_macOS_14_2 ({ (dyld_build_version_t){1, 0x000E0200}; })
#define DYLD_MACOSX_VERSION_14_3 0x000E0300
#define dyld_platform_version_macOS_14_3 ({ (dyld_build_version_t){1, 0x000E0300}; })
#define DYLD_MACOSX_VERSION_14_4 0x000E0400
#define dyld_platform_version_macOS_14_4 ({ (dyld_build_version_t){1, 0x000E0400}; })
#define DYLD_MACOSX_VERSION_14_5 0x000E0500
#define dyld_platform_version_macOS_14_5 ({ (dyld_build_version_t){1, 0x000E0500}; })
#define DYLD_MACOSX_VERSION_14_6 0x000E0600
#define dyld_platform_version_macOS_14_6 ({ (dyld_build_version_t){1, 0x000E0600}; })
#define DYLD_MACOSX_VERSION_14_7 0x000E0700
#define dyld_platform_version_macOS_14_7 ({ (dyld_build_version_t){1, 0x000E0700}; })
#define DYLD_MACOSX_VERSION_15_0 0x000F0000
#define dyld_platform_version_macOS_15_0 ({ (dyld_build_version_t){1, 0x000F0000}; })
#define DYLD_MACOSX_VERSION_15_1 0x000F0100
#define dyld_platform_version_macOS_15_1 ({ (dyld_build_version_t){1, 0x000F0100}; })
#define DYLD_MACOSX_VERSION_15_2 0x000F0200
#define dyld_platform_version_macOS_15_2 ({ (dyld_build_version_t){1, 0x000F0200}; })
#define DYLD_MACOSX_VERSION_15_3 0x000F0300
#define dyld_platform_version_macOS_15_3 ({ (dyld_build_version_t){1, 0x000F0300}; })
#define DYLD_MACOSX_VERSION_15_4 0x000F0400
#define dyld_platform_version_macOS_15_4 ({ (dyld_build_version_t){1, 0x000F0400}; })
#define DYLD_MACOSX_VERSION_15_5 0x000F0500
#define dyld_platform_version_macOS_15_5 ({ (dyld_build_version_t){1, 0x000F0500}; })
#define DYLD_MACOSX_VERSION_15_6 0x000F0600
#define dyld_platform_version_macOS_15_6 ({ (dyld_build_version_t){1, 0x000F0600}; })
#define DYLD_MACOSX_VERSION_15_7 0x000F0700
#define dyld_platform_version_macOS_15_7 ({ (dyld_build_version_t){1, 0x000F0700}; })
#define DYLD_MACOSX_VERSION_26_0 0x001A0000
#define dyld_platform_version_macOS_26_0 ({ (dyld_build_version_t){1, 0x001A0000}; })
#define DYLD_MACOSX_VERSION_26_1 0x001A0100
#define dyld_platform_version_macOS_26_1 ({ (dyld_build_version_t){1, 0x001A0100}; })
#define DYLD_MACOSX_VERSION_26_2 0x001A0200
#define dyld_platform_version_macOS_26_2 ({ (dyld_build_version_t){1, 0x001A0200}; })
#define DYLD_MACOSX_VERSION_26_3 0x001A0300
#define dyld_platform_version_macOS_26_3 ({ (dyld_build_version_t){1, 0x001A0300}; })
#define DYLD_MACOSX_VERSION_26_4 0x001A0400
#define dyld_platform_version_macOS_26_4 ({ (dyld_build_version_t){1, 0x001A0400}; })
#define DYLD_MACOSX_VERSION_26_5 0x001A0500
#define dyld_platform_version_macOS_26_5 ({ (dyld_build_version_t){1, 0x001A0500}; })
#define DYLD_MACOSX_VERSION_26_6 0x001A0600
#define dyld_platform_version_macOS_26_6 ({ (dyld_build_version_t){1, 0x001A0600}; })
#define DYLD_MACOSX_VERSION_26_7 0x001A0700
#define dyld_platform_version_macOS_26_7 ({ (dyld_build_version_t){1, 0x001A0700}; })
#define DYLD_IOS_VERSION_2_0 0x00020000
#define dyld_platform_version_iOS_2_0 ({ (dyld_build_version_t){2, 0x00020000}; })
#define DYLD_IOS_VERSION_2_1 0x00020100
#define dyld_platform_version_iOS_2_1 ({ (dyld_build_version_t){2, 0x00020100}; })
#define DYLD_IOS_VERSION_2_2 0x00020200
#define dyld_platform_version_iOS_2_2 ({ (dyld_build_version_t){2, 0x00020200}; })
#define DYLD_IOS_VERSION_2_3 0x00020300
#define dyld_platform_version_iOS_2_3 ({ (dyld_build_version_t){2, 0x00020300}; })
#define DYLD_IOS_VERSION_2_4 0x00020400
#define dyld_platform_version_iOS_2_4 ({ (dyld_build_version_t){2, 0x00020400}; })
#define DYLD_IOS_VERSION_2_5 0x00020500
#define dyld_platform_version_iOS_2_5 ({ (dyld_build_version_t){2, 0x00020500}; })
#define DYLD_IOS_VERSION_2_6 0x00020600
#define dyld_platform_version_iOS_2_6 ({ (dyld_build_version_t){2, 0x00020600}; })
#define DYLD_IOS_VERSION_2_7 0x00020700
#define dyld_platform_version_iOS_2_7 ({ (dyld_build_version_t){2, 0x00020700}; })
#define DYLD_IOS_VERSION_3_0 0x00030000
#define dyld_platform_version_iOS_3_0 ({ (dyld_build_version_t){2, 0x00030000}; })
#define DYLD_IOS_VERSION_3_1 0x00030100
#define dyld_platform_version_iOS_3_1 ({ (dyld_build_version_t){2, 0x00030100}; })
#define DYLD_IOS_VERSION_3_2 0x00030200
#define dyld_platform_version_iOS_3_2 ({ (dyld_build_version_t){2, 0x00030200}; })
#define DYLD_IOS_VERSION_3_3 0x00030300
#define dyld_platform_version_iOS_3_3 ({ (dyld_build_version_t){2, 0x00030300}; })
#define DYLD_IOS_VERSION_3_4 0x00030400
#define dyld_platform_version_iOS_3_4 ({ (dyld_build_version_t){2, 0x00030400}; })
#define DYLD_IOS_VERSION_3_5 0x00030500
#define dyld_platform_version_iOS_3_5 ({ (dyld_build_version_t){2, 0x00030500}; })
#define DYLD_IOS_VERSION_3_6 0x00030600
#define dyld_platform_version_iOS_3_6 ({ (dyld_build_version_t){2, 0x00030600}; })
#define DYLD_IOS_VERSION_3_7 0x00030700
#define dyld_platform_version_iOS_3_7 ({ (dyld_build_version_t){2, 0x00030700}; })
#define DYLD_IOS_VERSION_4_0 0x00040000
#define dyld_platform_version_iOS_4_0 ({ (dyld_build_version_t){2, 0x00040000}; })
#define DYLD_IOS_VERSION_4_1 0x00040100
#define dyld_platform_version_iOS_4_1 ({ (dyld_build_version_t){2, 0x00040100}; })
#define DYLD_IOS_VERSION_4_2 0x00040200
#define dyld_platform_version_iOS_4_2 ({ (dyld_build_version_t){2, 0x00040200}; })
#define DYLD_IOS_VERSION_4_3 0x00040300
#define dyld_platform_version_iOS_4_3 ({ (dyld_build_version_t){2, 0x00040300}; })
#define DYLD_IOS_VERSION_4_4 0x00040400
#define dyld_platform_version_iOS_4_4 ({ (dyld_build_version_t){2, 0x00040400}; })
#define DYLD_IOS_VERSION_4_5 0x00040500
#define dyld_platform_version_iOS_4_5 ({ (dyld_build_version_t){2, 0x00040500}; })
#define DYLD_IOS_VERSION_4_6 0x00040600
#define dyld_platform_version_iOS_4_6 ({ (dyld_build_version_t){2, 0x00040600}; })
#define DYLD_IOS_VERSION_4_7 0x00040700
#define dyld_platform_version_iOS_4_7 ({ (dyld_build_version_t){2, 0x00040700}; })
#define DYLD_IOS_VERSION_5_0 0x00050000
#define dyld_platform_version_iOS_5_0 ({ (dyld_build_version_t){2, 0x00050000}; })
#define DYLD_IOS_VERSION_5_1 0x00050100
#define dyld_platform_version_iOS_5_1 ({ (dyld_build_version_t){2, 0x00050100}; })
#define DYLD_IOS_VERSION_5_2 0x00050200
#define dyld_platform_version_iOS_5_2 ({ (dyld_build_version_t){2, 0x00050200}; })
#define DYLD_IOS_VERSION_5_3 0x00050300
#define dyld_platform_version_iOS_5_3 ({ (dyld_build_version_t){2, 0x00050300}; })
#define DYLD_IOS_VERSION_5_4 0x00050400
#define dyld_platform_version_iOS_5_4 ({ (dyld_build_version_t){2, 0x00050400}; })
#define DYLD_IOS_VERSION_5_5 0x00050500
#define dyld_platform_version_iOS_5_5 ({ (dyld_build_version_t){2, 0x00050500}; })
#define DYLD_IOS_VERSION_5_6 0x00050600
#define dyld_platform_version_iOS_5_6 ({ (dyld_build_version_t){2, 0x00050600}; })
#define DYLD_IOS_VERSION_5_7 0x00050700
#define dyld_platform_version_iOS_5_7 ({ (dyld_build_version_t){2, 0x00050700}; })
#define DYLD_IOS_VERSION_6_0 0x00060000
#define dyld_platform_version_iOS_6_0 ({ (dyld_build_version_t){2, 0x00060000}; })
#define DYLD_IOS_VERSION_6_1 0x00060100
#define dyld_platform_version_iOS_6_1 ({ (dyld_build_version_t){2, 0x00060100}; })
#define DYLD_IOS_VERSION_6_2 0x00060200
#define dyld_platform_version_iOS_6_2 ({ (dyld_build_version_t){2, 0x00060200}; })
#define DYLD_IOS_VERSION_6_3 0x00060300
#define dyld_platform_version_iOS_6_3 ({ (dyld_build_version_t){2, 0x00060300}; })
#define DYLD_IOS_VERSION_6_4 0x00060400
#define dyld_platform_version_iOS_6_4 ({ (dyld_build_version_t){2, 0x00060400}; })
#define DYLD_IOS_VERSION_6_5 0x00060500
#define dyld_platform_version_iOS_6_5 ({ (dyld_build_version_t){2, 0x00060500}; })
#define DYLD_IOS_VERSION_6_6 0x00060600
#define dyld_platform_version_iOS_6_6 ({ (dyld_build_version_t){2, 0x00060600}; })
#define DYLD_IOS_VERSION_6_7 0x00060700
#define dyld_platform_version_iOS_6_7 ({ (dyld_build_version_t){2, 0x00060700}; })
#define DYLD_IOS_VERSION_7_0 0x00070000
#define dyld_platform_version_iOS_7_0 ({ (dyld_build_version_t){2, 0x00070000}; })
#define DYLD_IOS_VERSION_7_1 0x00070100
#define dyld_platform_version_iOS_7_1 ({ (dyld_build_version_t){2, 0x00070100}; })
#define DYLD_IOS_VERSION_7_2 0x00070200
#define dyld_platform_version_iOS_7_2 ({ (dyld_build_version_t){2, 0x00070200}; })
#define DYLD_IOS_VERSION_7_3 0x00070300
#define dyld_platform_version_iOS_7_3 ({ (dyld_build_version_t){2, 0x00070300}; })
#define DYLD_IOS_VERSION_7_4 0x00070400
#define dyld_platform_version_iOS_7_4 ({ (dyld_build_version_t){2, 0x00070400}; })
#define DYLD_IOS_VERSION_7_5 0x00070500
#define dyld_platform_version_iOS_7_5 ({ (dyld_build_version_t){2, 0x00070500}; })
#define DYLD_IOS_VERSION_7_6 0x00070600
#define dyld_platform_version_iOS_7_6 ({ (dyld_build_version_t){2, 0x00070600}; })
#define DYLD_IOS_VERSION_7_7 0x00070700
#define dyld_platform_version_iOS_7_7 ({ (dyld_build_version_t){2, 0x00070700}; })
#define DYLD_IOS_VERSION_8_0 0x00080000
#define dyld_platform_version_iOS_8_0 ({ (dyld_build_version_t){2, 0x00080000}; })
#define DYLD_IOS_VERSION_8_1 0x00080100
#define dyld_platform_version_iOS_8_1 ({ (dyld_build_version_t){2, 0x00080100}; })
#define DYLD_IOS_VERSION_8_2 0x00080200
#define dyld_platform_version_iOS_8_2 ({ (dyld_build_version_t){2, 0x00080200}; })
#define DYLD_IOS_VERSION_8_3 0x00080300
#define dyld_platform_version_iOS_8_3 ({ (dyld_build_version_t){2, 0x00080300}; })
#define DYLD_IOS_VERSION_8_4 0x00080400
#define dyld_platform_version_iOS_8_4 ({ (dyld_build_version_t){2, 0x00080400}; })
#define DYLD_IOS_VERSION_8_5 0x00080500
#define dyld_platform_version_iOS_8_5 ({ (dyld_build_version_t){2, 0x00080500}; })
#define DYLD_IOS_VERSION_8_6 0x00080600
#define dyld_platform_version_iOS_8_6 ({ (dyld_build_version_t){2, 0x00080600}; })
#define DYLD_IOS_VERSION_8_7 0x00080700
#define dyld_platform_version_iOS_8_7 ({ (dyld_build_version_t){2, 0x00080700}; })
#define DYLD_IOS_VERSION_9_0 0x00090000
#define dyld_platform_version_iOS_9_0 ({ (dyld_build_version_t){2, 0x00090000}; })
#define DYLD_IOS_VERSION_9_1 0x00090100
#define dyld_platform_version_iOS_9_1 ({ (dyld_build_version_t){2, 0x00090100}; })
#define DYLD_IOS_VERSION_9_2 0x00090200
#define dyld_platform_version_iOS_9_2 ({ (dyld_build_version_t){2, 0x00090200}; })
#define DYLD_IOS_VERSION_9_3 0x00090300
#define dyld_platform_version_iOS_9_3 ({ (dyld_build_version_t){2, 0x00090300}; })
#define DYLD_IOS_VERSION_9_4 0x00090400
#define dyld_platform_version_iOS_9_4 ({ (dyld_build_version_t){2, 0x00090400}; })
#define DYLD_IOS_VERSION_9_5 0x00090500
#define dyld_platform_version_iOS_9_5 ({ (dyld_build_version_t){2, 0x00090500}; })
#define DYLD_IOS_VERSION_9_6 0x00090600
#define dyld_platform_version_iOS_9_6 ({ (dyld_build_version_t){2, 0x00090600}; })
#define DYLD_IOS_VERSION_9_7 0x00090700
#define dyld_platform_version_iOS_9_7 ({ (dyld_build_version_t){2, 0x00090700}; })
#define DYLD_IOS_VERSION_10_0 0x000A0000
#define dyld_platform_version_iOS_10_0 ({ (dyld_build_version_t){2, 0x000A0000}; })
#define DYLD_IOS_VERSION_10_1 0x000A0100
#define dyld_platform_version_iOS_10_1 ({ (dyld_build_version_t){2, 0x000A0100}; })
#define DYLD_IOS_VERSION_10_2 0x000A0200
#define dyld_platform_version_iOS_10_2 ({ (dyld_build_version_t){2, 0x000A0200}; })
#define DYLD_IOS_VERSION_10_3 0x000A0300
#define dyld_platform_version_iOS_10_3 ({ (dyld_build_version_t){2, 0x000A0300}; })
#define DYLD_IOS_VERSION_10_4 0x000A0400
#define dyld_platform_version_iOS_10_4 ({ (dyld_build_version_t){2, 0x000A0400}; })
#define DYLD_IOS_VERSION_10_5 0x000A0500
#define dyld_platform_version_iOS_10_5 ({ (dyld_build_version_t){2, 0x000A0500}; })
#define DYLD_IOS_VERSION_10_6 0x000A0600
#define dyld_platform_version_iOS_10_6 ({ (dyld_build_version_t){2, 0x000A0600}; })
#define DYLD_IOS_VERSION_10_7 0x000A0700
#define dyld_platform_version_iOS_10_7 ({ (dyld_build_version_t){2, 0x000A0700}; })
#define DYLD_IOS_VERSION_11_0 0x000B0000
#define dyld_platform_version_iOS_11_0 ({ (dyld_build_version_t){2, 0x000B0000}; })
#define DYLD_IOS_VERSION_11_1 0x000B0100
#define dyld_platform_version_iOS_11_1 ({ (dyld_build_version_t){2, 0x000B0100}; })
#define DYLD_IOS_VERSION_11_2 0x000B0200
#define dyld_platform_version_iOS_11_2 ({ (dyld_build_version_t){2, 0x000B0200}; })
#define DYLD_IOS_VERSION_11_3 0x000B0300
#define dyld_platform_version_iOS_11_3 ({ (dyld_build_version_t){2, 0x000B0300}; })
#define DYLD_IOS_VERSION_11_4 0x000B0400
#define dyld_platform_version_iOS_11_4 ({ (dyld_build_version_t){2, 0x000B0400}; })
#define DYLD_IOS_VERSION_11_5 0x000B0500
#define dyld_platform_version_iOS_11_5 ({ (dyld_build_version_t){2, 0x000B0500}; })
#define DYLD_IOS_VERSION_11_6 0x000B0600
#define dyld_platform_version_iOS_11_6 ({ (dyld_build_version_t){2, 0x000B0600}; })
#define DYLD_IOS_VERSION_11_7 0x000B0700
#define dyld_platform_version_iOS_11_7 ({ (dyld_build_version_t){2, 0x000B0700}; })
#define DYLD_IOS_VERSION_12_0 0x000C0000
#define dyld_platform_version_iOS_12_0 ({ (dyld_build_version_t){2, 0x000C0000}; })
#define DYLD_IOS_VERSION_12_1 0x000C0100
#define dyld_platform_version_iOS_12_1 ({ (dyld_build_version_t){2, 0x000C0100}; })
#define DYLD_IOS_VERSION_12_2 0x000C0200
#define dyld_platform_version_iOS_12_2 ({ (dyld_build_version_t){2, 0x000C0200}; })
#define DYLD_IOS_VERSION_12_3 0x000C0300
#define dyld_platform_version_iOS_12_3 ({ (dyld_build_version_t){2, 0x000C0300}; })
#define DYLD_IOS_VERSION_12_4 0x000C0400
#define dyld_platform_version_iOS_12_4 ({ (dyld_build_version_t){2, 0x000C0400}; })
#define DYLD_IOS_VERSION_12_5 0x000C0500
#define dyld_platform_version_iOS_12_5 ({ (dyld_build_version_t){2, 0x000C0500}; })
#define DYLD_IOS_VERSION_12_6 0x000C0600
#define dyld_platform_version_iOS_12_6 ({ (dyld_build_version_t){2, 0x000C0600}; })
#define DYLD_IOS_VERSION_12_7 0x000C0700
#define dyld_platform_version_iOS_12_7 ({ (dyld_build_version_t){2, 0x000C0700}; })
#define DYLD_IOS_VERSION_13_0 0x000D0000
#define dyld_platform_version_iOS_13_0 ({ (dyld_build_version_t){2, 0x000D0000}; })
#define DYLD_IOS_VERSION_13_1 0x000D0100
#define dyld_platform_version_iOS_13_1 ({ (dyld_build_version_t){2, 0x000D0100}; })
#define DYLD_IOS_VERSION_13_2 0x000D0200
#define dyld_platform_version_iOS_13_2 ({ (dyld_build_version_t){2, 0x000D0200}; })
#define DYLD_IOS_VERSION_13_3 0x000D0300
#define dyld_platform_version_iOS_13_3 ({ (dyld_build_version_t){2, 0x000D0300}; })
#define DYLD_IOS_VERSION_13_4 0x000D0400
#define dyld_platform_version_iOS_13_4 ({ (dyld_build_version_t){2, 0x000D0400}; })
#define DYLD_IOS_VERSION_13_5 0x000D0500
#define dyld_platform_version_iOS_13_5 ({ (dyld_build_version_t){2, 0x000D0500}; })
#define DYLD_IOS_VERSION_13_6 0x000D0600
#define dyld_platform_version_iOS_13_6 ({ (dyld_build_version_t){2, 0x000D0600}; })
#define DYLD_IOS_VERSION_13_7 0x000D0700
#define dyld_platform_version_iOS_13_7 ({ (dyld_build_version_t){2, 0x000D0700}; })
#define DYLD_IOS_VERSION_14_0 0x000E0000
#define dyld_platform_version_iOS_14_0 ({ (dyld_build_version_t){2, 0x000E0000}; })
#define DYLD_IOS_VERSION_14_1 0x000E0100
#define dyld_platform_version_iOS_14_1 ({ (dyld_build_version_t){2, 0x000E0100}; })
#define DYLD_IOS_VERSION_14_2 0x000E0200
#define dyld_platform_version_iOS_14_2 ({ (dyld_build_version_t){2, 0x000E0200}; })
#define DYLD_IOS_VERSION_14_3 0x000E0300
#define dyld_platform_version_iOS_14_3 ({ (dyld_build_version_t){2, 0x000E0300}; })
#define DYLD_IOS_VERSION_14_4 0x000E0400
#define dyld_platform_version_iOS_14_4 ({ (dyld_build_version_t){2, 0x000E0400}; })
#define DYLD_IOS_VERSION_14_5 0x000E0500
#define dyld_platform_version_iOS_14_5 ({ (dyld_build_version_t){2, 0x000E0500}; })
#define DYLD_IOS_VERSION_14_6 0x000E0600
#define dyld_platform_version_iOS_14_6 ({ (dyld_build_version_t){2, 0x000E0600}; })
#define DYLD_IOS_VERSION_14_7 0x000E0700
#define dyld_platform_version_iOS_14_7 ({ (dyld_build_version_t){2, 0x000E0700}; })
#define DYLD_IOS_VERSION_15_0 0x000F0000
#define dyld_platform_version_iOS_15_0 ({ (dyld_build_version_t){2, 0x000F0000}; })
#define DYLD_IOS_VERSION_15_1 0x000F0100
#define dyld_platform_version_iOS_15_1 ({ (dyld_build_version_t){2, 0x000F0100}; })
#define DYLD_IOS_VERSION_15_2 0x000F0200
#define dyld_platform_version_iOS_15_2 ({ (dyld_build_version_t){2, 0x000F0200}; })
#define DYLD_IOS_VERSION_15_3 0x000F0300
#define dyld_platform_version_iOS_15_3 ({ (dyld_build_version_t){2, 0x000F0300}; })
#define DYLD_IOS_VERSION_15_4 0x000F0400
#define dyld_platform_version_iOS_15_4 ({ (dyld_build_version_t){2, 0x000F0400}; })
#define DYLD_IOS_VERSION_15_5 0x000F0500
#define dyld_platform_version_iOS_15_5 ({ (dyld_build_version_t){2, 0x000F0500}; })
#define DYLD_IOS_VERSION_15_6 0x000F0600
#define dyld_platform_version_iOS_15_6 ({ (dyld_build_version_t){2, 0x000F0600}; })
#define DYLD_IOS_VERSION_15_7 0x000F0700
#define dyld_platform_version_iOS_15_7 ({ (dyld_build_version_t){2, 0x000F0700}; })
#define DYLD_IOS_VERSION_16_0 0x00100000
#define dyld_platform_version_iOS_16_0 ({ (dyld_build_version_t){2, 0x00100000}; })
#define DYLD_IOS_VERSION_16_1 0x00100100
#define dyld_platform_version_iOS_16_1 ({ (dyld_build_version_t){2, 0x00100100}; })
#define DYLD_IOS_VERSION_16_2 0x00100200
#define dyld_platform_version_iOS_16_2 ({ (dyld_build_version_t){2, 0x00100200}; })
#define DYLD_IOS_VERSION_16_3 0x00100300
#define dyld_platform_version_iOS_16_3 ({ (dyld_build_version_t){2, 0x00100300}; })
#define DYLD_IOS_VERSION_16_4 0x00100400
#define dyld_platform_version_iOS_16_4 ({ (dyld_build_version_t){2, 0x00100400}; })
#define DYLD_IOS_VERSION_16_5 0x00100500
#define dyld_platform_version_iOS_16_5 ({ (dyld_build_version_t){2, 0x00100500}; })
#define DYLD_IOS_VERSION_16_6 0x00100600
#define dyld_platform_version_iOS_16_6 ({ (dyld_build_version_t){2, 0x00100600}; })
#define DYLD_IOS_VERSION_16_7 0x00100700
#define dyld_platform_version_iOS_16_7 ({ (dyld_build_version_t){2, 0x00100700}; })
#define DYLD_IOS_VERSION_17_0 0x00110000
#define dyld_platform_version_iOS_17_0 ({ (dyld_build_version_t){2, 0x00110000}; })
#define DYLD_IOS_VERSION_17_1 0x00110100
#define dyld_platform_version_iOS_17_1 ({ (dyld_build_version_t){2, 0x00110100}; })
#define DYLD_IOS_VERSION_17_2 0x00110200
#define dyld_platform_version_iOS_17_2 ({ (dyld_build_version_t){2, 0x00110200}; })
#define DYLD_IOS_VERSION_17_3 0x00110300
#define dyld_platform_version_iOS_17_3 ({ (dyld_build_version_t){2, 0x00110300}; })
#define DYLD_IOS_VERSION_17_4 0x00110400
#define dyld_platform_version_iOS_17_4 ({ (dyld_build_version_t){2, 0x00110400}; })
#define DYLD_IOS_VERSION_17_5 0x00110500
#define dyld_platform_version_iOS_17_5 ({ (dyld_build_version_t){2, 0x00110500}; })
#define DYLD_IOS_VERSION_17_6 0x00110600
#define dyld_platform_version_iOS_17_6 ({ (dyld_build_version_t){2, 0x00110600}; })
#define DYLD_IOS_VERSION_17_7 0x00110700
#define dyld_platform_version_iOS_17_7 ({ (dyld_build_version_t){2, 0x00110700}; })
#define DYLD_IOS_VERSION_18_0 0x00120000
#define dyld_platform_version_iOS_18_0 ({ (dyld_build_version_t){2, 0x00120000}; })
#define DYLD_IOS_VERSION_18_1 0x00120100
#define dyld_platform_version_iOS_18_1 ({ (dyld_build_version_t){2, 0x00120100}; })
#define DYLD_IOS_VERSION_18_2 0x00120200
#define dyld_platform_version_iOS_18_2 ({ (dyld_build_version_t){2, 0x00120200}; })
#define DYLD_IOS_VERSION_18_3 0x00120300
#define dyld_platform_version_iOS_18_3 ({ (dyld_build_version_t){2, 0x00120300}; })
#define DYLD_IOS_VERSION_18_4 0x00120400
#define dyld_platform_version_iOS_18_4 ({ (dyld_build_version_t){2, 0x00120400}; })
#define DYLD_IOS_VERSION_18_5 0x00120500
#define dyld_platform_version_iOS_18_5 ({ (dyld_build_version_t){2, 0x00120500}; })
#define DYLD_IOS_VERSION_18_6 0x00120600
#define dyld_platform_version_iOS_18_6 ({ (dyld_build_version_t){2, 0x00120600}; })
#define DYLD_IOS_VERSION_18_7 0x00120700
#define dyld_platform_version_iOS_18_7 ({ (dyld_build_version_t){2, 0x00120700}; })
#define DYLD_IOS_VERSION_26_0 0x001A0000
#define dyld_platform_version_iOS_26_0 ({ (dyld_build_version_t){2, 0x001A0000}; })
#define DYLD_IOS_VERSION_26_1 0x001A0100
#define dyld_platform_version_iOS_26_1 ({ (dyld_build_version_t){2, 0x001A0100}; })
#define DYLD_IOS_VERSION_26_2 0x001A0200
#define dyld_platform_version_iOS_26_2 ({ (dyld_build_version_t){2, 0x001A0200}; })
#define DYLD_IOS_VERSION_26_3 0x001A0300
#define dyld_platform_version_iOS_26_3 ({ (dyld_build_version_t){2, 0x001A0300}; })
#define DYLD_IOS_VERSION_26_4 0x001A0400
#define dyld_platform_version_iOS_26_4 ({ (dyld_build_version_t){2, 0x001A0400}; })
#define DYLD_IOS_VERSION_26_5 0x001A0500
#define dyld_platform_version_iOS_26_5 ({ (dyld_build_version_t){2, 0x001A0500}; })
#define DYLD_IOS_VERSION_26_6 0x001A0600
#define dyld_platform_version_iOS_26_6 ({ (dyld_build_version_t){2, 0x001A0600}; })
#define DYLD_IOS_VERSION_26_7 0x001A0700
#define dyld_platform_version_iOS_26_7 ({ (dyld_build_version_t){2, 0x001A0700}; })

#endif /* _FINCH_DYLD_VERSIONS_H_ */
