#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Generate Finch/SwiftUI/AccessibilityModifiers.swift: the accessibility modifier families
(each property's overloads for Text, LocalizedStringKey and strings, with and without
isEnabled, on any view and chained on the accessibility modifier), to Apple's interface.
    userland/SwiftUI/gen-accessibility.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'Finch', 'SwiftUI', 'AccessibilityModifiers.swift')

HEADER = '''// SPDX-License-Identifier: MIT OR Apache-2.0
//
// The accessibility modifiers, to Apple's interface: each sets a property of the view's
// accessibility element (its label, value, hint, identifier, traits, visibility, heading
// level, sort priority), on any view or chained on another of these modifiers. Upstream has
// the accessibility tree and its properties, not these.
//
// Generated by userland/SwiftUI/gen-accessibility.py; edit that, not this.

import Foundation
import SwiftUICore
'''

# (property, Text parameter, LocalizedStringKey parameter, string parameter, key, value from `t`)
TEXT_PROPERTIES = [
    ('Label', 'label', 'labelKey', 'label', 'LabelKey', 'AccessibilityLabelStorage(texts: [t])'),
    ('Value', 'valueDescription', 'valueKey', 'value', 'ValueKey', 'AccessibilityValueStorage(description: t)'),
    ('Hint', 'hint', 'hintKey', 'hint', 'HintsKey', '[t]'),
]

HIDDEN = 'hidden ? AccessibilityVisibilityStorage(adding: .hidden) : AccessibilityVisibilityStorage(removing: .hidden)'
# (function, parameter, key, value, has isEnabled variants)
SIMPLE_PROPERTIES = [
    ('accessibilityIdentifier', '_ identifier: String', 'IdentifierKey', 'AccessibilityIdentifierStorage(identifier)', True),
    ('accessibilityHidden', '_ hidden: Bool', 'VisibilityKey', HIDDEN, True),
    ('accessibilityAddTraits', '_ traits: AccessibilityTraits', 'TraitsKey', 'AccessibilityTraitStorage(adding: traits)', False),
    ('accessibilityRemoveTraits', '_ traits: AccessibilityTraits', 'TraitsKey', 'AccessibilityTraitStorage(removing: traits)', False),
    ('accessibilitySortPriority', '_ sortPriority: Double', 'SortPriorityKey', 'sortPriority', False),
    ('accessibilityHeading', '_ level: AccessibilityHeadingLevel', 'TextHeadingLevelKey', 'level', False),
    # the deprecated forms
    ('accessibility', 'label: Text', 'LabelKey', 'AccessibilityLabelStorage(texts: [label])', False),
    ('accessibility', 'value: Text', 'ValueKey', 'AccessibilityValueStorage(description: value)', False),
    ('accessibility', 'hint: Text', 'HintsKey', '[hint]', False),
    ('accessibility', 'hidden: Bool', 'VisibilityKey', HIDDEN, False),
    ('accessibility', 'identifier: String', 'IdentifierKey', 'AccessibilityIdentifierStorage(identifier)', False),
    ('accessibility', 'sortPriority: Double', 'SortPriorityKey', 'sortPriority', False),
]


def both(view_body, chained_body):
    return f'''
@available(OpenSwiftUI_v1_0, *)
extension View {{{view_body}}}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {{{chained_body}}}'''


def main():
    out = [HEADER]
    for name, tparam, kparam, sparam, key, expr in TEXT_PROPERTIES:
        key = f'AccessibilityProperties.{key}'
        for enabled in (True, False):
            sig = ', isEnabled: Bool' if enabled else ''
            arg = 'isEnabled' if enabled else 'true'
            members = []
            for ret, call in (('ModifiedContent<Self, AccessibilityAttachmentModifier>', 'accessibility({key}.self, {expr}, isEnabled: {arg})'),
                              ('ModifiedContent<Content, Modifier>', 'update({key}.self, replacing: {expr}, isEnabled: {arg})')):
                call = call.format(key=key, expr=expr, arg=arg)
                members.append(f'''
    nonisolated public func accessibility{name}(_ {tparam}: Text{sig}) -> {ret} {{
        let t = {tparam}
        return {call}
    }}

    nonisolated public func accessibility{name}(_ {kparam}: LocalizedStringKey{sig}) -> {ret} {{
        let t = Text({kparam})
        return {call}
    }}

    @_disfavoredOverload
    nonisolated public func accessibility{name}<S>(_ {sparam}: S{sig}) -> {ret} where S: StringProtocol {{
        let t = Text({sparam})
        return {call}
    }}
''')
            out.append(both(*members))
    for fn, param, key, expr, enabled_too in SIMPLE_PROPERTIES:
        key = f'AccessibilityProperties.{key}'
        for enabled in ((True, False) if enabled_too else (False,)):
            sig = ', isEnabled: Bool' if enabled else ''
            arg = 'isEnabled' if enabled else 'true'
            out.append(both(f'''
    nonisolated public func {fn}({param}{sig}) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {{
        accessibility({key}.self, {expr}, isEnabled: {arg})
    }}
''', f'''
    nonisolated public func {fn}({param}{sig}) -> ModifiedContent<Content, Modifier> {{
        update({key}.self, replacing: {expr}, isEnabled: {arg})
    }}
'''))
    out.append('''
@available(OpenSwiftUI_v1_0, *)
extension View {
    /// The view as one accessibility element, its children ignored, contained or combined.
    nonisolated public func accessibilityElement(children: AccessibilityChildBehavior = .ignore) -> some View {
        modifier(AccessibilityAttachmentModifier(storage: MutableBox(AccessibilityAttachment()), behavior: children))
    }
}
''')
    with open(OUT, 'w') as f:
        f.write('\n'.join(out))


main()
