#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Write the simd overlay's elementwise math functions (Finch).

    gen-simd-math.py > SIMDMath.swift

Apple's simd overlay gained Swift spellings of <simd/math.h>'s overloaded
C functions (__tg_sin and friends) after Swift's historical overlay was
frozen: transcendental and classification functions over the Float and
Double vectors (macOS 12; sincos and sincospi macOS 14), and rounding,
abs, sqrt, min and max over the Float16 vectors. Each forwards to the C
overload of the same name.
"""
FLOAT = ['simd_float2', 'simd_float3', 'simd_float4', 'simd_float8', 'simd_float16']
DOUBLE = ['simd_double2', 'simd_double3', 'simd_double4', 'simd_double8']
HALF = ['simd_half2', 'simd_half3', 'simd_half4', 'simd_half8', 'simd_half16', 'simd_half32']
UNARY = ['cos', 'cosh', 'cospi', 'acos', 'acosh', 'sin', 'sinh', 'sinpi', 'asin', 'asinh',
         'tan', 'tanh', 'tanpi', 'atan', 'atanh', 'exp', 'exp2', 'exp10', 'expm1', 'log',
         'log2', 'log10', 'log1p', 'cbrt', 'erf', 'erfc', 'tgamma', 'lgamma', 'round']
# Classification answers with a same-width integer vector (-1 for true).
CLASSIFY = ['isfinite', 'isinf', 'isnan', 'isnormal']
BINARY = ['atan2', 'hypot', 'pow', 'fmod', 'remainder', 'nextafter']
HALF_UNARY = {'abs': 'fabs', 'ceil': 'ceil', 'floor': 'floor', 'rint': 'rint',
              'sqrt': 'sqrt', 'trunc': 'trunc'}
AVAIL12 = '@available(macOS 12.0, iOS 15.0, tvOS 15.0, watchOS 8.0, *)'
AVAIL14 = '@available(macOS 14.0, iOS 17.0, tvOS 17.0, watchOS 10.0, *)'

out = ['// SPDX-License-Identifier: MIT OR Apache-2.0',
       '// Generated by userland/swift/overlays/simd/gen-simd-math.py; do not edit.',
       '']
for t in DOUBLE + FLOAT:
    for f in ('sincos', 'sincospi'):
        out += [AVAIL14,
                f'@_transparent public func {f}(_ x: {t}) -> (sin: {t}, cos: {t}) {{',
                f'  var sinResult = {t}()',
                f'  var cosResult = {t}()',
                f'  __tg_{f}(x, &sinResult, &cosResult)',
                '  return (sinResult, cosResult)',
                '}']
    for f in UNARY:
        out += [AVAIL12, f'@_transparent public func {f}(_ x: {t}) -> {t} {{',
                f'  return __tg_{f}(x)', '}']
    mask = t.replace('double', 'long').replace('float', 'int')
    for f in CLASSIFY:
        out += [AVAIL12, f'@_transparent public func {f}(_ x: {t}) -> {mask} {{',
                f'  return __tg_{f}(x)', '}']
    for f in BINARY:
        out += [AVAIL12, f'@_transparent public func {f}(_ x: {t}, _ y: {t}) -> {t} {{',
                f'  return __tg_{f}(x, y)', '}']
    out += [AVAIL12, f'@_transparent public func fma(_ x: {t}, _ y: {t}, _ z: {t}) -> {t} {{',
            '  return __tg_fma(x, y, z)', '}']
for t in HALF:
    for f, c in HALF_UNARY.items():
        out += [f'@_transparent public func {f}(_ x: {t}) -> {t} {{', f'  return __tg_{c}(x)', '}']
    for f in ('min', 'max'):
        out += [f'@_transparent public func {f}(_ x: {t}, _ y: {t}) -> {t} {{',
                f'  return __tg_f{f}(x, y)', '}',
                f'@_transparent public func {f}(_ vector: {t}, _ scalar: Float16) -> {t} {{',
                f'  return __tg_f{f}(vector, {t}(repeating: scalar))', '}']
print('\n'.join(out))
