#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Write Finch/Merge.swift and Finch/CombineLatest.swift: the Merge and CombineLatest
publishers OpenCombine doesn't have, declared as Apple's Combine declares them (its
public swiftinterface), so the symbols apps import match. The work is done by
_FinchFanIn (Finch/FanIn.swift).
    userland/Combine/gen.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
L = 'ABCDEFGH'
Z = 'ZYXWVU'
HEAD = '// SPDX-License-Identifier: MIT OR Apache-2.0\n// Generated by userland/Combine/gen.py: do not edit.\n\n'


def merge():
    out = [HEAD]
    # Publisher.merge(with:...) for 2..8
    out.append('extension Publisher {')
    out.append('    public func merge<P>(with other: P) -> Publishers.Merge<Self, P> where P: Publisher, Self.Failure == P.Failure, Self.Output == P.Output {\n        return Publishers.Merge(self, other)\n    }')
    for n in range(3, 9):
        ps = list(L[1:n])
        gens = ', '.join(ps)
        params = ', '.join(f'{"with " if i == 0 else "_ "}{p.lower()}: {p}' for i, p in enumerate(ps))
        cons = [f'{p}: Publisher' for p in ps] + ['Self.Failure == B.Failure', 'Self.Output == B.Output']
        for a, b in zip(ps, ps[1:]):
            cons += [f'{a}.Failure == {b}.Failure', f'{a}.Output == {b}.Output']
        args = ', '.join(['self'] + [p.lower() for p in ps])
        out.append(f'    public func merge<{gens}>({params}) -> Publishers.Merge{n}<Self, {gens}> where {", ".join(cons)} {{\n        return Publishers.Merge{n}({args})\n    }}')
    out.append('    public func merge(with other: Self) -> Publishers.MergeMany<Self> {\n        return Publishers.MergeMany(self, other)\n    }')
    out.append('}\n')
    out.append('extension Publishers {')
    for n in range(2, 9):
        ps = list(L[:n])
        name = 'Merge' if n == 2 else f'Merge{n}'
        cons = [f'{p}: Publisher' for p in ps]
        for a, b in zip(ps, ps[1:]):
            cons += [f'{a}.Failure == {b}.Failure', f'{a}.Output == {b}.Output']
        last = ps[-1]
        out.append(f'    public struct {name}<{", ".join(ps)}>: Publisher where {", ".join(cons)} {{')
        out.append('        public typealias Output = A.Output\n        public typealias Failure = A.Failure')
        for p in ps:
            out.append(f'        public let {p.lower()}: {p}')
        out.append(f'        public init({", ".join(f"_ {p.lower()}: {p}" for p in ps)}) {{')
        for p in ps:
            out.append(f'            self.{p.lower()} = {p.lower()}')
        out.append('        }')
        out.append(f'        public func receive<S>(subscriber: S) where S: Subscriber, {last}.Failure == S.Failure, {last}.Output == S.Input {{')
        out.append(f'            let fan = _FinchFanIn<Output, Failure>("{name}", count: {n}, downstream: AnySubscriber(subscriber), make: nil)')
        out.append('            subscriber.receive(subscription: fan)')
        for i, p in enumerate(ps):
            out.append(f'            {p.lower()}.subscribe(fan.side({i}, {p}.Output.self))')
        out.append('        }')
        # further merge(with:) up to 8
        for k in range(1, 9 - n):
            zs = list(Z[:k])
            if k == 1:
                gens, params = 'P', 'with other: P'
                cons2 = [f'P: Publisher', f'{last}.Failure == P.Failure', f'{last}.Output == P.Output']
                newargs = 'other'
                tps = ['P']
            else:
                gens = ', '.join(zs)
                params = ', '.join(f'{"with " if i == 0 else "_ "}{z.lower()}: {z}' for i, z in enumerate(zs))
                cons2 = [f'{z}: Publisher' for z in zs] + [f'{last}.Failure == Z.Failure', f'{last}.Output == Z.Output']
                for a, b in zip(zs, zs[1:]):
                    cons2 += [f'{a}.Failure == {b}.Failure', f'{a}.Output == {b}.Output']
                newargs = ', '.join(z.lower() for z in zs)
                tps = zs
            m = n + k
            out.append(f'        public func merge<{gens}>({params}) -> Publishers.Merge{m}<{", ".join(ps + tps)}> where {", ".join(cons2)} {{')
            out.append(f'            return Publishers.Merge{m}({", ".join(p.lower() for p in ps)}, {newargs})')
            out.append('        }')
        out.append('    }')
    out.append('''    public struct MergeMany<Upstream>: Publisher where Upstream: Publisher {
        public typealias Output = Upstream.Output
        public typealias Failure = Upstream.Failure
        public let publishers: [Upstream]
        public init(_ upstream: Upstream...) {
            publishers = upstream
        }
        public init<S>(_ upstream: S) where Upstream == S.Element, S: Swift.Sequence {
            publishers = Array(upstream)
        }
        public func receive<S>(subscriber: S) where S: Subscriber, Upstream.Failure == S.Failure, Upstream.Output == S.Input {
            let fan = _FinchFanIn<Output, Failure>("MergeMany", count: publishers.count, downstream: AnySubscriber(subscriber), make: nil)
            subscriber.receive(subscription: fan)
            for (i, p) in publishers.enumerated() {
                p.subscribe(fan.side(i, Upstream.Output.self))
            }
        }
        public func merge(with other: Upstream) -> MergeMany<Upstream> {
            return MergeMany(publishers + [other])
        }
    }''')
    out.append('}\n')
    for n in range(2, 9):
        ps = list(L[:n])
        name = 'Merge' if n == 2 else f'Merge{n}'
        out.append(f'extension Publishers.{name}: Equatable where {", ".join(f"{p}: Equatable" for p in ps)} {{')
        out.append(f'    public static func == (lhs: Publishers.{name}<{", ".join(ps)}>, rhs: Publishers.{name}<{", ".join(ps)}>) -> Bool {{')
        out.append('        return ' + ' && '.join(f'lhs.{p.lower()} == rhs.{p.lower()}' for p in ps))
        out.append('    }\n}\n')
    out.append('extension Publishers.MergeMany: Equatable where Upstream: Equatable {\n    public static func == (lhs: Publishers.MergeMany<Upstream>, rhs: Publishers.MergeMany<Upstream>) -> Bool {\n        return lhs.publishers == rhs.publishers\n    }\n}\n')
    return '\n'.join(out)


def combine_latest():
    out = [HEAD, 'extension Publisher {']
    for n in range(2, 5):
        ps = list('PQR')[:n - 1]
        gens = ', '.join(ps)
        if n == 2:
            params = 'other: P'
            plist = ['other']
        else:
            params = ', '.join(f'_ publisher{i + 1}: {p}' for i, p in enumerate(ps))
            plist = [f'publisher{i + 1}' for i in range(len(ps))]
        cons = [f'{p}: Publisher' for p in ps] + [f'Self.Failure == {ps[0]}.Failure']
        for a, b in zip(ps, ps[1:]):
            cons.append(f'{a}.Failure == {b}.Failure')
        name = 'CombineLatest' if n == 2 else f'CombineLatest{n}'
        first = '_ ' + params if n == 2 else params
        out.append(f'    public func combineLatest<{gens}>({first}) -> Publishers.{name}<Self, {gens}> where {", ".join(cons)} {{\n        return Publishers.{name}(self, {", ".join(plist)})\n    }}')
        outs = ', '.join(['Self.Output'] + [f'{p}.Output' for p in ps])
        out.append(f'    public func combineLatest<{gens}, T>({first}, _ transform: @escaping ({outs}) -> T) -> Publishers.Map<Publishers.{name}<Self, {gens}>, T> where {", ".join(cons)} {{\n        return Publishers.{name}(self, {", ".join(plist)}).map(transform)\n    }}')
    out.append('}\n')
    out.append('extension Publishers {')
    for n in range(2, 5):
        ps = list(L[:n])
        name = 'CombineLatest' if n == 2 else f'CombineLatest{n}'
        cons = [f'{p}: Publisher' for p in ps] + [f'{a}.Failure == {b}.Failure' for a, b in zip(ps, ps[1:])]
        last = ps[-1]
        tup = '(' + ', '.join(f'{p}.Output' for p in ps) + ')'
        out.append(f'    public struct {name}<{", ".join(ps)}>: Publisher where {", ".join(cons)} {{')
        out.append(f'        public typealias Output = {tup}\n        public typealias Failure = A.Failure')
        for p in ps:
            out.append(f'        public let {p.lower()}: {p}')
        out.append(f'        public init({", ".join(f"_ {p.lower()}: {p}" for p in ps)}) {{')
        for p in ps:
            out.append(f'            self.{p.lower()} = {p.lower()}')
        out.append('        }')
        out.append(f'        public func receive<S>(subscriber: S) where S: Subscriber, {last}.Failure == S.Failure, S.Input == {tup} {{')
        make = '(' + ', '.join(f'v[{i}] as! {p}.Output' for i, p in enumerate(ps)) + ')'
        out.append(f'            let fan = _FinchFanIn<Output, Failure>("{name}", count: {n}, downstream: AnySubscriber(subscriber), make: {{ v in {make} }})')
        out.append('            subscriber.receive(subscription: fan)')
        for i, p in enumerate(ps):
            out.append(f'            {p.lower()}.subscribe(fan.side({i}, {p}.Output.self))')
        out.append('        }')
        out.append('    }')
    out.append('}\n')
    for n in range(2, 5):
        ps = list(L[:n])
        name = 'CombineLatest' if n == 2 else f'CombineLatest{n}'
        out.append(f'extension Publishers.{name}: Equatable where {", ".join(f"{p}: Equatable" for p in ps)} {{')
        out.append(f'    public static func == (lhs: Publishers.{name}<{", ".join(ps)}>, rhs: Publishers.{name}<{", ".join(ps)}>) -> Bool {{')
        out.append('        return ' + ' && '.join(f'lhs.{p.lower()} == rhs.{p.lower()}' for p in ps))
        out.append('    }\n}\n')
    return '\n'.join(out)


open(os.path.join(HERE, 'Finch', 'Merge.swift'), 'w').write(merge())
open(os.path.join(HERE, 'Finch', 'CombineLatest.swift'), 'w').write(combine_latest())
