# SPDX-License-Identifier: MIT OR Apache-2.0
NAME        := libEndpointSecuritySystem
VERSION     := 589.100.28
SRCS        := ess.c
INSTALL_DIR := /usr/lib
UMBRELLA    :=
LIBS        := -lsystem_kernel -lsystem_platform -lsystem_c -lsystem_trace -ldispatch -lsystem_blocks
include ../lib.mk
