/* SPDX-License-Identifier: MIT OR Apache-2.0 */
#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
struct api{size_t(*cs)(void*),(*ss)(void*);int(*ci)(void*,void*,void*,size_t,const void*),(*si)(void*,void*,void*,size_t,const void*);int(*encode)(void*,void*,size_t,const void*);int(*match)(void*,void*,void*);int(*check)(void*,void*,void*,size_t,const void*,void*);int(*det)(void*,bool*,void*,void*);};
static int tests;
#define CHECK(x) do{tests++;if(!(x)){fprintf(stderr,"line%d %s\n",__LINE__,#x);exit(1);}}while(0)
static void load(void*h,struct api*a){a->cs=dlsym(h,"ccapsic_client_state_sizeof");a->ss=dlsym(h,"ccapsic_server_state_sizeof");a->ci=dlsym(h,"ccapsic_client_init");a->si=dlsym(h,"ccapsic_server_init");a->encode=dlsym(h,"ccapsic_server_encode_element");a->match=dlsym(h,"ccapsic_client_generate_match_response");a->check=dlsym(h,"ccapsic_client_check_intersect_response");a->det=dlsym(h,"ccapsic_server_determine_intersection");}
int main(int argc,char**argv){void*h=dlopen("/usr/lib/system/libcorecrypto.dylib",2),*f=dlopen(argc>1?argv[1]:"/tmp/ecc-apsic-test.dylib",2);CHECK(h&&f);struct api a[2];load(h,a);load(f,a+1);void*(*rng)(int*)=dlsym(h,"ccrng");int(*gen)(void*,void*,void*)=dlsym(h,"ccec_generate_key");int bs[]={256,384,521};for(int curve=0;curve<3;curve++){char name[40];snprintf(name,sizeof name,"ccec_cp_%d",bs[curve]);void*(*cpf)(void)=dlsym(h,name);void*cp=cpf();unsigned char key[400];CHECK(gen(cp,rng(NULL),key)==0);CHECK(a[0].cs(key)==a[1].cs(key));CHECK(a[0].ss(key)==a[1].ss(key));for(int init=0;init<2;init++)for(int client=0;client<2;client++)for(int server=0;server<2;server++){unsigned char c[1300]={0},s[1300]={0},encoded[400]={0},e0[400]={0},x[400]={0},y[400]={0};*(void**)encoded=cp;*(void**)e0=cp;*(void**)x=cp;*(void**)y=cp;CHECK(a[init].ci(c,key,rng(NULL),4,"test")==0);CHECK(a[init].si(s,key,rng(NULL),4,"test")==0);CHECK(a[0].encode(s,e0,5,"hello")==0);CHECK(a[1].encode(s,encoded,5,"hello")==0);CHECK(!memcmp(e0+16,encoded+16,3*((bs[curve]+63)/64)*8));for(int match=0;match<2;match++){int rc=a[client].check(c,x,y,5,match?"hello":"other",encoded);if(rc)fprintf(stderr,"curve%d init%d c%d s%d match%d rc%d cp %p %p %p\n",curve,init,client,server,match,rc,*(void**)x,*(void**)y,*(void**)encoded);CHECK(rc==0);bool result=true;CHECK(a[server].det(s,&result,x,y)==0);CHECK(result==(bool)match);}CHECK(a[client].match(c,x,y)==0);bool result=false;CHECK(a[server].det(s,&result,x,y)==0);CHECK(result);}}printf("APSIC: %d checks passed\n",tests);}
