/* SPDX-License-Identifier: MIT OR Apache-2.0 */
#include "../abi/ccsigma.h"
#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define FN(N) __typeof__(&N) h_##N=dlsym(h,#N),f_##N=dlsym(f,#N)
static int checks,failures;
#define CHECK(X) do{checks++;if(!(X)){fprintf(stderr,"FAIL line %d: %s\n",__LINE__,#X);failures++;}}while(0)
struct rng{struct ccrng_state r;unsigned seed;};
static int random_bytes(struct ccrng_state*r,size_t n,void*out){unsigned seed=((struct rng*)r)->seed;for(size_t i=0;i<n;i++)((unsigned char*)out)[i]=seed+i*13;return 0;}
int main(int argc,char**argv){setbuf(stdout,NULL);void*h=dlopen("/usr/lib/system/libcorecrypto.dylib",RTLD_NOW|RTLD_LOCAL),*f=dlopen(argc>1?argv[1]:"build/userland/corecrypto/sigma-test.dylib",RTLD_NOW|RTLD_LOCAL);if(!h||!f){fprintf(stderr,"%s\n",dlerror());return 2;}
FN(ccsigma_init);FN(ccsigma_set_signing_function);FN(ccsigma_import_signing_key);FN(ccsigma_import_peer_verification_key);FN(ccsigma_export_key_share);FN(ccsigma_import_peer_key_share);FN(ccsigma_peer_role);FN(ccsigma_kex_init_ctx);FN(ccsigma_kex_resp_ctx);FN(ccsigma_derive_session_keys);FN(ccsigma_compute_mac);FN(ccsigma_sign);FN(ccsigma_verify);FN(ccsigma_seal);FN(ccsigma_open);FN(ccsigma_clear_key);FN(ccsigma_clear);FN(ccsigma_session_init);FN(ccsigma_session_seal);FN(ccsigma_session_open);FN(ccsigma_session_export);FN(ccsigma_session_import);FN(ccsigma_session_clear);FN(ccsigma_exclave_pairing_session_info);
(void)h_ccsigma_set_signing_function;(void)f_ccsigma_set_signing_function;
const char*names[]={"ccsigma_mfi_info","ccsigma_mfi_nvm_info","ccsigma_exclave_pairing_info"};
for(unsigned cross=0;cross<2;cross++)for(unsigned which=0;which<3;which++){const struct ccsigma_info*i=((const struct ccsigma_info*(*)(void))dlsym(cross?f:h,names[which]))();struct ccsigma_ctx*a=calloc(1,1024),*b=calloc(1,1024),*peer=calloc(1,1024);struct rng ra={{random_bytes},7},rb={{random_bytes},7},rp={{random_bytes},55};int x=h_ccsigma_init(i,a,0,&ra.r),y=f_ccsigma_init(i,b,0,&rb.r);CHECK(x==y);CHECK(!x);CHECK(!h_ccsigma_init(i,peer,1,&rp.r));CHECK(h_ccsigma_peer_role(a)==f_ccsigma_peer_role(b));CHECK((char*)h_ccsigma_kex_init_ctx(a)-(char*)a==(char*)f_ccsigma_kex_init_ctx(b)-(char*)b);CHECK((char*)h_ccsigma_kex_resp_ctx(a)-(char*)a==(char*)f_ccsigma_kex_resp_ctx(b)-(char*)b);unsigned char ka[140],kb[140],kp[140];size_t na=sizeof ka,nb=sizeof kb,np=sizeof kp;CHECK(!h_ccsigma_export_key_share(a,&na,ka));CHECK(!f_ccsigma_export_key_share(b,&nb,kb));CHECK(na==nb);CHECK(!memcmp(ka,kb,na));CHECK(!h_ccsigma_export_key_share(peer,&np,kp));CHECK(!h_ccsigma_import_peer_key_share(a,np,kp));CHECK(!f_ccsigma_import_peer_key_share(b,np,kp));CHECK(!h_ccsigma_import_peer_key_share(peer,nb,kb));CHECK(!h_ccsigma_derive_session_keys(a,4,"test",&ra.r));CHECK(!f_ccsigma_derive_session_keys(b,4,"test",&rb.r));CHECK(!h_ccsigma_derive_session_keys(peer,4,"test",&rp.r));CHECK(!memcmp(i->keys(a),i->keys(b),i->keys_size));CHECK(!memcmp(i->keys(a),i->keys(peer),i->keys_size));for(size_t k=0;k<i->key_count+1;k++){unsigned char ma[64]={0},mb[64]={0};x=h_ccsigma_compute_mac(a,k,9,"test data",ma);y=f_ccsigma_compute_mac(b,k,9,"test data",mb);CHECK(x==y);CHECK(!memcmp(ma,mb,sizeof ma));}
int(*keygen)(ccec_const_cp_t,struct ccrng_state*,struct ccec_ctx*)=dlsym(h,"ccec_generate_key_fips");void(*export_key)(int,void*,const struct ccec_ctx*)=dlsym(h,"ccec_x963_export");unsigned char keyctx[200],priv[97],pub[65],sig[64],fsig[64];struct ccec_ctx*sk=(void*)keyctx;CHECK(!keygen(i->sign_cp,&rp.r,sk));export_key(1,priv,sk);export_key(0,pub,sk);CHECK(!h_ccsigma_import_signing_key(a,sizeof priv,priv));CHECK(!f_ccsigma_import_signing_key(b,sizeof priv,priv));CHECK(!h_ccsigma_import_peer_verification_key(peer,sizeof pub,pub));CHECK(!f_ccsigma_import_peer_verification_key(b,sizeof pub,pub));CHECK(!h_ccsigma_sign(a,sig,9,"test data",&ra.r));CHECK(!f_ccsigma_sign(b,fsig,9,"test data",&rb.r));CHECK(!memcmp(sig,fsig,64));CHECK(!h_ccsigma_verify(peer,fsig,9,"test data"));CHECK(!f_ccsigma_verify(peer,sig,9,"test data"));for(unsigned bad=0;bad<3;bad++){memcpy(fsig,sig,64);if(bad==0)fsig[2]^=1;else if(bad==1)memset(fsig,0,32);else memset(fsig,255,32);x=h_ccsigma_verify(peer,fsig,9,"test data");y=f_ccsigma_verify(peer,fsig,9,"test data");if(x!=y)printf("verify bad%u host%d finch%d\n",bad,x,y);CHECK(x==y);}
unsigned char ca[100]={0},cb[100]={0},tag[16],ftag[16],plain[100];for(unsigned len=0;len<40;len++){unsigned char msg[40];memset(msg,0x42,sizeof msg);struct ccsigma_ctx*sa=malloc(1024),*sb=malloc(1024),*pa=malloc(1024),*pb=malloc(1024);memcpy(sa,a,1024);memcpy(sb,b,1024);memcpy(pa,peer,1024);memcpy(pb,peer,1024);CHECK(h_ccsigma_seal(sa,0,1,len/2,msg,len,msg,ca,tag)==f_ccsigma_seal(sb,0,1,len/2,msg,len,msg,cb,ftag));CHECK(!memcmp(ca,cb,len));CHECK(!memcmp(tag,ftag,16));CHECK(!memcmp(i->keys(sa),i->keys(sb),i->keys_size));CHECK(h_ccsigma_open(pa,0,1,len/2,msg,len,ca,plain,tag)==f_ccsigma_open(pb,0,1,len/2,msg,len,cb,plain,ftag));CHECK(!memcmp(plain,msg,len));CHECK(!memcmp(i->keys(pa),i->keys(pb),i->keys_size));memcpy(pa,peer,1024);memcpy(pb,peer,1024);tag[len%16]^=1;ftag[len%16]^=1;memset(ca,0xcc,sizeof ca);memset(cb,0xcc,sizeof cb);CHECK(h_ccsigma_open(pa,0,1,len/2,msg,len,msg,ca,tag)==f_ccsigma_open(pb,0,1,len/2,msg,len,msg,cb,ftag));CHECK(!memcmp(ca,cb,100));CHECK(!memcmp(i->keys(pa),i->keys(pb),i->keys_size));free(sa);free(sb);free(pa);free(pb);}CHECK(!h_ccsigma_seal(a,0,1,3,"aad",9,"plaintext",ca,tag));CHECK(!f_ccsigma_seal(b,0,1,3,"aad",9,"plaintext",cb,ftag));CHECK(!memcmp(ca,cb,9));CHECK(!memcmp(tag,ftag,16));CHECK(!memcmp(i->keys(a),i->keys(b),i->keys_size));struct ccsigma_ctx*copy=malloc(1024);memcpy(copy,peer,1024);CHECK(!f_ccsigma_open(copy,0,1,3,"aad",9,cb,plain,ftag));CHECK(!h_ccsigma_open(peer,0,1,3,"aad",9,cb,plain,ftag));CHECK(!memcmp(copy,peer,1024));free(copy);CHECK(!memcmp(plain,"plaintext",9));
if(which==2){const struct ccsigma_session_info*si=cross?f_ccsigma_exclave_pairing_session_info():h_ccsigma_exclave_pairing_session_info();struct ccsigma_session_ctx at={0},ar={0},bt={0},br={0},pt={0},pr={0};CHECK(!h_ccsigma_session_init(a,10,3,"ctx",si,&at,&ar));CHECK(!f_ccsigma_session_init(b,10,3,"ctx",si,&bt,&br));CHECK(!h_ccsigma_session_init(peer,10,3,"ctx",si,&pt,&pr));CHECK(!memcmp(&at,&bt,sizeof at));CHECK(!memcmp(&ar,&br,sizeof ar));CHECK(!memcmp(at.key,pr.key,32));for(unsigned turn=0;turn<3;turn++){uint64_t qa=99,qb=99;CHECK(!h_ccsigma_session_seal(&at,3,"aad",9,"plaintext",ca,tag,&qa));CHECK(!f_ccsigma_session_seal(&bt,3,"aad",9,"plaintext",cb,ftag,&qb));CHECK(qa==qb);CHECK(!memcmp(ca,cb,9));CHECK(!memcmp(tag,ftag,16));CHECK(!memcmp(&at,&bt,sizeof at));struct ccsigma_session_ctx copy=pr;CHECK(!h_ccsigma_session_open(&copy,3,"aad",9,ca,plain,tag,qa));CHECK(!f_ccsigma_session_open(&pr,3,"aad",9,ca,plain,tag,qa));CHECK(!memcmp(&copy,&pr,sizeof copy));CHECK(!memcmp(plain,"plaintext",9));}for(unsigned bad=0;bad<5;bad++){struct ccsigma_session_ctx xa=pr,xb=pr;memset(ca,0xcc,100);memset(cb,0xcc,100);uint64_t seq=pr.sequence;if(bad==0)seq--;if(bad==1)seq=UINT64_MAX;if(bad==2)xa.direction=xb.direction=0;if(bad==3)seq+=10;if(bad==4)xa.sequence=xb.sequence=UINT64_MAX;CHECK(h_ccsigma_session_open(&xa,3,"aad",9,"wrongtext",ca,tag,seq)==f_ccsigma_session_open(&xb,3,"aad",9,"wrongtext",cb,tag,seq));CHECK(!memcmp(ca,cb,100));CHECK(!memcmp(&xa,&xb,sizeof xa));}for(unsigned bad=0;bad<3;bad++){struct ccsigma_session_ctx xa=at,xb=bt;if(bad==0)xa.sequence=xb.sequence=UINT64_MAX;if(bad==1)xa.direction=xb.direction=1;if(bad==2)xa.sequence=xb.sequence=UINT64_MAX-1;uint64_t qa=100,qb=100;memset(ca,0xcc,100);memset(cb,0xcc,100);memset(tag,0xcc,16);memset(ftag,0xcc,16);CHECK(h_ccsigma_session_seal(&xa,3,"aad",9,"plaintext",ca,tag,&qa)==f_ccsigma_session_seal(&xb,3,"aad",9,"plaintext",cb,ftag,&qb));CHECK(!memcmp(ca,cb,100));CHECK(!memcmp(tag,ftag,16));CHECK(qa==qb);CHECK(!memcmp(&xa,&xb,sizeof xa));}unsigned char ea[64],eb[64];memset(ea,0,sizeof ea);memset(eb,0,sizeof eb);CHECK(!h_ccsigma_session_export(&at,sizeof ea,ea));CHECK(!f_ccsigma_session_export(&bt,sizeof eb,eb));CHECK(!memcmp(ea,eb,sizeof ea));struct ccsigma_session_ctx ia={0},ib={0};CHECK(!h_ccsigma_session_import(si,&ia,sizeof ea,ea));CHECK(!f_ccsigma_session_import(si,&ib,sizeof eb,eb));CHECK(!memcmp(&ia,&ib,sizeof ia));h_ccsigma_session_clear(&ia);f_ccsigma_session_clear(&ib);CHECK(!memcmp(&ia,&ib,sizeof ia));}
for(size_t k=0;k<=i->key_count;k++){CHECK(h_ccsigma_clear_key(a,k)==f_ccsigma_clear_key(b,k));CHECK(!memcmp(i->keys(a),i->keys(b),i->keys_size));}h_ccsigma_clear(a);f_ccsigma_clear(b);CHECK(!memcmp(a,b,1024));free(a);free(b);free(peer);}
printf("SIGMA ABI: %d checks, %d failures\n",checks,failures);return failures?1:0;}
