/* SPDX-License-Identifier: MIT OR Apache-2.0 */
#include "../abi/ccvrf.h"
#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static int checks,failures;
#define CHECK(x) do{checks++;if(!(x)){if(failures++<20)fprintf(stderr,"line %d: %s\n",__LINE__,#x);}}while(0)
#define LOAD(name,type) type h_##name=(type)dlsym(h,#name),f_##name=(type)dlsym(f,#name);CHECK(h_##name&&f_##name)
typedef void(*factoryfn)(struct ccvrf_info*);
typedef void(*factorydifn)(struct ccvrf_info*,const struct ccdigest_info*);
typedef int(*pubfn)(const struct ccvrf_info*,size_t,const void*,size_t,void*);
typedef int(*provefn)(const struct ccvrf_info*,size_t,const void*,size_t,const void*,size_t,void*);
typedef int(*verifyfn)(const struct ccvrf_info*,size_t,const void*,size_t,const void*,size_t,const void*);
typedef const struct ccdigest_info*(*difn)(void);
int main(int argc,char**argv){void*h=dlopen("/usr/lib/system/libcorecrypto.dylib",RTLD_NOW|RTLD_LOCAL),*f=dlopen(argc>1?argv[1]:"build/userland/corecrypto/vrf-test.dylib",RTLD_NOW|RTLD_LOCAL);if(!h||!f){fprintf(stderr,"%s\n",dlerror());return 2;}LOAD(ccvrf_factory_irtfdraft03_default,factoryfn);LOAD(ccvrf_factory_irtfdraft03,factorydifn);LOAD(ccvrf_derive_public_key,pubfn);LOAD(ccvrf_prove,provefn);LOAD(ccvrf_verify,verifyfn);LOAD(ccvrf_proof_to_hash,pubfn);struct ccvrf_info hi,fi;h_ccvrf_factory_irtfdraft03_default(&hi);f_ccvrf_factory_irtfdraft03_default(&fi);CHECK(!memcmp(&hi,&fi,40));for(int origin=0;origin<2;origin++){const struct ccdigest_info*di=((difn)dlsym(origin?h:f,"ccsha512_di"))();h_ccvrf_factory_irtfdraft03(&hi,di);f_ccvrf_factory_irtfdraft03(&fi,di);for(int seed=0;seed<10;seed++){unsigned char sk[32],msg[1000],pa[32],pb[32],a[80],b[80],ha[64],hb[64];for(int j=0;j<32;j++)sk[j]=j*13+seed;for(int j=0;j<1000;j++)msg[j]=j*7+seed;size_t n=seed*97;CHECK(!h_ccvrf_derive_public_key(&hi,32,sk,32,pa));CHECK(!f_ccvrf_derive_public_key(&fi,32,sk,32,pb));CHECK(!memcmp(pa,pb,32));CHECK(!h_ccvrf_prove(&hi,32,sk,n,msg,80,a));CHECK(!f_ccvrf_prove(&fi,32,sk,n,msg,80,b));CHECK(!memcmp(a,b,80));if(memcmp(a,b,80)&&failures<5){for(int j=0;j<80;j++)fprintf(stderr,"%02x",a[j]);fprintf(stderr,"\n");for(int j=0;j<80;j++)fprintf(stderr,"%02x",b[j]);fprintf(stderr,"\n");}CHECK(!h_ccvrf_verify(&hi,32,pa,n,msg,80,b));CHECK(!f_ccvrf_verify(&fi,32,pb,n,msg,80,a));CHECK(!h_ccvrf_proof_to_hash(&hi,80,a,64,ha));CHECK(!f_ccvrf_proof_to_hash(&fi,80,a,64,hb));CHECK(!memcmp(ha,hb,64));for(int j=0;j<80;j++){unsigned char bad[80];memcpy(bad,a,80);bad[j]^=128;CHECK(h_ccvrf_verify(&hi,32,pa,n,msg,80,bad)==f_ccvrf_verify(&fi,32,pa,n,msg,80,bad));int hr=h_ccvrf_proof_to_hash(&hi,80,bad,64,ha),fr=f_ccvrf_proof_to_hash(&fi,80,bad,64,hb);CHECK(hr==fr);if(!hr)CHECK(!memcmp(ha,hb,64));}CHECK(h_ccvrf_prove(&hi,31,sk,n,msg,80,a)==f_ccvrf_prove(&fi,31,sk,n,msg,80,b));CHECK(h_ccvrf_verify(&hi,32,pa,n,msg,79,a)==f_ccvrf_verify(&fi,32,pa,n,msg,79,a));CHECK(h_ccvrf_proof_to_hash(&hi,80,a,63,ha)==f_ccvrf_proof_to_hash(&fi,80,a,63,hb));memset(pa,0,32);CHECK(h_ccvrf_verify(&hi,32,pa,n,msg,80,a)==f_ccvrf_verify(&fi,32,pa,n,msg,80,a));pa[0]=1;CHECK(h_ccvrf_verify(&hi,32,pa,n,msg,80,a)==f_ccvrf_verify(&fi,32,pa,n,msg,80,a));}}
/* Factories preserve the destination when a digest has the wrong width. */
const char*small[]={"ccsha256_di","ccsha384_di","ccsha1_di"};for(int j=0;j<3;j++){const struct ccdigest_info*di=((difn)dlsym(h,small[j]))();memset(&hi,0xa5,sizeof(hi));memset(&fi,0xa5,sizeof(fi));h_ccvrf_factory_irtfdraft03(&hi,di);f_ccvrf_factory_irtfdraft03(&fi,di);CHECK(!memcmp(&hi,&fi,sizeof(hi)));}
h_ccvrf_factory_irtfdraft03_default(&hi);f_ccvrf_factory_irtfdraft03_default(&fi);const char*sizes[]={"ccvrf_sizeof_public_key","ccvrf_sizeof_secret_key","ccvrf_sizeof_proof","ccvrf_sizeof_hash"};for(int j=0;j<4;j++){size_t(*hs)(const struct ccvrf_info*)=(void*)dlsym(h,sizes[j]);size_t(*fs)(const struct ccvrf_info*)=(void*)dlsym(f,sizes[j]);CHECK(hs(&hi)==fs(&fi));CHECK(hs(&fi)==fs(&hi));}
for(int origin=0;origin<2;origin++){const struct ccvrf_info*i=origin?&hi:&fi;unsigned char sk[32]={7},pk[32],pk2[32],p[80],p2[80],ha[64],hb[64];CHECK(h_ccvrf_derive_public_key(i,32,sk,32,pk)==f_ccvrf_derive_public_key(i,32,sk,32,pk2));CHECK(!memcmp(pk,pk2,32));CHECK(h_ccvrf_prove(i,32,sk,5,"hello",80,p)==f_ccvrf_prove(i,32,sk,5,"hello",80,p2));CHECK(!memcmp(p,p2,80));CHECK(h_ccvrf_verify(i,32,pk,5,"hello",80,p)==f_ccvrf_verify(i,32,pk,5,"hello",80,p));CHECK(h_ccvrf_proof_to_hash(i,80,p,64,ha)==f_ccvrf_proof_to_hash(i,80,p,64,hb));CHECK(!memcmp(ha,hb,64));
for(int j=0;j<256;j++){for(int k=0;k<32;k++)pk2[k]=(j*31+k*17)^(j>>(k%8));int hr=h_ccvrf_verify(&hi,32,pk2,5,"hello",80,p),fr=f_ccvrf_verify(&fi,32,pk2,5,"hello",80,p);CHECK(hr==fr);}for(int j=0;j<20;j++){memset(pk2,255,32);pk2[0]=237+j;pk2[31]=127;CHECK(h_ccvrf_verify(&hi,32,pk2,5,"hello",80,p)==f_ccvrf_verify(&fi,32,pk2,5,"hello",80,p));}
for(size_t j=0;j<100;j++){CHECK(h_ccvrf_derive_public_key(i,j,sk,32,pk)==f_ccvrf_derive_public_key(i,j,sk,32,pk2));CHECK(h_ccvrf_prove(i,32,sk,0,NULL,j,p)==f_ccvrf_prove(i,32,sk,0,NULL,j,p2));CHECK(h_ccvrf_proof_to_hash(i,80,p,j,ha)==f_ccvrf_proof_to_hash(i,80,p,j,hb));}}
printf("VRF ABI: %d checks, %d failures\n",checks,failures);return failures?1:0;}
