/* SPDX-License-Identifier: MIT OR Apache-2.0
 * Private set matching with randomized curve points. */
#include "cch2c.h"
#include <openssl/bn.h>
#include <openssl/ec.h>
#include <openssl/obj_mac.h>
#include <string.h>
#define EXPORT __attribute__((visibility("default")))
struct apsic{ccec_const_cp_t cp;struct ccrng_state*rng;const struct cch2c_info*h2c;size_t dst_n;unsigned char dst[160];cc_unit data[];};
static int apsic_encode(void*w,const struct cch2c_info*i,size_t dn,const void*dst,size_t n,const void*in,struct ccec_ctx*out){const struct apsic*s=(const void*)((const unsigned char*)dst-32);const struct cch2c_info*base=i->l==48?&cch2c_p256_sha256_sswu_ro_info:i->l==72?&cch2c_p384_sha512_sswu_ro_info:&cch2c_p521_sha512_sswu_ro_info;int rc=base->encode(w,base,dn,dst,n,in,out);if(!rc)out->cp=s->cp;return rc;}
static const struct cch2c_info apsic256={"P256-SHA256-SSWU-RO-",48,10,ccec_cp_256,ccsha256_di,NULL,NULL,NULL,apsic_encode};
static const struct cch2c_info apsic384={"P384-SHA512-SSWU-RO-",72,12,ccec_cp_384,ccsha512_di,NULL,NULL,NULL,apsic_encode};
static const struct cch2c_info apsic521={"P521-SHA512-SSWU-RO-",96,4,ccec_cp_521,ccsha512_di,NULL,NULL,NULL,apsic_encode};
extern int ccec_projectify(ccec_const_cp_t,cc_unit*,const cc_unit*,struct ccrng_state*);
static EC_GROUP*group(ccec_const_cp_t cp){return EC_GROUP_new_by_curve_name(cp->bitlen==256?NID_X9_62_prime256v1:cp->bitlen==384?NID_secp384r1:NID_secp521r1);}
static EC_POINT*point(const EC_GROUP*g,const cc_unit*in,size_t n,BN_CTX*c){BIGNUM*x=BN_lebin2bn((const void*)in,(int)n*8,NULL),*y=BN_lebin2bn((const void*)(in+n),(int)n*8,NULL);EC_POINT*p=EC_POINT_new(g);if(!x||!y||!p||!EC_POINT_set_affine_coordinates(g,p,x,y,c)){EC_POINT_free(p);p=NULL;}BN_free(x);BN_free(y);return p;}
static int save(ccec_const_cp_t cp,struct ccec_ctx*k,const EC_GROUP*g,const EC_POINT*p,BN_CTX*c){BIGNUM*x=BN_new(),*y=BN_new();int rc=-1;if(x&&y&&EC_POINT_get_affine_coordinates(g,p,x,y,c)){k->cp=cp;k->reserved=0;BN_bn2lebinpad(x,(void*)k->data,(int)cp->n*8);BN_bn2lebinpad(y,(void*)(k->data+cp->n),(int)cp->n*8);memset(k->data+2*cp->n,0,cp->n*8);k->data[2*cp->n]=1;rc=0;}BN_free(x);BN_free(y);return rc;}
static int scalar(struct apsic*s,const EC_GROUP*g,BIGNUM*d,BN_CTX*c,cc_unit*out){BIGNUM*q=BN_new();unsigned char buf[72];int rc=-1;if(!q||!EC_GROUP_get_order(g,q,c))goto done;BN_sub_word(q,1);size_t n=BN_num_bytes(q);for(int i=0;i<100;i++){rc=s->rng->generate(s->rng,n,buf);if(rc)break;buf[0]&=(unsigned char)(255>>(8*n-BN_num_bits(q)));BN_bin2bn(buf,(int)n,d);if(BN_cmp(d,q)<0){BN_add_word(d,1);BN_set_flags(d,BN_FLG_CONSTTIME);BN_bn2lebinpad(d,(void*)out,(int)s->cp->n*8);rc=0;break;}rc=-15;}done:BN_free(q);OPENSSL_cleanse(buf,sizeof(buf));return rc;}
EXPORT size_t ccapsic_client_state_sizeof(const struct ccec_ctx*k){return 192+112*k->cp->n;}
EXPORT size_t ccapsic_server_state_sizeof(const struct ccec_ctx*k){return 192+120*k->cp->n;}
EXPORT int ccapsic_client_init(struct apsic*s,const struct ccec_ctx*k,struct ccrng_state*r,size_t n,const void*dst){s->cp=k->cp;s->rng=r;s->h2c=NULL;if(!n||n>128||!r)return -7;size_t limbs=k->cp->n;int zero=1;for(size_t i=0;i<limbs;i++)zero&=k->data[2*limbs+i]==0;if(zero)return -7;switch(k->cp->bitlen){case 256:s->h2c=&apsic256;break;case 384:s->h2c=&apsic384;break;case 521:s->h2c=&apsic521;break;default:return -7;}memcpy(s->data+11*limbs,k->data,24*limbs);int rc=ccec_projectify(k->cp,s->data+2*limbs,k->cp->data+3*limbs+1,r);if(!rc)rc=ccec_projectify(k->cp,s->data+5*limbs,k->data,r);if(rc)return rc;size_t hn=strlen(s->h2c->name);memcpy(s->dst,s->h2c->name,hn);memcpy(s->dst+hn,"APSIC",5);memcpy(s->dst+hn+5,dst,n);s->dst_n=hn+5+n;return 0;}
EXPORT int ccapsic_server_init(struct apsic*s,const struct ccec_ctx*k,struct ccrng_state*r,size_t n,const void*dst){int rc=ccapsic_client_init(s,k,r,n,dst);if(!rc)memcpy(s->data+14*k->cp->n,k->data+3*k->cp->n,k->cp->n*8);return rc;}
static int multiply(struct apsic*s,struct ccec_ctx*out,const struct ccec_ctx*in,const cc_unit*scalar_units){EC_GROUP*g=group(s->cp);BN_CTX*c=BN_CTX_new();BIGNUM*d=BN_lebin2bn((const void*)scalar_units,(int)s->cp->n*8,NULL);EC_POINT*p=g&&c?point(g,in->data,s->cp->n,c):NULL;int rc=-7;if(d)BN_set_flags(d,BN_FLG_CONSTTIME);if(p&&d&&EC_POINT_mul(g,p,NULL,p,d,c))rc=save(s->cp,out,g,p,c);EC_POINT_free(p);BN_clear_free(d);BN_CTX_free(c);EC_GROUP_free(g);return rc;}
EXPORT int ccapsic_server_encode_element(struct apsic*s,struct ccec_ctx*out,size_t n,const void*in){int rc=cch2c(s->h2c,s->dst_n,s->dst,n,in,out);if(!rc){out->cp=s->cp;rc=multiply(s,out,out,s->data+14*s->cp->n);}return rc;}
EXPORT int ccapsic_client_generate_match_response(struct apsic*s,struct ccec_ctx*x,struct ccec_ctx*y){if(x->cp!=s->cp||y->cp!=s->cp)return -7;EC_GROUP*g=group(s->cp);BN_CTX*c=BN_CTX_new();BIGNUM*d=BN_new();EC_POINT*p=g?EC_POINT_new(g):NULL,*pub=g&&c?point(g,s->data+11*s->cp->n,s->cp->n,c):NULL;int rc=-1;if(p&&pub&&d&&c){rc=scalar(s,g,d,c,s->data);if(!rc)rc=EC_POINT_mul(g,p,d,NULL,NULL,c)?save(s->cp,x,g,p,c):-1;if(!rc)rc=EC_POINT_mul(g,p,NULL,pub,d,c)?save(s->cp,y,g,p,c):-1;}EC_POINT_free(p);EC_POINT_free(pub);BN_clear_free(d);BN_CTX_free(c);EC_GROUP_free(g);return rc;}
EXPORT int ccapsic_client_check_intersect_response(struct apsic*s,struct ccec_ctx*x,struct ccec_ctx*y,size_t n,const void*in,const struct ccec_ctx*encoded){if(x->cp!=s->cp||y->cp!=s->cp||encoded->cp!=s->cp)return -7;size_t limbs=s->cp->n;EC_GROUP*g=group(s->cp);BN_CTX*c=BN_CTX_new();BIGNUM*a=BN_new(),*b=BN_new();EC_POINT*p=g?EC_POINT_new(g):NULL,*h=NULL,*e=g&&c?point(g,encoded->data,limbs,c):NULL,*pub=g&&c?point(g,s->data+11*limbs,limbs,c):NULL,*tmp=g?EC_POINT_new(g):NULL;int rc=-1;if(p&&e&&pub&&tmp&&a&&b&&c){rc=scalar(s,g,a,c,s->data);if(!rc)rc=scalar(s,g,b,c,s->data+limbs);if(!rc)rc=cch2c(s->h2c,s->dst_n,s->dst,n,in,x);x->cp=s->cp;if(!rc&&(!memcmp(s->data+11*limbs,encoded->data,24*limbs)))rc=-7;if(!rc){h=point(g,x->data,limbs,c);if(!h||EC_POINT_cmp(g,h,EC_GROUP_get0_generator(g),c)==0)rc=-7;}if(!rc)rc=EC_POINT_mul(g,p,b,h,a,c)?save(s->cp,x,g,p,c):-1;if(!rc)rc=EC_POINT_mul(g,p,NULL,e,a,c)&&EC_POINT_mul(g,tmp,NULL,pub,b,c)&&EC_POINT_add(g,p,p,tmp,c)?save(s->cp,y,g,p,c):-1;}EC_POINT_free(h);EC_POINT_free(p);EC_POINT_free(e);EC_POINT_free(pub);EC_POINT_free(tmp);BN_clear_free(a);BN_clear_free(b);BN_CTX_free(c);EC_GROUP_free(g);return rc;}
EXPORT int ccapsic_server_determine_intersection(struct apsic*s,bool*result,struct ccec_ctx*x,const struct ccec_ctx*y){int rc=multiply(s,x,x,s->data+14*s->cp->n);if(!rc)*result=!memcmp(x->data,y->data,16*s->cp->n);return rc;}
