/* SPDX-License-Identifier: MIT OR Apache-2.0
 * Two-party key generation. The context and wire layouts were measured from
 * the system library; curve arithmetic is supplied by OpenSSL.
 */
#define OPENSSL_SUPPRESS_DEPRECATED
#include "ccec.h"
#include "ccdigest.h"
#include <openssl/ec.h>
#include <openssl/obj_mac.h>
#include <openssl/crypto.h>
#include <string.h>
#define API __attribute__((visibility("default")))
struct ccckg_ctx { uint32_t version,reserved; ccec_const_cp_t cp; const struct ccdigest_info *di; struct ccrng_state *rng; unsigned char state,pad[7]; cc_unit data[]; };
struct ccckg2_params { uint32_t version,reserved; ccec_const_cp_t (*cp)(void); const struct ccdigest_info *(*di)(void); };
extern int ccansikdf_x963(const struct ccdigest_info*,size_t,const void*,size_t,const void*,size_t,void*);
static size_t width(ccec_const_cp_t cp){return(cp->bitlen+7)/8;}
static size_t pubsize(ccec_const_cp_t cp){return 2*width(cp)+1;}
static size_t aligned(size_t n){return(n+7)&~(size_t)7;}
static unsigned char*nonce(struct ccckg_ctx*c){return(void*)(c->data+c->cp->n);}
static unsigned char*commitment(struct ccckg_ctx*c){return nonce(c)+aligned(c->di->output_size);}
static unsigned char*tail2(struct ccckg_ctx*c){return(void*)(c->data+2*c->cp->n);}
static EC_GROUP*group(ccec_const_cp_t cp){int nid=0;switch(cp->bitlen){case 192:nid=NID_X9_62_prime192v1;break;case 224:nid=NID_secp224r1;break;case 256:nid=NID_X9_62_prime256v1;break;case 384:nid=NID_secp384r1;break;case 521:nid=NID_secp521r1;break;}return nid?EC_GROUP_new_by_curve_name(nid):NULL;}
static BIGNUM*readle(const cc_unit*p,size_t n){return BN_lebin2bn((const void*)p,(int)(8*n),NULL);}
static int savepoint(ccec_const_cp_t cp,struct ccec_ctx*out,const EC_GROUP*g,const EC_POINT*p,BN_CTX*c){BIGNUM*x=BN_new(),*y=BN_new();int ok=x&&y&&EC_POINT_get_affine_coordinates(g,p,x,y,c);if(ok){out->cp=cp;BN_bn2lebinpad(x,(void*)out->data,(int)(8*cp->n));BN_bn2lebinpad(y,(void*)(out->data+cp->n),(int)(8*cp->n));memset(out->data+2*cp->n,0,8*cp->n);out->data[2*cp->n]=1;}BN_free(x);BN_free(y);return ok?0:-7;}
static int random_key(struct ccckg_ctx*c,struct ccrng_state*r,cc_unit*scalar,void*pub){_Alignas(16) unsigned char storage[304]={0};struct ccec_ctx*k=(void*)storage;int rc=ccec_generate_key(c->cp,r,k);if(!rc){memcpy(scalar,k->data+3*c->cp->n,8*c->cp->n);if(pub)rc=ccec_export_pub(k,pub);}OPENSSL_cleanse(storage,sizeof(storage));return rc;}
static int random_check(struct ccrng_state*r){unsigned char b[32];if(!r||!r->generate)return -7;int rc=r->generate(r,sizeof(b),b);OPENSSL_cleanse(b,sizeof(b));return rc;}
/* Sum the contributor's scalar times G and the owner's public point. */
static int derive_public(struct ccckg_ctx*c,const void*share,struct ccec_ctx*out,struct ccrng_state*r){if(((const unsigned char*)share)[0]!=4)return -7;int rc=random_check(r);if(rc)return rc;EC_GROUP*g=group(c->cp);BN_CTX*bn=BN_CTX_new();EC_POINT*p=g?EC_POINT_new(g):NULL,*a=g?EC_POINT_new(g):NULL;BIGNUM*d=readle(c->data,c->cp->n);rc=-7;if(d)BN_set_flags(d,BN_FLG_CONSTTIME);if(p&&a&&bn&&d&&EC_POINT_oct2point(g,p,share,pubsize(c->cp),bn)&&EC_POINT_mul(g,a,d,NULL,NULL,bn)&&EC_POINT_add(g,p,p,a,bn))rc=savepoint(c->cp,out,g,p,bn);BN_clear_free(d);EC_POINT_free(p);EC_POINT_free(a);EC_GROUP_free(g);BN_CTX_free(bn);return rc;}
static int derive_private(struct ccckg_ctx*c,const void*opening,struct ccec_ctx*out,struct ccrng_state*r){int rc=random_check(r);if(rc)return rc;EC_GROUP*g=group(c->cp);BN_CTX*bn=BN_CTX_new();EC_POINT*p=g?EC_POINT_new(g):NULL;BIGNUM*a=BN_bin2bn(opening,(int)width(c->cp),NULL),*b=readle(c->data,c->cp->n),*q=BN_new();rc=-7;if(a)BN_set_flags(a,BN_FLG_CONSTTIME);if(p&&bn&&a&&b&&q&&EC_GROUP_get_order(g,q,bn)&&!BN_is_zero(a)&&BN_cmp(a,q)<0&&BN_mod_add(a,a,b,q,bn)&&!BN_is_zero(a)&&EC_POINT_mul(g,p,a,NULL,NULL,bn)){rc=savepoint(c->cp,out,g,p,bn);if(!rc)BN_bn2lebinpad(a,(void*)(out->data+3*c->cp->n),(int)(8*c->cp->n));}BN_clear_free(a);BN_clear_free(b);BN_free(q);EC_POINT_free(p);EC_GROUP_free(g);BN_CTX_free(bn);return rc;}
static int derive_v1(struct ccckg_ctx*c,const struct ccec_ctx*k,const void*contributor_nonce,const void*owner_nonce,size_t n,void*out){unsigned char x[66],info[128];size_t h=c->di->output_size;if(h>64)return -7;ccn_write_uint_padded_ct(c->cp->n,k->data,width(c->cp),x);memcpy(info,contributor_nonce,h);memcpy(info+h,owner_nonce,h);int rc=ccansikdf_x963(c->di,width(c->cp),x,2*h,info,n,out);OPENSSL_cleanse(x,sizeof(x));OPENSSL_cleanse(info,sizeof(info));return rc;}
API ccec_const_cp_t ccckg_ctx_cp(const struct ccckg_ctx*c){return c->cp;}
API const struct ccdigest_info*ccckg_ctx_di(const struct ccckg_ctx*c){return c->di;}
API size_t ccckg_sizeof_ctx(ccec_const_cp_t cp,const struct ccdigest_info*di){return 40+8*cp->n+((2*di->output_size+14)&~(size_t)15);}
API size_t ccckg_sizeof_commitment(ccec_const_cp_t cp,const struct ccdigest_info*di){(void)cp;return di->output_size;}
API size_t ccckg_sizeof_share(ccec_const_cp_t cp,const struct ccdigest_info*di){return pubsize(cp)+di->output_size;}
API size_t ccckg_sizeof_opening(ccec_const_cp_t cp,const struct ccdigest_info*di){return width(cp)+di->output_size;}
API int ccckg_init(struct ccckg_ctx*c,ccec_const_cp_t cp,const struct ccdigest_info*di,struct ccrng_state*r){memset(c,0,ccckg_sizeof_ctx(cp,di));c->version=1;c->cp=cp;c->di=di;c->rng=r;return 0;}
API int ccckg_contributor_commit(struct ccckg_ctx*c,size_t n,void*out){if(c->state)return -86;if(n!=c->di->output_size)return -7;int rc=random_key(c,c->rng,c->data,NULL);if(rc)return rc;rc=c->rng->generate(c->rng,n,nonce(c));if(rc)return rc;unsigned char opening[130];ccn_write_uint_padded_ct(c->cp->n,c->data,width(c->cp),opening);memcpy(opening+width(c->cp),nonce(c),n);ccdigest(c->di,width(c->cp)+n,opening,out);OPENSSL_cleanse(opening,sizeof(opening));c->state=1;return 0;}
API int ccckg_owner_generate_share(struct ccckg_ctx*c,size_t cn,const void*commit,size_t sn,void*share){if(c->state)return -86;if(cn!=c->di->output_size||sn!=ccckg_sizeof_share(c->cp,c->di))return -7;memcpy(commitment(c),commit,cn);int rc=random_key(c,c->rng,c->data,share);if(rc)return rc;rc=c->rng->generate(c->rng,c->di->output_size,nonce(c));if(rc)return rc;memcpy((unsigned char*)share+pubsize(c->cp),nonce(c),c->di->output_size);c->state=2;return 0;}
API int ccckg_contributor_finish(struct ccckg_ctx*c,size_t sn,const void*share,size_t on,void*opening,struct ccec_ctx*pub,size_t kn,void*key){if(c->state!=1)return -86;if(pub->cp!=c->cp||sn!=ccckg_sizeof_share(c->cp,c->di)||on!=ccckg_sizeof_opening(c->cp,c->di))return -7;int rc=derive_public(c,share,pub,c->rng);if(!rc)rc=derive_v1(c,pub,nonce(c),(const unsigned char*)share+pubsize(c->cp),kn,key);if(rc)return rc;ccn_write_uint_padded_ct(c->cp->n,c->data,width(c->cp),opening);memcpy((unsigned char*)opening+width(c->cp),nonce(c),c->di->output_size);c->state=3;return 0;}
API int ccckg_owner_finish(struct ccckg_ctx*c,size_t on,const void*opening,struct ccec_ctx*full,size_t kn,void*key){if(c->state!=2)return -86;if(full->cp!=c->cp||on!=ccckg_sizeof_opening(c->cp,c->di)||c->di->output_size>64)return -7;unsigned char digest[64];ccdigest(c->di,on,opening,digest);int bad=CRYPTO_memcmp(digest,commitment(c),c->di->output_size);OPENSSL_cleanse(digest,sizeof(digest));if(bad)return -2;int rc=derive_private(c,opening,full,c->rng);if(!rc)rc=derive_v1(c,full,(const unsigned char*)opening+width(c->cp),nonce(c),kn,key);if(!rc)c->state=3;return rc;}
static const struct ccckg2_params params={2,0,ccec_cp_224,ccsha256_di};
API const struct ccckg2_params*ccckg2_params_p224_sha256_v2(void){return &params;}
API ccec_const_cp_t ccckg2_ctx_cp(const struct ccckg_ctx*c){return c->cp;}
API const struct ccdigest_info*ccckg2_ctx_di(const struct ccckg_ctx*c){return c->di;}
API size_t ccckg2_sizeof_ctx(const struct ccckg2_params*p){ccec_const_cp_t cp=p->cp();size_t tail=pubsize(cp),h=aligned(p->di()->output_size);return 40+16*cp->n+(tail>h?tail:h);}
API size_t ccckg2_sizeof_commitment(const struct ccckg2_params*p){return p->di()->output_size;}
API size_t ccckg2_sizeof_share(const struct ccckg2_params*p){return 2*pubsize(p->cp());}
API size_t ccckg2_sizeof_opening(const struct ccckg2_params*p){return width(p->cp())+pubsize(p->cp());}
API int ccckg2_init(struct ccckg_ctx*c,const struct ccckg2_params*p){if(p->version!=2)return -7;memset(c,0,ccckg2_sizeof_ctx(p));c->version=2;c->cp=p->cp();c->di=p->di();return 0;}
API int ccckg2_contributor_commit(struct ccckg_ctx*c,size_t n,void*out,struct ccrng_state*r){if(c->state)return -86;if(c->version!=2||n!=c->di->output_size)return -7;int rc=random_key(c,r,c->data,NULL);if(!rc)rc=random_key(c,r,c->data+c->cp->n,tail2(c));if(rc)return rc;unsigned char opening[199];size_t w=width(c->cp),pn=pubsize(c->cp);ccn_write_uint_padded_ct(c->cp->n,c->data,w,opening);memcpy(opening+w,tail2(c),pn);ccdigest(c->di,w+pn,opening,out);OPENSSL_cleanse(opening,sizeof(opening));c->state=1;return 0;}
API int ccckg2_owner_generate_share(struct ccckg_ctx*c,size_t cn,const void*commit,size_t sn,void*share,struct ccrng_state*r){if(c->state)return -86;if(cn!=c->di->output_size||sn!=2*pubsize(c->cp))return -7;memcpy(tail2(c),commit,cn);int rc=random_key(c,r,c->data,share);if(!rc)rc=random_key(c,r,c->data+c->cp->n,(unsigned char*)share+pubsize(c->cp));if(!rc)c->state=2;return rc;}
static int derive_v2(struct ccckg_ctx*c,const void*peer,const struct ccec_ctx*pub,size_t kn,void*key,struct ccrng_state*r){if(((const unsigned char*)peer)[0]!=4)return -7;int rc=random_check(r);if(rc)return rc;EC_GROUP*g=group(c->cp);BN_CTX*bn=BN_CTX_new();EC_POINT*p=g?EC_POINT_new(g):NULL;BIGNUM*d=readle(c->data+c->cp->n,c->cp->n);unsigned char x[66],info[133];rc=-7;if(d)BN_set_flags(d,BN_FLG_CONSTTIME);if(g&&bn&&p&&d&&EC_POINT_oct2point(g,p,peer,pubsize(c->cp),bn)&&EC_POINT_mul(g,p,NULL,p,d,bn)&&!EC_POINT_is_at_infinity(g,p)&&EC_POINT_point2oct(g,p,POINT_CONVERSION_UNCOMPRESSED,info,sizeof(info),bn)==pubsize(c->cp)){ccn_write_uint_padded_ct(c->cp->n,pub->data,width(c->cp),x);rc=ccansikdf_x963(c->di,width(c->cp),x,pubsize(c->cp),info,kn,key);}OPENSSL_cleanse(x,sizeof(x));OPENSSL_cleanse(info,sizeof(info));BN_clear_free(d);EC_POINT_free(p);EC_GROUP_free(g);BN_CTX_free(bn);return rc;}
API int ccckg2_contributor_finish(struct ccckg_ctx*c,size_t sn,const void*share,size_t on,void*opening,struct ccec_ctx*pub,size_t kn,void*key,struct ccrng_state*r){if(c->state!=1)return -86;if(c->version!=2||pub->cp!=c->cp||sn!=2*pubsize(c->cp)||on!=width(c->cp)+pubsize(c->cp))return -7;int rc=derive_public(c,share,pub,r);if(!rc)rc=derive_v2(c,(const unsigned char*)share+pubsize(c->cp),pub,kn,key,r);if(rc)return rc;ccn_write_uint_padded_ct(c->cp->n,c->data,width(c->cp),opening);memcpy((unsigned char*)opening+width(c->cp),tail2(c),pubsize(c->cp));c->state=3;return 0;}
API int ccckg2_owner_finish(struct ccckg_ctx*c,size_t on,const void*opening,struct ccec_ctx*full,size_t kn,void*key,struct ccrng_state*r){if(c->state!=2)return -86;if(full->cp!=c->cp||on!=width(c->cp)+pubsize(c->cp)||c->di->output_size>64)return -7;unsigned char digest[64];ccdigest(c->di,on,opening,digest);int bad=CRYPTO_memcmp(digest,tail2(c),c->di->output_size);OPENSSL_cleanse(digest,sizeof(digest));if(bad)return -2;int rc=derive_private(c,opening,full,r);if(!rc)rc=derive_v2(c,(const unsigned char*)opening+width(c->cp),full,kn,key,r);if(!rc)c->state=3;return rc;}
