/* SPDX-License-Identifier: MIT OR Apache-2.0 */
#include "cche.h"
#include "ccrng.h"
#include <openssl/evp.h>
#include <openssl/crypto.h>
#include <stdlib.h>
#include <string.h>
#define EXPORT __attribute__((visibility("default")))
struct he_block_rng {struct ccrng_state rng;unsigned char key[16],v[16],buffer[4096];size_t offset;};
static int block_expand(struct he_block_rng*r,size_t n,unsigned char*out){EVP_CIPHER_CTX*c=EVP_CIPHER_CTX_new();if(!c)return -13;int rc=-1,z;if(EVP_EncryptInit_ex(c,EVP_aes_128_ecb(),NULL,r->key,NULL)!=1||EVP_CIPHER_CTX_set_padding(c,0)!=1)goto done;for(size_t i=0;i<n;i+=16){for(int j=15;j>=0;j--)if(++r->v[j])break;if(EVP_EncryptUpdate(c,out+i,&z,r->v,16)!=1||z!=16)goto done;}rc=0;done:EVP_CIPHER_CTX_free(c);return rc;}
static int block_update(struct he_block_rng*r,const unsigned char*seed){unsigned char b[32];int rc=block_expand(r,32,b);if(!rc){if(seed)for(unsigned i=0;i<32;i++)b[i]^=seed[i];memcpy(r->key,b,16);memcpy(r->v,b+16,16);}OPENSSL_cleanse(b,sizeof b);return rc;}
static int block_generate(struct ccrng_state*state,size_t n,void*out){struct he_block_rng*r=(void*)state;unsigned char*b=out;while(n){if(r->offset==4096){int rc=block_expand(r,4096,r->buffer);if(!rc)rc=block_update(r,NULL);if(rc)return rc;r->offset=0;}size_t take=4096-r->offset;if(take>n)take=n;memcpy(b,r->buffer+r->offset,take);r->offset+=take;b+=take;n-=take;}return 0;}
static int block_init(struct he_block_rng*r,const void*seed){memset(r,0,sizeof *r);r->rng.generate=block_generate;r->offset=4096;return block_update(r,seed);}
static int sample(struct he_poly*p,struct ccrng_state*rng,unsigned kind){unsigned n=p->ctx->n,l=p->ctx->l,chunk=n<128?n:128,width=kind==0?16:kind==1?12:6;unsigned char buf[2048];for(unsigned limb=0;limb<(kind?1:l);limb++)for(unsigned j=0;j<n;j++){if(j%chunk==0){int rc=rng->generate(rng,chunk*width,buf);if(rc)return rc;}__uint128_t v=0;memcpy(&v,buf+(j%chunk)*width,width);if(!kind)p->data[(size_t)limb*n+j]=v%finch_he_modulus(p->ctx,limb);else{int val=kind==1?(int)(v%3)-1:__builtin_popcountll((uint64_t)v&0x1fffff)-__builtin_popcountll(((uint64_t)v>>21)&0x1fffff);for(unsigned k=0;k<l;k++){uint64_t q=finch_he_modulus(p->ctx,k);p->data[(size_t)k*n+j]=val<0?q-(uint64_t)(-val):(uint64_t)val;}}}OPENSSL_cleanse(buf,sizeof buf);return 0;}
EXPORT int cche_secret_key_generate(struct he_poly*out,const struct he_params*p,struct ccrng_state*rng){out->ctx=finch_he_ring(p,p->l);int rc=sample(out,rng,1);return rc?rc:finch_he_ntt(out,0);}
EXPORT int cche_secret_key_generate_from_seed(struct he_poly*out,const struct he_params*p,const void*seed){struct he_block_rng r;int rc=block_init(&r,seed);if(!rc)rc=cche_secret_key_generate(out,p,&r.rng);OPENSSL_cleanse(&r,sizeof r);return rc;}
#include <openssl/bn.h>
static int cipher_init(struct he_cipher*c,const struct he_params*p,unsigned l,unsigned np){if(!l||l>p->l||!np)return -7;c->params=p;c->npolys=np;c->correction=1;struct he_ring*r=finch_he_ring(p,l);for(unsigned i=0;i<np;i++)((struct he_poly*)(c->data+i*(8+8*(size_t)p->n*l)))->ctx=r;return 0;}
EXPORT int cche_ciphertext_plaintext_add(struct he_cipher*out,const struct he_cipher*in,const struct he_poly*plain){const struct he_params*p=in->params;const struct he_poly*c0=(void*)in->data;unsigned l=c0->ctx->l;if(in->npolys!=2||out->npolys!=2||plain->ctx->n!=p->n||plain->ctx->mod[0]!=p->t||(p->scheme==1&&in->correction!=1))return -7;size_t bytes=24+2*(8+8*(size_t)p->n*l);if(out!=in)memcpy(out,in,bytes);struct he_poly*z=(void*)out->data;BN_CTX*bc=BN_CTX_new();if(!bc)return -13;BN_CTX_start(bc);BIGNUM*Q=BN_CTX_get(bc),*t=BN_CTX_get(bc),*m=BN_CTX_get(bc),*scaled=BN_CTX_get(bc);int rc=-1;if(!scaled||!BN_one(Q)||!BN_set_word(t,p->t))goto done;for(unsigned k=0;k<l;k++)if(!BN_mul_word(Q,p->q[k]))goto done;for(unsigned j=0;j<p->n;j++){if(p->scheme==1){if(!BN_set_word(m,plain->data[j])||!BN_mul(scaled,Q,m,bc)||!BN_add_word(scaled,(p->t+1)/2)||!BN_div(scaled,NULL,scaled,t,bc))goto done;}for(unsigned k=0;k<l;k++){uint64_t q=p->q[k],v=p->scheme==1?BN_mod_word(scaled,q):finch_he_mul(plain->data[j],in->correction,p->t);z->data[(size_t)k*p->n+j]=(z->data[(size_t)k*p->n+j]+v)%q;}}rc=0;done:BN_CTX_end(bc);BN_CTX_free(bc);return rc;}
static int encrypt_zero(struct he_cipher*out,const struct he_params*p,const struct he_poly*sk,unsigned l,int eval,void*seed,struct ccrng_state*rng){if(!l||l>p->l||sk->ctx->n!=p->n||sk->ctx->l!=p->l)return -7;int rc=cipher_init(out,p,l,2);if(rc)return rc;struct he_poly*c0=finch_he_poly(out,0),*c1=finch_he_poly(out,1),*e=malloc(8+8*(size_t)p->n*l);if(!e)return -13;e->ctx=c0->ctx;struct he_block_rng br;if(seed){rc=rng->generate(rng,32,seed);if(!rc)rc=block_init(&br,seed);if(!rc)rc=sample(c1,&br.rng,0);OPENSSL_cleanse(&br,sizeof br);}else rc=sample(c1,rng,0);if(rc)goto done;rc=sample(e,rng,2);if(rc)goto done;for(unsigned k=0;k<l;k++)for(unsigned j=0;j<p->n;j++){size_t i=(size_t)k*p->n+j;c0->data[i]=finch_he_mul(c1->data[i],sk->data[i],p->q[k]);if(p->scheme==2)e->data[i]=finch_he_mul(e->data[i],p->t,p->q[k]);}if(eval)rc=finch_he_ntt(e,0);else{rc=finch_he_ntt(c0,1);if(!rc)rc=finch_he_ntt(c1,1);}if(rc)goto done;for(unsigned k=0;k<l;k++)for(unsigned j=0;j<p->n;j++){size_t i=(size_t)k*p->n+j;uint64_t q=p->q[k],v=(c0->data[i]+e->data[i])%q;c0->data[i]=v?q-v:0;}done:OPENSSL_clear_free(e,8+8*(size_t)p->n*l);return rc;}
EXPORT int cche_encrypt_zero_symmetric_coeff(struct he_cipher*out,const struct he_params*p,const struct he_poly*sk,unsigned l,void*seed,struct ccrng_state*rng){return encrypt_zero(out,p,sk,l,0,seed,rng);}
EXPORT int cche_encrypt_zero_symmetric_eval(struct he_cipher*out,const struct he_params*p,const struct he_poly*sk,unsigned l,void*seed,struct ccrng_state*rng){return encrypt_zero(out,p,sk,l,1,seed,rng);}
EXPORT int cche_encrypt_symmetric(struct he_cipher*out,const struct he_poly*plain,const struct he_params*p,const struct he_poly*sk,unsigned l,void*seed,struct ccrng_state*rng){int rc=encrypt_zero(out,p,sk,l,0,seed,rng);return rc?rc:cche_ciphertext_plaintext_add(out,out,plain);}
EXPORT int cche_decrypt(struct he_poly*out,const struct he_params*p,const struct he_cipher*in,const struct he_poly*sk){const struct he_poly*c0=(void*)in->data;unsigned n=p->n,l=c0->ctx->l;if(!l||l>p->l||!in->npolys||in->params!=p||sk->ctx->n!=n||sk->ctx->l!=p->l)return -7;size_t bytes=8+8*(size_t)n*l;struct he_poly*sum=calloc(1,bytes),*tmp=malloc(bytes);BN_CTX*bc=BN_CTX_new();if(!sum||!tmp||!bc){free(sum);free(tmp);BN_CTX_free(bc);return -13;}sum->ctx=c0->ctx;int rc=0;for(unsigned pol=0;pol<in->npolys&&!rc;pol++){memcpy(tmp,finch_he_poly((void*)in,pol),bytes);rc=finch_he_ntt(tmp,0);for(unsigned k=0;k<l;k++)for(unsigned j=0;j<n;j++){size_t i=(size_t)k*n+j;uint64_t v=finch_he_mul(tmp->data[i],finch_he_pow(sk->data[i],pol,p->q[k]),p->q[k]);sum->data[i]=(sum->data[i]+v)%p->q[k];}}if(!rc)rc=finch_he_ntt(sum,1);if(rc)goto done;out->ctx=finch_he_plain_ring(p);BN_CTX_start(bc);BIGNUM*Q=BN_CTX_get(bc),*part=BN_CTX_get(bc),*qi=BN_CTX_get(bc),*inv=BN_CTX_get(bc),*x=BN_CTX_get(bc),*v=BN_CTX_get(bc),*half=BN_CTX_get(bc),*t=BN_CTX_get(bc);BIGNUM**factors=calloc(l,sizeof *factors);if(!t||!factors||!BN_one(Q)||!BN_set_word(t,p->t)){rc=-13;free(factors);BN_CTX_end(bc);goto done;}for(unsigned k=0;k<l;k++)BN_mul_word(Q,p->q[k]);BN_rshift1(half,Q);for(unsigned k=0;k<l;k++){BN_set_word(qi,p->q[k]);BN_div(part,NULL,Q,qi,bc);if(!BN_mod_inverse(inv,part,qi,bc)||(factors[k]=BN_new())==NULL||!BN_mul(factors[k],part,inv,bc)){rc=-1;break;}}uint64_t cinv=1;if(!rc&&p->scheme==2){BN_set_word(v,in->correction);if(!BN_mod_inverse(inv,v,t,bc))rc=-7;else cinv=BN_get_word(inv);}for(unsigned j=0;j<n&&!rc;j++){BN_zero(x);for(unsigned k=0;k<l;k++){BN_set_word(v,sum->data[(size_t)k*n+j]);BN_mul(v,v,factors[k],bc);BN_add(x,x,v);}BN_nnmod(x,x,Q,bc);if(p->scheme==1){BN_mul(x,x,t,bc);BN_add(x,x,half);BN_div(x,NULL,x,Q,bc);out->data[j]=BN_mod_word(x,p->t);}else{if(BN_cmp(x,half)>0)BN_sub(x,x,Q);BN_nnmod(x,x,t,bc);out->data[j]=finch_he_mul(BN_get_word(x),cinv,p->t);}}for(unsigned k=0;k<l;k++)BN_clear_free(factors[k]);free(factors);BN_CTX_end(bc);done:OPENSSL_clear_free(sum,bytes);OPENSSL_clear_free(tmp,bytes);BN_CTX_free(bc);return rc;}
int finch_he_poly_read(struct he_poly*,const void*,unsigned);
size_t cche_serialize_seeded_ciphertext_coeff_nbytes(const struct he_cipher*);
static int deserialize_seeded(struct he_cipher*out,size_t n,const void*in,const void*seed,const struct he_params*p,unsigned l,uint64_t correction,int eval){int rc=cipher_init(out,p,l,2);if(rc)return rc;if(n!=cche_serialize_seeded_ciphertext_coeff_nbytes(out))return -7;out->correction=correction;rc=finch_he_poly_read(finch_he_poly(out,0),in,0);struct he_block_rng br;if(!rc)rc=block_init(&br,seed);if(!rc)rc=sample(finch_he_poly(out,1),&br.rng,0);if(!rc&&!eval)rc=finch_he_ntt(finch_he_poly(out,1),1);OPENSSL_cleanse(&br,sizeof br);return rc;}
EXPORT int cche_deserialize_seeded_ciphertext_coeff(struct he_cipher*out,size_t n,const void*in,const void*seed,const struct he_params*p,unsigned l,uint64_t correction){return deserialize_seeded(out,n,in,seed,p,l,correction,0);}
EXPORT int cche_deserialize_seeded_ciphertext_eval(struct he_cipher*out,size_t n,const void*in,const void*seed,const struct he_params*p,unsigned l,uint64_t correction){return deserialize_seeded(out,n,in,seed,p,l,correction,1);}
EXPORT int cche_dcrt_plaintext_encode(struct he_poly*out,const struct he_poly*in,const struct he_params*p,unsigned l){if(!l||l>(p->l>1?p->l-1:1)||in->ctx->n!=p->n||in->ctx->mod[0]!=p->t)return -7;out->ctx=finch_he_ring(p,l);for(unsigned k=0;k<l;k++)for(unsigned j=0;j<p->n;j++){uint64_t x=in->data[j];out->data[(size_t)k*p->n+j]=x>p->t/2?p->q[k]-(p->t-x):x;}return finch_he_ntt(out,0);}
EXPORT int cche_ciphertext_eval_dcrt_plaintext_mul(struct he_cipher*out,const struct he_cipher*in,const struct he_poly*pt){const struct he_poly*c=(void*)in->data;unsigned n=c->ctx->n,l=c->ctx->l;if(pt->ctx->n!=n||pt->ctx->l!=l||out->npolys!=in->npolys)return -7;if(out!=in)memcpy(out,in,24+in->npolys*(8+8*(size_t)n*l));for(unsigned pol=0;pol<in->npolys;pol++){struct he_poly*z=finch_he_poly(out,pol);for(unsigned k=0;k<l;k++)for(unsigned j=0;j<n;j++){size_t i=(size_t)k*n+j;z->data[i]=finch_he_mul(z->data[i],pt->data[i],finch_he_modulus(c->ctx,k));}}return 0;}
EXPORT int cche_ciphertext_coeff_dcrt_plaintext_mul(struct he_cipher*out,const struct he_cipher*in,const struct he_poly*pt){const struct he_poly*c=(void*)in->data;if(out!=in)memcpy(out,in,24+in->npolys*(8+8*(size_t)c->ctx->n*c->ctx->l));int rc=0;for(unsigned i=0;i<out->npolys&&!rc;i++)rc=finch_he_ntt(finch_he_poly(out,i),0);if(!rc)rc=cche_ciphertext_eval_dcrt_plaintext_mul(out,out,pt);for(unsigned i=0;i<out->npolys&&!rc;i++)rc=finch_he_ntt(finch_he_poly(out,i),1);return rc;}
static int plaintext_mul(struct he_cipher*out,const struct he_cipher*in,const struct he_poly*pt,int eval){const struct he_poly*c=(void*)in->data;struct he_poly*dcrt=malloc(8+8*(size_t)c->ctx->n*c->ctx->l);if(!dcrt)return -13;int rc=cche_dcrt_plaintext_encode(dcrt,pt,in->params,c->ctx->l);if(!rc)rc=eval?cche_ciphertext_eval_dcrt_plaintext_mul(out,in,dcrt):cche_ciphertext_coeff_dcrt_plaintext_mul(out,in,dcrt);free(dcrt);return rc;}
EXPORT int cche_ciphertext_coeff_plaintext_mul(struct he_cipher*out,const struct he_cipher*in,const struct he_poly*pt){return plaintext_mul(out,in,pt,0);}
EXPORT int cche_ciphertext_eval_plaintext_mul(struct he_cipher*out,const struct he_cipher*in,const struct he_poly*pt){return plaintext_mul(out,in,pt,1);}
