/* SPDX-License-Identifier: MIT OR Apache-2.0 */
#include "cche.h"
#include <openssl/bn.h>
#include <stdlib.h>
#include <string.h>
#define EXPORT __attribute__((visibility("default")))
static unsigned part_count(uint64_t q,unsigned bits,unsigned skip){unsigned qbits=64-__builtin_clzll(q-1);return skip>=qbits?0:(qbits-skip+bits-1)/bits;}
EXPORT uint32_t cche_ciphertext_coeff_decompose_nptexts(const struct he_cipher*c,const uint32_t*skip){const struct he_poly*p=(void*)c->data;unsigned n=0,bits=63-__builtin_clzll(c->params->t);for(unsigned i=0;i<c->npolys;i++)for(unsigned j=0;j<p->ctx->l;j++)n+=part_count(finch_he_modulus(p->ctx,j),bits,skip?skip[i*p->ctx->l+j]:0);return n;}
EXPORT int cche_ciphertext_coeff_decompose(uint32_t np,struct he_poly**out,const struct he_cipher*c,const uint32_t*skip){if(np!=cche_ciphertext_coeff_decompose_nptexts(c,skip))return -7;unsigned bits=63-__builtin_clzll(c->params->t),idx=0;uint64_t mask=((uint64_t)1<<bits)-1;for(unsigned i=0;i<c->npolys;i++){const struct he_poly*p=finch_he_poly((void*)c,i);for(unsigned j=0;j<p->ctx->l;j++){unsigned s=skip?skip[i*p->ctx->l+j]:0,count=part_count(finch_he_modulus(p->ctx,j),bits,s);for(unsigned k=0;k<count;k++,idx++,s+=bits){if(s>=64)return -7;out[idx]->ctx=finch_he_plain_ring(c->params);for(unsigned a=0;a<p->ctx->n;a++)out[idx]->data[a]=(p->data[(size_t)j*p->ctx->n+a]>>s)&mask;}}}return 0;}
EXPORT int cche_ciphertext_coeff_compose(struct he_cipher*out,uint32_t np,const struct he_poly*const*in,const struct he_params*p,unsigned l,uint64_t correction,const uint32_t*skip){if(!np||!l||l>p->l||correction>=p->t)return -7;memset(out,0,24+2*(8+8*(size_t)p->n*l));out->params=p;out->npolys=2;out->correction=correction;for(unsigned i=0;i<2;i++)((struct he_poly*)(out->data+i*(8+8*(size_t)p->n*l)))->ctx=finch_he_ring(p,l);if(np!=cche_ciphertext_coeff_decompose_nptexts(out,skip))return -7;unsigned bits=63-__builtin_clzll(p->t),idx=0;for(unsigned i=0;i<2;i++){struct he_poly*z=finch_he_poly(out,i);for(unsigned j=0;j<l;j++){unsigned s=skip?skip[i*l+j]:0,count=part_count(p->q[j],bits,s);for(unsigned k=0;k<count;k++,idx++,s+=bits){if(s>=64)return -7;for(unsigned a=0;a<p->n;a++)z->data[(size_t)j*p->n+a]|=in[idx]->data[a]<<s;}}}return 0;}
EXPORT int cche_ciphertext_galois_elt_rotate_rows_left(uint32_t*out,int32_t step,uint32_t n){if(!n||(n&(n-1))||(step<0?-(int64_t)step:step)>=n/2)return -7;unsigned exponent=step<0?n/2+step:step;*out=(uint32_t)finch_he_pow(3,exponent,2*(uint64_t)n);return 0;}
EXPORT int cche_ciphertext_galois_elt_rotate_rows_right(uint32_t*out,int32_t step,uint32_t n){if(step==INT32_MIN)return -7;return cche_ciphertext_galois_elt_rotate_rows_left(out,-step,n);}
EXPORT int cche_ciphertext_galois_elt_swap_columns(uint32_t*out,uint32_t n){if(!n||(n&(n-1)))return -7;*out=2*n-1;return 0;}
EXPORT int cche_crt_compose(size_t n,int64_t*out,const int64_t*in,uint32_t l,const uint64_t*moduli){uint64_t Q=1;for(unsigned k=0;k<l;k++){if(moduli[k]<2||moduli[k]>UINT64_MAX/Q)return -1;Q*=moduli[k];}if(l==1){memcpy(out,in,n*8);return 0;}BN_CTX*bc=BN_CTX_new();BIGNUM*a=BN_new(),*q=BN_new(),*inv=NULL;uint64_t*f=calloc(l?l:1,8);int rc=-1;if(!bc||!a||!q||!f)goto done;for(unsigned k=0;k<l;k++){uint64_t part=Q/moduli[k];BN_set_word(a,part%moduli[k]);BN_set_word(q,moduli[k]);inv=BN_mod_inverse(NULL,a,q,bc);if(!inv)goto done;f[k]=finch_he_mul(part,BN_get_word(inv),Q);BN_free(inv);inv=NULL;}for(size_t j=0;j<n;j++){uint64_t x=0;for(unsigned k=0;k<l;k++){int64_t v=in[(size_t)k*n+j];uint64_t r=v<0?moduli[k]-(uint64_t)(-(__int128)v)%moduli[k]:(uint64_t)v%moduli[k];x=(uint64_t)(((__uint128_t)x+finch_he_mul(r,f[k],Q))%Q);}out[j]=x>Q/2?(int64_t)(x-Q):(int64_t)x;}rc=0;done:BN_free(inv);BN_free(a);BN_free(q);BN_CTX_free(bc);free(f);return rc;}
