/* SPDX-License-Identifier: MIT OR Apache-2.0
 * HPKE base mode and X-Wing, built from OpenSSL and Finch primitives. */
#include "ccrng.h"
#include "ccdigest.h"
#include <openssl/evp.h>
#include <openssl/core_names.h>
#include <openssl/params.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#define EXPORT __attribute__((visibility("default")))
struct hpke_params;
typedef int(*aead_fn)(size_t,const void*,size_t,const void*,size_t,const void*,size_t,const void*,void*,size_t,void*);
struct hpke_kdf{uint64_t id;size_t hash_size;void(*hash)(size_t,const void*,void*);const struct ccdigest_info*(*di)(void);};
struct hpke_aead{uint64_t id;size_t key_size,tag_size,nonce_size;aead_fn seal,open;};
struct hpke_kem{uint64_t id;size_t enc_size,shared_size,pk_size,pk_wire_size,sk_size;int(*generate)(struct ccrng_state*,size_t,void*,size_t,void*);int(*encap)(const struct hpke_params*,struct ccrng_state*,size_t,const void*,size_t,void*,size_t,void*);int(*encap_det)(const struct hpke_params*,size_t,const void*,size_t,const void*,size_t,const void*,size_t,void*,size_t,void*);int(*decap)(const struct hpke_params*,size_t,const void*,size_t,const void*,size_t,void*);};
struct hpke_params{const struct hpke_kdf*kdf;const struct hpke_aead*aead;const struct hpke_kem*kem;};
struct hpke_ctx{const struct hpke_params*p;unsigned char key[32],nonce[16],exporter[32];uint64_t seq;};
extern int cccurve25519(void*,const void*,const void*);
extern int cccurve25519_make_pub(void*,const void*);
extern int cccurve25519_make_key_pair(struct ccrng_state*,void*,void*);
extern int cchkdf_extract(const struct ccdigest_info*,size_t,const void*,size_t,const void*,void*);
extern int cchkdf_expand(const struct ccdigest_info*,size_t,const void*,size_t,const void*,size_t,void*);
static void wipe(void*p,size_t n){OPENSSL_cleanse(p,n);}
static size_t suite(const struct hpke_params*p,int kem,unsigned char*out){size_t n=kem?3:4;memcpy(out,kem?"KEM":"HPKE",n);out[n++]=p->kem->id>>8;out[n++]=p->kem->id;if(!kem){out[n++]=p->kdf->id>>8;out[n++]=p->kdf->id;out[n++]=p->aead->id>>8;out[n++]=p->aead->id;}return n;}
static int extract(const struct hpke_params*p,int kem,size_t sn,const void*s,const char*label,size_t n,const void*in,void*out){unsigned char id[10];size_t il=suite(p,kem,id),ll=strlen(label);if(n>SIZE_MAX-7-il-ll)return -7;unsigned char*b=malloc(7+il+ll+n);if(!b)return -13;memcpy(b,"HPKE-v1",7);memcpy(b+7,id,il);memcpy(b+7+il,label,ll);if(n)memcpy(b+7+il+ll,in,n);int rc=cchkdf_extract(ccsha256_di(),sn,s,7+il+ll+n,b,out);wipe(b,7+il+ll+n);free(b);return rc;}
static int expand(const struct hpke_params*p,int kem,const void*prk,const char*label,size_t n,const void*in,size_t on,void*out){if(on>65535)return -7;unsigned char id[10];size_t il=suite(p,kem,id),ll=strlen(label);if(n>SIZE_MAX-9-il-ll)return -7;unsigned char*b=malloc(9+il+ll+n);if(!b)return -13;b[0]=on>>8;b[1]=on;memcpy(b+2,"HPKE-v1",7);memcpy(b+9,id,il);memcpy(b+9+il,label,ll);if(n)memcpy(b+9+il+ll,in,n);int rc=cchkdf_expand(ccsha256_di(),32,prk,9+il+ll+n,b,on,out);free(b);return rc;}
static int schedule(struct hpke_ctx*c,const void*secret,size_t n,const void*info){unsigned char context[65]={0},prk[32];int rc=extract(c->p,0,0,NULL,"psk_id_hash",0,NULL,context+1);if(!rc)rc=extract(c->p,0,0,NULL,"info_hash",n,info,context+33);if(!rc)rc=extract(c->p,0,32,secret,"secret",0,NULL,prk);if(!rc)rc=expand(c->p,0,prk,"key",65,context,c->p->aead->key_size,c->key);if(!rc)rc=expand(c->p,0,prk,"base_nonce",65,context,c->p->aead->nonce_size,c->nonce);if(!rc)rc=expand(c->p,0,prk,"exp",65,context,32,c->exporter);wipe(prk,32);return rc;}
static int xgenerate(struct ccrng_state*r,size_t sn,void*sk,size_t pn,void*pk){return sn==32&&pn==32?cccurve25519_make_key_pair(r,pk,sk):-7;}
static int xderive(const struct hpke_params*p,const void*dh,const void*enc,const void*pk,void*out){unsigned char prk[32],ctx[64];memcpy(ctx,enc,32);memcpy(ctx+32,pk,32);int rc=extract(p,1,0,NULL,"eae_prk",32,dh,prk);if(!rc)rc=expand(p,1,prk,"shared_secret",64,ctx,32,out);wipe(prk,32);return rc;}
static int xdet(const struct hpke_params*p,size_t sn,const void*sk,size_t en,const void*ep,size_t pn,const void*pk,size_t zn,void*z,size_t cn,void*ct){if(sn!=32||en!=32||pn!=32||zn!=32||cn!=32)return -7;unsigned char dh[32];int rc=cccurve25519(dh,sk,pk);if(!rc){memcpy(ct,ep,32);rc=xderive(p,dh,ep,pk,z);}wipe(dh,32);return rc;}
static int xencap(const struct hpke_params*p,struct ccrng_state*r,size_t pn,const void*pk,size_t zn,void*z,size_t cn,void*ct){if(pn!=32||zn!=32||cn!=32)return -7;unsigned char sk[32],ep[32];int rc=xgenerate(r,32,sk,32,ep);if(!rc)rc=xdet(p,32,sk,32,ep,pn,pk,zn,z,cn,ct);wipe(sk,32);return rc;}
static int xdecap(const struct hpke_params*p,size_t cn,const void*ct,size_t sn,const void*sk,size_t zn,void*z){if(cn!=32||sn!=32||zn!=32)return -7;unsigned char pk[32],dh[32];int rc=cccurve25519_make_pub(pk,sk);if(!rc)rc=cccurve25519(dh,sk,ct);if(!rc)rc=xderive(p,dh,ct,pk,z);wipe(dh,32);return rc;}
/* X-Wing's private wire key is a 32-byte seed. */
static EVP_PKEY*mlkey(int private_key,const void*data,size_t n){EVP_PKEY_CTX*c=EVP_PKEY_CTX_new_from_name(NULL,"ML-KEM-768",NULL);EVP_PKEY*k=NULL;OSSL_PARAM ps[]={OSSL_PARAM_construct_octet_string(private_key?OSSL_PKEY_PARAM_ML_KEM_SEED:OSSL_PKEY_PARAM_PUB_KEY,(void*)data,n),OSSL_PARAM_construct_end()};if(c&&EVP_PKEY_fromdata_init(c)>0)EVP_PKEY_fromdata(c,&k,private_key?EVP_PKEY_KEYPAIR:EVP_PKEY_PUBLIC_KEY,ps);EVP_PKEY_CTX_free(c);return k;}
static EVP_PKEY*wingkey(const void*seed,unsigned char expanded[96],unsigned char*pk){EVP_MD_CTX*c=EVP_MD_CTX_new();int ok=c&&EVP_DigestInit_ex(c,EVP_shake256(),NULL)&&EVP_DigestUpdate(c,seed,32)&&EVP_DigestFinalXOF(c,expanded,96);EVP_MD_CTX_free(c);if(!ok)return NULL;EVP_PKEY*k=mlkey(1,expanded,64);if(k&&pk){size_t n=1184;if(!EVP_PKEY_get_octet_string_param(k,OSSL_PKEY_PARAM_PUB_KEY,pk,n,&n)||cccurve25519_make_pub(pk+1184,expanded+64)){EVP_PKEY_free(k);k=NULL;}}return k;}
static int combine(const unsigned char*ml,const unsigned char*dh,const void*ct,const void*pk,void*out){unsigned char buf[134];memcpy(buf,ml,32);memcpy(buf+32,dh,32);memcpy(buf+64,ct,32);memcpy(buf+96,pk,32);memcpy(buf+128,"\\.//^\\",6);unsigned n=0;int rc=EVP_Digest(buf,sizeof(buf),out,&n,EVP_sha3_256(),NULL)?0:-1;wipe(buf,sizeof(buf));return rc;}
static int wgenerate(struct ccrng_state*r,size_t sn,void*sk,size_t pn,void*pk){if(sn!=32||pn!=1216)return -7;if(r->generate(r,32,sk))return -1;unsigned char ex[96];EVP_PKEY*k=wingkey(sk,ex,pk);int rc=k?0:-1;EVP_PKEY_free(k);wipe(ex,sizeof(ex));return rc;}
static int wencap(const struct hpke_params*p,struct ccrng_state*r,size_t pn,const void*pk,size_t zn,void*z,size_t cn,void*ct){(void)p;if(pn!=1216||zn!=32||cn!=1120)return -7;unsigned char coins[64],ml[32],dh[32];int rc=r->generate(r,64,coins)?-1:0;EVP_PKEY*k=rc?NULL:mlkey(0,pk,1184);EVP_PKEY_CTX*c=k?EVP_PKEY_CTX_new(k,NULL):NULL;OSSL_PARAM ps[]={OSSL_PARAM_construct_octet_string(OSSL_KEM_PARAM_IKME,coins,32),OSSL_PARAM_construct_end()};size_t ctlen=1088,zlen=32;if(!rc)rc=c&&EVP_PKEY_encapsulate_init(c,ps)>0&&EVP_PKEY_encapsulate(c,ct,&ctlen,ml,&zlen)>0?0:-1;if(!rc)rc=cccurve25519_make_pub((char*)ct+1088,coins+32);if(!rc)rc=cccurve25519(dh,coins+32,(const char*)pk+1184);if(!rc)rc=combine(ml,dh,(char*)ct+1088,(const char*)pk+1184,z);EVP_PKEY_CTX_free(c);EVP_PKEY_free(k);wipe(coins,sizeof(coins));wipe(ml,32);wipe(dh,32);return rc;}
static int wdecap(const struct hpke_params*p,size_t cn,const void*ct,size_t sn,const void*sk,size_t zn,void*z){(void)p;if(cn!=1120||sn!=32||zn!=32)return -7;unsigned char ex[96],pk[1216],ml[32],dh[32];EVP_PKEY*k=wingkey(sk,ex,pk);EVP_PKEY_CTX*c=k?EVP_PKEY_CTX_new(k,NULL):NULL;size_t zlen=32;int rc=c&&EVP_PKEY_decapsulate_init(c,NULL)>0&&EVP_PKEY_decapsulate(c,ml,&zlen,ct,1088)>0?0:-1;if(!rc)rc=cccurve25519(dh,ex+64,(const char*)ct+1088);if(!rc)rc=combine(ml,dh,(const char*)ct+1088,pk+1184,z);EVP_PKEY_CTX_free(c);EVP_PKEY_free(k);wipe(ex,sizeof(ex));wipe(ml,32);wipe(dh,32);return rc;}
static int aes(int enc,size_t kn,const void*k,size_t nn,const void*nonce,size_t an,const void*a,size_t n,const void*in,void*out,size_t tn,void*tag){if((kn!=16&&kn!=32)||nn>INT_MAX||an>INT_MAX||n>INT_MAX||tn>16)return -7;EVP_CIPHER_CTX*c=EVP_CIPHER_CTX_new();int len=0,end=0,ok=c&&EVP_CipherInit_ex(c,kn==16?EVP_aes_128_gcm():EVP_aes_256_gcm(),NULL,NULL,NULL,enc)&&EVP_CIPHER_CTX_ctrl(c,EVP_CTRL_GCM_SET_IVLEN,(int)nn,NULL)&&EVP_CipherInit_ex(c,NULL,NULL,k,nonce,enc);if(ok&&an)ok=EVP_CipherUpdate(c,NULL,&len,a,(int)an);if(ok&&n)ok=EVP_CipherUpdate(c,out,&len,in,(int)n);if(ok&&!enc)ok=EVP_CIPHER_CTX_ctrl(c,EVP_CTRL_GCM_SET_TAG,(int)tn,tag);if(ok)ok=EVP_CipherFinal_ex(c,(unsigned char*)out+n,&end);if(ok&&enc)ok=EVP_CIPHER_CTX_ctrl(c,EVP_CTRL_GCM_GET_TAG,(int)tn,tag);EVP_CIPHER_CTX_free(c);return ok?0:enc?-1:-1;}
static int seal(size_t kn,const void*k,size_t nn,const void*nonce,size_t an,const void*a,size_t n,const void*in,void*out,size_t tn,void*tag){return aes(1,kn,k,nn,nonce,an,a,n,in,out,tn,tag);}
static int open_aead(size_t kn,const void*k,size_t nn,const void*nonce,size_t an,const void*a,size_t n,const void*in,void*out,size_t tn,void*tag){return aes(0,kn,k,nn,nonce,an,a,n,in,out,tn,tag);}
static void hash(size_t n,const void*in,void*out){ccdigest(ccsha256_di(),n,in,out);}
static const struct hpke_kdf kdf={1,32,hash,ccsha256_di};
static const struct hpke_aead a128={1,16,16,12,seal,open_aead},a256={2,32,16,12,seal,open_aead};
static const struct hpke_kem xkem={32,32,32,32,32,32,xgenerate,xencap,xdet,xdecap},wkem={0x647a,1120,32,1216,1216,32,wgenerate,wencap,NULL,wdecap};
static const struct hpke_params p128={&kdf,&a128,&xkem},p256={&kdf,&a256,&xkem},pwing={&kdf,&a128,&wkem};
EXPORT const struct hpke_params*cchpke_params_x25519_AESGCM128_HKDF_SHA256(void){return &p128;}
EXPORT const struct hpke_params*cchpke_params_x25519_AESGCM256_HKDF_SHA256(void){return &p256;}
EXPORT const struct hpke_params*cchpke_params_xwing_AESGCM128_HKDF_SHA256(void){return &pwing;}
#define SIZE(name,field) EXPORT size_t cchpke_params_sizeof_##name(const struct hpke_params*p){return p->field;}
SIZE(kem_enc,kem->enc_size) SIZE(kem_shared_secret,kem->shared_size) SIZE(kem_pk,kem->pk_size) SIZE(kem_pk_marshalled,kem->pk_wire_size) SIZE(kem_sk,kem->sk_size) SIZE(kdf_hash,kdf->hash_size) SIZE(aead_key,aead->key_size) SIZE(aead_tag,aead->tag_size) SIZE(aead_nonce,aead->nonce_size)
EXPORT int cchpke_kem_generate_key_pair(const struct hpke_params*p,struct ccrng_state*r,size_t sn,void*sk,size_t pn,void*pk){return p->kem->generate(r,sn,sk,pn,pk);}
EXPORT int cchpke_initiator_setup(struct hpke_ctx*c,const struct hpke_params*p,struct ccrng_state*r,size_t pn,const void*pk,size_t in,const void*info,size_t en,void*enc){if(in>64||en!=p->kem->enc_size)return -7;memset(c,0,sizeof(*c));c->p=p;unsigned char secret[32];int rc=p->kem->encap(p,r,pn,pk,32,secret,en,enc);if(!rc)rc=schedule(c,secret,in,info);wipe(secret,32);return rc;}
EXPORT int cchpke_responder_setup(struct hpke_ctx*c,const struct hpke_params*p,size_t sn,const void*sk,size_t in,const void*info,size_t en,const void*enc){if(in>64||en!=p->kem->enc_size)return -7;memset(c,0,sizeof(*c));c->p=p;unsigned char secret[32];int rc=p->kem->decap(p,en,enc,sn,sk,32,secret);if(!rc)rc=schedule(c,secret,in,info);wipe(secret,32);return rc;}
static void nonce(const struct hpke_ctx*c,unsigned char*n){memcpy(n,c->nonce,12);for(unsigned i=0;i<8;i++)n[11-i]^=c->seq>>(8*i);}
EXPORT int cchpke_initiator_encrypt(struct hpke_ctx*c,size_t an,const void*a,size_t n,const void*in,void*out,size_t tn,void*tag){unsigned char iv[12];nonce(c,iv);int rc=c->p->aead->seal(c->p->aead->key_size,c->key,12,iv,an,a,n,in,out,tn,tag);if(!rc)c->seq++;return rc;}
EXPORT int cchpke_responder_decrypt(struct hpke_ctx*c,size_t an,const void*a,size_t n,const void*in,size_t tn,const void*tag,void*out){unsigned char iv[12];nonce(c,iv);int rc=c->p->aead->open(c->p->aead->key_size,c->key,12,iv,an,a,n,in,out,tn,(void*)tag);if(!rc)c->seq++;return rc;}
EXPORT int cchpke_initiator_export(const struct hpke_ctx*c,size_t in,const void*info,size_t on,void*out){return in>64?-7:expand(c->p,0,c->exporter,"sec",in,info,on,out);}
EXPORT int cchpke_responder_export(const struct hpke_ctx*c,size_t in,const void*info,size_t on,void*out){return cchpke_initiator_export(c,in,info,on,out);}
EXPORT int cchpke_initiator_seal(const struct hpke_params*p,struct ccrng_state*r,size_t pn,const void*pk,size_t in,const void*info,size_t an,const void*a,size_t n,const void*plain,void*cipher,size_t tn,void*tag,size_t en,void*enc){struct hpke_ctx c;int rc=cchpke_initiator_setup(&c,p,r,pn,pk,in,info,en,enc);if(!rc)rc=cchpke_initiator_encrypt(&c,an,a,n,plain,cipher,tn,tag);wipe(&c,sizeof(c));return rc;}
EXPORT int cchpke_responder_open(const struct hpke_params*p,size_t sn,const void*sk,size_t in,const void*info,size_t an,const void*a,size_t n,const void*cipher,size_t tn,const void*tag,size_t en,const void*enc,void*plain){struct hpke_ctx c;int rc=cchpke_responder_setup(&c,p,sn,sk,in,info,en,enc);if(!rc)rc=cchpke_responder_decrypt(&c,an,a,n,cipher,tn,tag,plain);wipe(&c,sizeof(c));return rc;}
