/* SPDX-License-Identifier: MIT OR Apache-2.0
 * SPAKE2+ with the RFC and earlier transcript formats used by the host ABI.
 */
#include "ccspake.h"
#include <openssl/bn.h>
#include <openssl/ec.h>
#include <openssl/obj_mac.h>
#include <openssl/crypto.h>
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
#define API __attribute__((visibility("default")))
extern int cchkdf(const struct ccdigest_info*,size_t,const void*,size_t,const void*,size_t,const void*,size_t,void*);
extern void cchmac(const struct ccdigest_info*,size_t,const void*,size_t,const void*,void*);
extern int cccmac_one_shot_generate(const struct ccmode_cbc*,size_t,const void*,size_t,const void*,size_t,void*);
extern const struct ccmode_cbc *ccaes_cbc_encrypt_mode(void);
static size_t limbs(const struct ccspake_cp*cp){return cp->curve()->n;}
static size_t field_bytes(const struct ccspake_cp*cp){return (cp->curve()->bitlen+7)/8;}
static EC_GROUP *group(const struct ccspake_cp*cp){size_t b=cp->curve()->bitlen;return EC_GROUP_new_by_curve_name(b==256?NID_X9_62_prime256v1:b==384?NID_secp384r1:b==521?NID_secp521r1:NID_undef);}
static cc_unit *part(const struct ccspake_ctx*s,unsigned i){return (cc_unit*)s->data+i*limbs(s->cp);}
API size_t ccspake_sizeof_w(const struct ccspake_cp*cp){return field_bytes(cp)+(cp->variant?0:8);}
API size_t ccspake_sizeof_point(const struct ccspake_cp*cp){return 1+2*field_bytes(cp);}
API size_t ccspake_sizeof_ctx(const struct ccspake_cp*cp){return 336+64*limbs(cp);}
static BIGNUM *read_scalar(const struct ccspake_cp*cp,const cc_unit*x){return BN_lebin2bn((void*)x,(int)limbs(cp)*8,NULL);}
static int save_scalar(const struct ccspake_cp*cp,const BIGNUM*x,cc_unit*out){return BN_bn2lebinpad(x,(void*)out,(int)limbs(cp)*8)<0?-7:0;}
static EC_POINT *read_point(const struct ccspake_cp*cp,const EC_GROUP*g,const cc_unit*xy,BN_CTX*c){size_t n=limbs(cp);BIGNUM*x=read_scalar(cp,xy),*y=read_scalar(cp,xy+n);EC_POINT*p=EC_POINT_new(g);if(!x||!y||!p||!EC_POINT_set_affine_coordinates(g,p,x,y,c)){EC_POINT_free(p);p=NULL;}BN_free(x);BN_free(y);return p;}
static int save_point(const struct ccspake_cp*cp,const EC_GROUP*g,const EC_POINT*p,cc_unit*xy,BN_CTX*c){BIGNUM*x=BN_new(),*y=BN_new();int ret=-13;if(x&&y&&EC_POINT_get_affine_coordinates(g,p,x,y,c)){ret=save_scalar(cp,x,xy);if(!ret)ret=save_scalar(cp,y,xy+limbs(cp));}BN_clear_free(x);BN_clear_free(y);return ret;}
static int import_point(const struct ccspake_cp*cp,const EC_GROUP*g,size_t n,const void*in,EC_POINT*p,BN_CTX*c){if(n!=ccspake_sizeof_point(cp)||!in||*(const unsigned char*)in!=4)return -7;if(!EC_POINT_oct2point(g,p,in,n,c)||!EC_POINT_is_on_curve(g,p,c)||EC_POINT_is_at_infinity(g,p))return -7;return 0;}
static int scalar_from_bytes(const struct ccspake_cp*cp,size_t n,const void*in,int reduce,BIGNUM*out,BN_CTX*c){EC_GROUP*g=group(cp);BIGNUM*q=g?BN_dup(EC_GROUP_get0_order(g)):NULL;int ret=-13;if(!g||!q)goto done;if(reduce==1&&n>128){ret=-7;goto done;}if(!BN_bin2bn(in,(int)n,out))goto done;if(reduce==1){BN_sub_word(q,1);if(!BN_nnmod(out,out,q,c)||!BN_add_word(out,1))goto done;}else if(reduce==2){if(!BN_nnmod(out,out,q,c))goto done;if(BN_is_zero(out)){ret=-7;goto done;}}ret=0;done:BN_free(q);EC_GROUP_free(g);return ret;}
static int reduce(const struct ccspake_cp*cp,size_t n,const void*in,size_t on,void*out,int rfc){if(!cp->variant||on!=ccspake_sizeof_w(cp)||n<on+8)return -7;BN_CTX*c=BN_CTX_new();BIGNUM*x=BN_new();int ret=-13;if(c&&x){if(rfc&&n>limbs(cp)*16){const unsigned char*p=in;size_t skip=n-limbs(cp)*16;for(size_t i=0;i<skip;i++)if(p[i]){ret=-1;goto done;}in=p+skip;n-=skip;}ret=scalar_from_bytes(cp,n,in,rfc?2:1,x,c);if(!ret&&BN_bn2binpad(x,out,(int)on)<0)ret=-7;}done:BN_clear_free(x);BN_CTX_free(c);return ret;}
API int ccspake_reduce_w(const struct ccspake_cp*cp,size_t n,const void*in,size_t on,void*out){return reduce(cp,n,in,on,out,0);}
API int ccspake_reduce_w_RFC9383(const struct ccspake_cp*cp,size_t n,const void*in,size_t on,void*out){return reduce(cp,n,in,on,out,1);}
/* Add a fresh multiple of the group order before each private multiplication. */
static int multiply(const EC_GROUP*g,EC_POINT*out,const EC_POINT*p,const BIGNUM*x,struct ccrng_state*r,BN_CTX*c){unsigned char bytes[32];int ret=r->generate(r,sizeof bytes,bytes);if(ret)return ret;BIGNUM*b=BN_bin2bn(bytes,sizeof bytes,NULL),*e=BN_new();OPENSSL_cleanse(bytes,sizeof bytes);if(!b||!e){BN_free(b);BN_free(e);return -13;}int ok=BN_mul(e,b,EC_GROUP_get0_order(g),c)&&BN_add(e,e,x);BN_set_flags(e,BN_FLG_CONSTTIME);if(ok)ok=p?EC_POINT_mul(g,out,NULL,p,e,c):EC_POINT_mul(g,out,e,NULL,NULL,c);BN_clear_free(b);BN_clear_free(e);return ok?0:-7;}
API int ccspake_generate_L(const struct ccspake_cp*cp,size_t wn,const void*w,size_t ln,void*l,struct ccrng_state*r){if(wn!=ccspake_sizeof_w(cp)||ln!=ccspake_sizeof_point(cp))return -7;BN_CTX*c=BN_CTX_new();EC_GROUP*g=group(cp);EC_POINT*p=g?EC_POINT_new(g):NULL;BIGNUM*x=BN_new();int ret=-13;if(!c||!g||!p||!x)goto done;ret=scalar_from_bytes(cp,wn,w,cp->variant?0:1,x,c);if(ret)goto done;if(BN_is_zero(x)||BN_cmp(x,EC_GROUP_get0_order(g))>=0){ret=-22;goto done;}ret=multiply(g,p,NULL,x,r,c);if(!ret&&EC_POINT_point2oct(g,p,POINT_CONVERSION_UNCOMPRESSED,l,ln,c)!=ln)ret=-7;done:BN_CTX_free(c);EC_GROUP_free(g);EC_POINT_free(p);BN_clear_free(x);return ret;}
static void transcript_append(struct ccspake_ctx*s,size_t n,const void*p){const struct ccdigest_info*d=s->mac->digest();uint64_t length=n;ccdigest_update(d,s->digest,8,&length);if(n)ccdigest_update(d,s->digest,n,p);}
static void transcript_point(struct ccspake_ctx*s,const cc_unit*xy){size_t n=field_bytes(s->cp);unsigned char b[133];b[0]=4;ccn_write_uint_padded_ct(limbs(s->cp),xy,n,b+1);ccn_write_uint_padded_ct(limbs(s->cp),xy+limbs(s->cp),n,b+1+n);transcript_append(s,2*n+1,b);}
static void transcript_begin(struct ccspake_ctx*s,size_t cn,const void*ctx,size_t pn,const void*prover,size_t vn,const void*verifier){transcript_append(s,cn,ctx);transcript_append(s,pn,prover);transcript_append(s,vn,verifier);transcript_point(s,s->cp->m);transcript_point(s,s->cp->n);}
static int init(struct ccspake_ctx*s,const struct ccspake_cp*cp,const struct ccspake_mac*mac,struct ccrng_state*r,int prover,size_t cn,const void*ctx,size_t wn,const void*w0,const void*w1,size_t ln,const void*l){memset(s,0,ccspake_sizeof_ctx(cp));if(wn!=ccspake_sizeof_w(cp)||(!cp->variant&&cn>20)||(!prover&&ln!=ccspake_sizeof_point(cp)))return -7;s->cp=cp;s->mac=mac;s->rng=r;s->prover=prover;s->state=1;if(!cp->variant){s->context_size=cn;if(cn)memcpy(s->context,ctx,cn);}BN_CTX*c=BN_CTX_new();BIGNUM*x=BN_new();EC_GROUP*g=group(cp);EC_POINT*p=g?EC_POINT_new(g):NULL;int ret=-13;if(!c||!x||!g||!p)goto done;ret=scalar_from_bytes(cp,wn,w0,cp->variant?0:1,x,c);if(ret)goto done;save_scalar(cp,x,part(s,0));if(prover){ret=scalar_from_bytes(cp,wn,w1,cp->variant?0:1,x,c);if(ret)goto done;save_scalar(cp,x,part(s,1));}else{ret=import_point(cp,g,ln,l,p,c);if(ret)goto done;ret=save_point(cp,g,p,part(s,1),c);if(ret)goto done;}ccdigest_init(mac->digest(),s->digest);done:BN_CTX_free(c);BN_clear_free(x);EC_POINT_free(p);EC_GROUP_free(g);return ret;}
API int ccspake_prover_init(struct ccspake_ctx*s,const struct ccspake_cp*cp,const struct ccspake_mac*m,struct ccrng_state*r,size_t cn,const void*ctx,size_t wn,const void*w0,const void*w1){if(cp->variant){memset(s,0,ccspake_sizeof_ctx(cp));return -7;}return init(s,cp,m,r,1,cn,ctx,wn,w0,w1,0,NULL);}
API int ccspake_verifier_init(struct ccspake_ctx*s,const struct ccspake_cp*cp,const struct ccspake_mac*m,struct ccrng_state*r,size_t cn,const void*ctx,size_t wn,const void*w0,size_t ln,const void*l){if(cp->variant){memset(s,0,ccspake_sizeof_ctx(cp));return -7;}return init(s,cp,m,r,0,cn,ctx,wn,w0,NULL,ln,l);}
API int ccspake_prover_initialize(struct ccspake_ctx*s,const struct ccspake_cp*cp,const struct ccspake_mac*m,struct ccrng_state*r,size_t cn,const void*ctx,size_t pn,const void*p,size_t vn,const void*v,size_t wn,const void*w0,const void*w1){if(!cp->variant){if(pn||vn)return -7;return ccspake_prover_init(s,cp,m,r,cn,ctx,wn,w0,w1);}if(!cn||wn!=ccspake_sizeof_w(cp))return -7;int ret=init(s,cp,m,r,1,cn,ctx,wn,w0,w1,0,NULL);if(!ret)transcript_begin(s,cn,ctx,pn,p,vn,v);return ret;}
API int ccspake_verifier_initialize(struct ccspake_ctx*s,const struct ccspake_cp*cp,const struct ccspake_mac*m,struct ccrng_state*r,size_t cn,const void*ctx,size_t pn,const void*p,size_t vn,const void*v,size_t wn,const void*w0,size_t ln,const void*l){if(!cp->variant){if(pn||vn)return -7;return ccspake_verifier_init(s,cp,m,r,cn,ctx,wn,w0,ln,l);}if(!cn||wn!=ccspake_sizeof_w(cp)||ln!=ccspake_sizeof_point(cp))return -7;int ret=init(s,cp,m,r,0,cn,ctx,wn,w0,NULL,ln,l);if(!ret)transcript_begin(s,cn,ctx,pn,p,vn,v);return ret;}
static int lazy_generate(struct ccspake_ctx*s){if(ccn_bitlen(limbs(s->cp),part(s,3)))return 0;BN_CTX*c=BN_CTX_new();EC_GROUP*g=group(s->cp);BIGNUM*x=BN_new(),*w0=read_scalar(s->cp,part(s,0)),*qm=g?BN_dup(EC_GROUP_get0_order(g)):NULL;EC_POINT*p=g?EC_POINT_new(g):NULL,*mask=g?read_point(s->cp,g,s->prover?s->cp->m:s->cp->n,c):NULL;int ret=-13;unsigned char random[72];if(!c||!g||!x||!w0||!qm||!p||!mask)goto done;BN_sub_word(qm,1);size_t n=limbs(s->cp)*8,bits=(size_t)BN_num_bits(qm);for(unsigned tries=0;tries<100;tries++){ret=s->rng->generate(s->rng,n,random);if(ret)goto done;BN_lebin2bn(random,(int)n,x);BN_mask_bits(x,(int)bits);if(BN_cmp(x,qm)<0){BN_add_word(x,1);ret=0;break;}ret=-15;}if(ret)goto done;ret=multiply(g,p,NULL,x,s->rng,c);if(ret)goto done;ret=multiply(g,mask,mask,w0,s->rng,c);if(ret)goto done;if(!EC_POINT_add(g,p,p,mask,c)){ret=-7;goto done;}ret=save_point(s->cp,g,p,part(s,4),c);if(!ret)ret=save_scalar(s->cp,x,part(s,3));done:OPENSSL_cleanse(random,sizeof random);BN_CTX_free(c);EC_GROUP_free(g);EC_POINT_free(p);EC_POINT_free(mask);BN_clear_free(x);BN_clear_free(w0);BN_free(qm);return ret;}
API int ccspake_kex_generate(struct ccspake_ctx*s,size_t n,void*out){if(s->state!=1&&s->state!=5)return -86;if(n!=ccspake_sizeof_point(s->cp))return -7;int ret=lazy_generate(s);if(ret)return ret;unsigned char*b=out;size_t z=field_bytes(s->cp);b[0]=4;ccn_write_uint_padded_ct(limbs(s->cp),part(s,4),z,b+1);ccn_write_uint_padded_ct(limbs(s->cp),part(s,5),z,b+1+z);s->state|=3;return 0;}
API int ccspake_kex_process(struct ccspake_ctx*s,size_t n,const void*in){if(n!=ccspake_sizeof_point(s->cp))return -7;if(s->state!=1&&s->state!=3)return -86;BN_CTX*c=BN_CTX_new();EC_GROUP*g=group(s->cp);EC_POINT*peer=g?EC_POINT_new(g):NULL,*mask=NULL,*z=g?EC_POINT_new(g):NULL,*v=g?EC_POINT_new(g):NULL;BIGNUM*x=NULL,*w0=NULL,*w1=NULL;int ret=-13;cc_unit tmp[36];if(!c||!g||!peer||!z||!v)goto done;ret=import_point(s->cp,g,n,in,peer,c);if(ret)goto done;ret=lazy_generate(s);if(ret)goto done;ret=save_point(s->cp,g,peer,tmp,c);if(ret)goto done;if(!CRYPTO_memcmp(tmp,part(s,4),16*limbs(s->cp))){ret=-7;goto done;}mask=read_point(s->cp,g,s->prover?s->cp->n:s->cp->m,c);x=read_scalar(s->cp,part(s,3));w0=read_scalar(s->cp,part(s,0));if(!mask||!x||!w0){ret=-13;goto done;}ret=multiply(g,mask,mask,w0,s->rng,c);if(ret)goto done;EC_POINT_invert(g,mask,c);EC_POINT_add(g,mask,peer,mask,c);ret=multiply(g,z,mask,x,s->rng,c);if(ret)goto done;if(s->prover){w1=read_scalar(s->cp,part(s,1));if(!w1){ret=-13;goto done;}ret=multiply(g,v,mask,w1,s->rng,c);}else{EC_POINT*l=read_point(s->cp,g,part(s,1),c);if(!l){ret=-1;goto done;}ret=multiply(g,v,l,x,s->rng,c);EC_POINT_free(l);}if(ret)goto done;memcpy(part(s,6),tmp,16*limbs(s->cp));transcript_point(s,part(s,s->prover?4:6));transcript_point(s,part(s,s->prover?6:4));ret=save_point(s->cp,g,z,tmp,c);if(ret)goto done;transcript_point(s,tmp);ret=save_point(s->cp,g,v,tmp,c);if(ret)goto done;transcript_point(s,tmp);unsigned char wb[66];size_t wn=field_bytes(s->cp);ccn_write_uint_padded_ct(limbs(s->cp),part(s,0),wn,wb);transcript_append(s,wn,wb);const struct ccdigest_info*d=s->mac->digest();d->final(d,s->digest,s->secret);OPENSSL_cleanse(s->digest,ccdigest_di_size(d));s->state|=5;ret=0;done:BN_CTX_free(c);EC_GROUP_free(g);EC_POINT_free(peer);EC_POINT_free(mask);EC_POINT_free(z);EC_POINT_free(v);BN_clear_free(x);BN_clear_free(w0);BN_clear_free(w1);OPENSSL_cleanse(tmp,sizeof tmp);return ret;}
static int derive(const struct ccspake_ctx*s,size_t n,const void*in,void*out){unsigned char info[36]="ConfirmationKeys";size_t size=16;if(!s->cp->variant&&s->context_size){memcpy(info+16,s->context,s->context_size);size+=s->context_size;}return cchkdf(s->mac->digest(),n,in,0,NULL,size,info,2*s->mac->key_size,out);}
static int mac_hmac(const struct ccspake_ctx*s,size_t kn,const void*k,size_t n,const void*in,size_t on,void*out){if(on!=s->mac->tag_size)return -7;cchmac(s->mac->digest(),kn,k,n,in,out);return 0;}
static int mac_cmac(const struct ccspake_ctx*s,size_t kn,const void*k,size_t n,const void*in,size_t on,void*out){if(on!=s->mac->tag_size)return -7;return cccmac_one_shot_generate(s->mac->cbc(),kn,k,n,in,on,out);}
static const struct ccspake_mac mac256={ccsha256_di,NULL,32,32,derive,mac_hmac},mac512={ccsha512_di,NULL,64,64,derive,mac_hmac},macaes={ccsha256_di,ccaes_cbc_encrypt_mode,16,16,derive,mac_cmac};
API const struct ccspake_mac*ccspake_mac_hkdf_hmac_sha256(void){return &mac256;}
API const struct ccspake_mac*ccspake_mac_hkdf_hmac_sha512(void){return &mac512;}
API const struct ccspake_mac*ccspake_mac_hkdf_cmac_aes128_sha256(void){return &macaes;}
static int confirmation(const struct ccspake_ctx*s,int prover,unsigned point,size_t n,void*out){const struct ccdigest_info*d=s->mac->digest();size_t input_n=s->cp->variant?d->output_size:d->output_size/2;unsigned char keys[128],bytes[133];int ret=s->mac->derive(s,input_n,s->secret,keys);if(ret)return ret;size_t kn=s->cp->variant?s->mac->key_size:d->output_size/2,offset=(prover^(s->cp->variant!=0))?kn:0;size_t f=field_bytes(s->cp);bytes[0]=4;ccn_write_uint_padded_ct(limbs(s->cp),part(s,point),f,bytes+1);ccn_write_uint_padded_ct(limbs(s->cp),part(s,point+1),f,bytes+1+f);ret=s->mac->compute(s,kn,keys+offset,2*f+1,bytes,n,out);OPENSSL_cleanse(keys,sizeof keys);return ret;}
static int session(const struct ccspake_ctx*s,size_t n,void*out){const struct ccdigest_info*d=s->mac->digest();if(!s->cp->variant){if(n!=d->output_size/2)return -7;memcpy(out,s->secret+n,n);return 0;}if(!n)return -7;return cchkdf(d,d->output_size,s->secret,0,NULL,9,"SharedKey",n,out);}
API int ccspake_mac_compute(struct ccspake_ctx*s,size_t n,void*out){if(s->state!=7&&s->state!=23)return -86;int ret=confirmation(s,s->prover,6,n,out);if(!ret)s->state|=15;return ret;}
API int ccspake_get_session_key(struct ccspake_ctx*s,size_t n,void*out){if(s->state!=7&&s->state!=15)return -86;return session(s,n,out);}
API int ccspake_mac_verify_and_get_session_key(struct ccspake_ctx*s,size_t mn,const void*mac,size_t kn,void*out){if(s->state!=7&&s->state!=15)return -86;if(mn>64||(!s->cp->variant&&kn!=s->mac->digest()->output_size/2)||(s->cp->variant==1&&!kn))return -7;unsigned char expected[64];int ret=confirmation(s,!s->prover,4,mn,expected);if(!ret&&CRYPTO_memcmp(expected,mac,mn))ret=-2;if(!ret)ret=session(s,kn,out);if(!ret)s->state|=23;OPENSSL_cleanse(expected,sizeof expected);return ret;}

/* Public SPAKE2+ points from RFC 9383, confirmed against host accessors. */
static cc_unit points[3][36];static pthread_once_t points_once=PTHREAD_ONCE_INIT;
static void init_points(void){BIGNUM*x=NULL;
BN_hex2bn(&x,"886e2f97ace46e55ba9dd7242579f2993b64e16ef3dcab95afd497333d8fa12f");BN_bn2lebinpad(x,(void*)(points[0]+0),32);
BN_hex2bn(&x,"5ff355163e43ce224e0b0e65ff02ac8e5c7be09419c785e0ca547d55a12e2d20");BN_bn2lebinpad(x,(void*)(points[0]+4),32);
BN_hex2bn(&x,"d8bbd6c639c62937b04d997f38c3770719c629d7014d49a24b4f98baa1292b49");BN_bn2lebinpad(x,(void*)(points[0]+8),32);
BN_hex2bn(&x,"07d60aa6bfade45008a636337f5168c64d9bd36034808cd564490b1e656edbe7");BN_bn2lebinpad(x,(void*)(points[0]+12),32);
BN_hex2bn(&x,"0ff0895ae5ebf6187080a82d82b42e2765e3b2f8749c7e05eba366434b363d3dc36f15314739074d2eb8613fceec2853");BN_bn2lebinpad(x,(void*)(points[1]+0),48);
BN_hex2bn(&x,"97592c55797cdd77c0715cb7df2150220a0119866486af4234f390aad1f6addde5930909adc67a1fc0c99ba3d52dc5dd");BN_bn2lebinpad(x,(void*)(points[1]+6),48);
BN_hex2bn(&x,"c72cf2e390853a1c1c4ad816a62fd15824f56078918f43f922ca21518f9c543bb252c5490214cf9aa3f0baab4b665c10");BN_bn2lebinpad(x,(void*)(points[1]+12),48);
BN_hex2bn(&x,"c38b7d7f4e7f320317cd717315a797c7e02933aef68b364cbf84ebc619bedbe21ff5c69ea0f1fed5d7e3200418073f40");BN_bn2lebinpad(x,(void*)(points[1]+18),48);
BN_hex2bn(&x,"000000000000003f06f38131b2ba2600791e82488e8d20ab889af753a41806c5db18d37d85608cfae06b82e4a72cd744c719193562a653ea1f119eef9356907edc9b56979962d7aa");BN_bn2lebinpad(x,(void*)(points[2]+0),72);
BN_hex2bn(&x,"00000000000001bdd179a3d547610892e9b96dea1eab10bdd7ac5ae0cf75aa0f853bfd185cf782f894301998b11d1898ede2701dca37a2bb50b4f519c3d89a7d054b51fb84912192");BN_bn2lebinpad(x,(void*)(points[2]+9),72);
BN_hex2bn(&x,"00000000000000c7924b9ec017f3094562894336a53c50167ba8c5963876880542bc669e494b2532d76c5b53dfb349fdf69154b9e0048c58a42e8ed04cef052a3bc349d95575cd25");BN_bn2lebinpad(x,(void*)(points[2]+18),72);
BN_hex2bn(&x,"00000000000001c62bee650c9287a651bb75c7f39a2006873347b769840d261d17760b107e29f091d556a82a2e4cde0c40b84b95b878db2489ef760206424b3fe7968aa8e0b1f334");BN_bn2lebinpad(x,(void*)(points[2]+27),72);
BN_free(x);}
static const struct ccspake_cp cp256={0,0,ccec_cp_256,points[0],points[0]+8};
API const struct ccspake_cp*ccspake_cp_256(void){pthread_once(&points_once,init_points);return &cp256;}
static const struct ccspake_cp cp256_rfc={1,0,ccec_cp_256,points[0],points[0]+8};
API const struct ccspake_cp*ccspake_cp_256_rfc(void){pthread_once(&points_once,init_points);return &cp256_rfc;}
static const struct ccspake_cp cp384={0,0,ccec_cp_384,points[1],points[1]+12};
API const struct ccspake_cp*ccspake_cp_384(void){pthread_once(&points_once,init_points);return &cp384;}
static const struct ccspake_cp cp384_rfc={1,0,ccec_cp_384,points[1],points[1]+12};
API const struct ccspake_cp*ccspake_cp_384_rfc(void){pthread_once(&points_once,init_points);return &cp384_rfc;}
static const struct ccspake_cp cp521={0,0,ccec_cp_521,points[2],points[2]+18};
API const struct ccspake_cp*ccspake_cp_521(void){pthread_once(&points_once,init_points);return &cp521;}
static const struct ccspake_cp cp521_rfc={1,0,ccec_cp_521,points[2],points[2]+18};
API const struct ccspake_cp*ccspake_cp_521_rfc(void){pthread_once(&points_once,init_points);return &cp521_rfc;}
