#!/bin/bash
# SPDX-License-Identifier: MIT OR Apache-2.0
# SystemConfiguration.framework (docs/design/SECURITY.md), without configd:
# Finch's dynamic store, preferences, reachability and network configuration
# (the .c files here), with what builds from Apple's configd (pinned in
# userland/projects.txt):
#   - the schema constants, generated by configd's genSCPreferences
#   - the other public constants, with configd's values (gen-constants.py)
#   - SCDKeys.c (store keys), SCDConsoleUser.c and SCLocation.c, over Finch's store
#
# Linked as Apple ships it: install name, current version 1405.100.8.
#   FINCH_OUTPUT_ROOT / FINCH_OBJ_DIR override build/root and build/obj/SystemConfiguration.
#
#   userland/SystemConfiguration/build.sh -> build/root/System/Library/Frameworks/SystemConfiguration.framework
set -euo pipefail
FINCH_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
HERE="$FINCH_ROOT/userland/SystemConfiguration"
CONFIGD="$FINCH_ROOT/build/src/configd/SystemConfiguration.fproj"
OBJ="${FINCH_OBJ_DIR:-$FINCH_ROOT/build/obj/SystemConfiguration}"
ROOT="${FINCH_OUTPUT_ROOT:-$FINCH_ROOT/build/root}"
FW="$ROOT/System/Library/Frameworks/SystemConfiguration.framework"
SDK="$FINCH_ROOT/build/sdk"
SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
SDKH="$SDKROOT/System/Library/Frameworks/SystemConfiguration.framework/Headers"
CC="$(xcrun -f clang)"
log() { echo "==> $*"; }

[[ -d "$CONFIGD" ]] || { echo "missing configd (tools/fetch-src.sh configd)" >&2; exit 1; }
[[ -f "$FINCH_ROOT/build/root/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation" ]] \
    || { echo "build CoreFoundation first (userland/CoreFoundation/build.sh)" >&2; exit 1; }

log "generating constants"
rm -rf "$OBJ" && mkdir -p "$OBJ/hdr/CoreFoundation" "$OBJ/hdr/SystemConfiguration" "$OBJ/o"
sed -E 's/#include "(CF[^"]+)"/#include <CoreFoundation\/\1>/' \
    "$FINCH_ROOT/build/src/swift-corelibs-foundation/Sources/CoreFoundation/include/CFRuntime.h" > "$OBJ/hdr/CoreFoundation/CFRuntime.h"
# configd's own sources see the SDK's public headers, then its private ones.
rsync -a "$SDKH/" "$OBJ/hdr/SystemConfiguration/"
rsync -a --ignore-existing --include='*.h' --exclude='*' "$CONFIGD/" "$OBJ/hdr/SystemConfiguration/"
"$CC" -isysroot "$SDKROOT" "$CONFIGD/genSCPreferences.c" -o "$OBJ/genSCPreferences"
"$OBJ/genSCPreferences" cfile > "$OBJ/SCSchemaDefinitions.c"
python3 "$HERE/gen-constants.py" "$CONFIGD" "$OBJ/hdr/SystemConfiguration" "$OBJ/SCSchemaDefinitions.c" "$OBJ/SCConstants.c" \
    "$CONFIGD/SCDKeys.c" "$CONFIGD/SCDConsoleUser.c" "$CONFIGD/SCLocation.c"

FINCH_CFLAGS=(-arch arm64e -mmacosx-version-min=26.0 -isysroot "$SDKROOT" -Os -g -fblocks -fno-common
    -Wall -Wextra -Werror -Wno-unused-parameter -Wno-deprecated-declarations -Wno-nonnull
    -I"$HERE" -I"$OBJ/hdr/CoreFoundation/.." )
# configd's files, as Apple builds them: private headers, Finch's SDK overlay.
CONFIGD_CFLAGS=(-arch arm64e -mmacosx-version-min=26.0 -isysroot "$SDKROOT" -Os -g -fblocks -fno-common
    -I"$OBJ/hdr" -I"$SDK/include" -idirafter "$SDK/override" -idirafter "$SDK/availability" -F"$SDK/Frameworks"
    -Wno-deprecated-declarations)

log "compiling"
objects=()
for source in "$HERE"/*.c; do
    output="$OBJ/o/$(basename "${source%.c}").o"
    "$CC" "${FINCH_CFLAGS[@]}" -c "$source" -o "$output"
    objects+=("$output")
done
for source in "$OBJ/SCSchemaDefinitions.c" "$OBJ/SCConstants.c" "$CONFIGD/SCDKeys.c" "$CONFIGD/SCDConsoleUser.c" "$CONFIGD/SCLocation.c"; do
    output="$OBJ/o/$(basename "${source%.c}").o"
    "$CC" "${CONFIGD_CFLAGS[@]}" -c "$source" -o "$output"
    objects+=("$output")
done

log "linking"
mkdir -p "$FW/Versions/A"
"$CC" -arch arm64e -mmacosx-version-min=26.0 -isysroot "$SDKROOT" -dynamiclib \
    -install_name /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration \
    -current_version 1405.100.8 -compatibility_version 1 \
    "${objects[@]}" -F"$FINCH_ROOT/build/root/System/Library/Frameworks" -framework CoreFoundation \
    -Wl,-exported_symbols_list,"$HERE/exports.txt" \
    -o "$FW/Versions/A/SystemConfiguration"
ln -sfn A "$FW/Versions/Current"
ln -sfn Versions/Current/SystemConfiguration "$FW/SystemConfiguration"
"$FINCH_ROOT/tools/mkframeworkplist.sh" "$FW" A SystemConfiguration com.apple.SystemConfiguration SystemConfiguration 1.21 1.21 English
codesign -f -s - -i com.apple.SystemConfiguration "$FW/Versions/A/SystemConfiguration" 2>/dev/null
python3 "$FINCH_ROOT/tools/collect-notices.py" \
    'Apple configd-1405.100.8, in SystemConfiguration.framework' \
    "$ROOT/usr/share/finch/licenses/SystemConfiguration/configd-NOTICES.txt" \
    "$CONFIGD/SCDKeys.c" "$CONFIGD/SCDConsoleUser.c" "$CONFIGD/SCLocation.c" "$CONFIGD/genSCPreferences.c" > /dev/null
log "installed ${FW#"$FINCH_ROOT/"}"
