#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""SystemConfiguration's public constants outside the schema, from configd.

    gen-constants.py <configd SystemConfiguration.fproj> <headers> <schema .c> <out.c> [built .c ...]

The schema constants (kSCProp..., kSCEnt..., ...) come from configd's
genSCPreferences (SCSchemaDefinitions.c). The others the SDK's headers declare
(kSCNetworkInterfaceType..., kSCNetworkProtocolType..., kSCBondStatus...) get
the values configd's sources define them with. Constants defined by the
configd files built into the framework (the trailing arguments) are left to them.
"""
import os
import re
import sys

src, hdrs, schema, out = sys.argv[1:5]
declared = set()
for name in os.listdir(hdrs):
    if name.endswith(".h"):
        text = open(os.path.join(hdrs, name), encoding="utf-8", errors="replace").read()
        declared |= set(re.findall(r"\bextern\s+const\s+CFStringRef\s+(?:_Nonnull\s+)?(k\w+)", text))
have = set(re.findall(r"const CFStringRef\s+(k\w+)", open(schema).read()))
for built in sys.argv[5:]:
    have |= set(re.findall(r"const\s+CFStringRef\s+(k\w+)\s*=", open(built, encoding="utf-8", errors="replace").read()))
values = {}
for name in sorted(os.listdir(src)):
    if name.endswith(".c"):
        text = open(os.path.join(src, name), encoding="utf-8", errors="replace").read()
        for k, v in re.findall(r'const\s+CFStringRef\s+(k\w+)\s*=\s*CFSTR\(\s*"((?:[^"\\]|\\.)*)"\s*\)', text):
            values.setdefault(k, v)
lines = ["/* Generated by userland/SystemConfiguration/gen-constants.py from configd. */",
         "#include <CoreFoundation/CoreFoundation.h>", ""]
missing = []
for k in sorted(declared - have):
    if k in values:
        lines.append('const CFStringRef %s = CFSTR("%s");' % (k, values[k]))
    else:
        missing.append(k)
lines.append("/* Declared, not defined by a CFSTR in configd's sources: %s */" % (" ".join(missing) or "none"))
open(out, "w").write("\n".join(lines) + "\n")
print("%d constants; %d without a CFSTR definition: %s" % (len(declared - have) - len(missing), len(missing), " ".join(missing)))
