/* SPDX-License-Identifier: MIT OR Apache-2.0 */
/* Generated from Finch implementations by tools/update-commoncrypto-decls.py. */
void cc_clear(size_t, void *);
int cc_cmp_safe(size_t, const void *, const void *);
const struct ccmode_cbc *ccaes_cbc_decrypt_mode(void);
const struct ccmode_cbc *ccaes_cbc_encrypt_mode(void);
const struct ccmode_ccm *ccaes_ccm_decrypt_mode(void);
const struct ccmode_ccm *ccaes_ccm_encrypt_mode(void);
const struct ccmode_stream *ccaes_cfb8_decrypt_mode(void);
const struct ccmode_stream *ccaes_cfb8_encrypt_mode(void);
const struct ccmode_stream *ccaes_cfb_decrypt_mode(void);
const struct ccmode_stream *ccaes_cfb_encrypt_mode(void);
const struct ccmode_ctr *ccaes_ctr_crypt_mode(void);
const struct ccmode_ecb *ccaes_ecb_decrypt_mode(void);
const struct ccmode_ecb *ccaes_ecb_encrypt_mode(void);
const struct ccmode_gcm *ccaes_gcm_decrypt_mode(void);
const struct ccmode_gcm *ccaes_gcm_encrypt_mode(void);
const struct ccmode_stream *ccaes_ofb_crypt_mode(void);
const struct ccmode_xts *ccaes_xts_decrypt_mode(void);
const struct ccmode_xts *ccaes_xts_encrypt_mode(void);
int ccansikdf_x963(const struct ccdigest_info *, size_t, const void *, size_t, const void *, size_t, void *);
const struct ccmode_cbc *ccblowfish_cbc_decrypt_mode(void);
const struct ccmode_cbc *ccblowfish_cbc_encrypt_mode(void);
const struct ccmode_stream *ccblowfish_cfb8_decrypt_mode(void);
const struct ccmode_stream *ccblowfish_cfb8_encrypt_mode(void);
const struct ccmode_stream *ccblowfish_cfb_decrypt_mode(void);
const struct ccmode_stream *ccblowfish_cfb_encrypt_mode(void);
const struct ccmode_ctr *ccblowfish_ctr_crypt_mode(void);
const struct ccmode_ecb *ccblowfish_ecb_decrypt_mode(void);
const struct ccmode_ecb *ccblowfish_ecb_encrypt_mode(void);
const struct ccmode_stream *ccblowfish_ofb_crypt_mode(void);
const struct ccmode_cbc *cccast_cbc_decrypt_mode(void);
const struct ccmode_cbc *cccast_cbc_encrypt_mode(void);
const struct ccmode_stream *cccast_cfb8_decrypt_mode(void);
const struct ccmode_stream *cccast_cfb8_encrypt_mode(void);
const struct ccmode_stream *cccast_cfb_decrypt_mode(void);
const struct ccmode_stream *cccast_cfb_encrypt_mode(void);
const struct ccmode_ctr *cccast_ctr_crypt_mode(void);
const struct ccmode_ecb *cccast_ecb_decrypt_mode(void);
const struct ccmode_ecb *cccast_ecb_encrypt_mode(void);
const struct ccmode_stream *cccast_ofb_crypt_mode(void);
int ccccm_cbcmac(const struct ccmode_ccm *, const void *, void *, size_t, const void *);
int ccccm_set_iv(const struct ccmode_ccm *, const void *, void *, size_t, const void *, size_t, size_t, size_t);
int ccchacha20(const void *, const void *, uint32_t, size_t, const void *, void *);
int ccchacha20poly1305_decrypt_oneshot(const struct ccchacha20poly1305_info *, const void *, const void *, size_t, const void *, size_t, const void *, void *, const void *);
int ccchacha20poly1305_encrypt_oneshot(const struct ccchacha20poly1305_info *, const void *, const void *, size_t, const void *, size_t, const void *, void *, void *);
const struct ccchacha20poly1305_info *ccchacha20poly1305_info(void);
int ccckg2_contributor_commit(struct ccckg_ctx *, size_t, void *, struct ccrng_state *);
int ccckg2_contributor_finish(struct ccckg_ctx *, size_t, const void *, size_t, void *, struct ccec_ctx *, size_t, void *, struct ccrng_state *);
ccec_const_cp_t ccckg2_ctx_cp(const struct ccckg_ctx *);
int ccckg2_init(struct ccckg_ctx *, const struct ccckg2_params *);
int ccckg2_owner_finish(struct ccckg_ctx *, size_t, const void *, struct ccec_ctx *, size_t, void *, struct ccrng_state *);
int ccckg2_owner_generate_share(struct ccckg_ctx *, size_t, const void *, size_t, void *, struct ccrng_state *);
const struct ccckg2_params *ccckg2_params_p224_sha256_v2(void);
size_t ccckg2_sizeof_commitment(const struct ccckg2_params *);
size_t ccckg2_sizeof_ctx(const struct ccckg2_params *);
size_t ccckg2_sizeof_opening(const struct ccckg2_params *);
size_t ccckg2_sizeof_share(const struct ccckg2_params *);
int ccckg_contributor_commit(struct ccckg_ctx *, size_t, void *);
int ccckg_contributor_finish(struct ccckg_ctx *, size_t, const void *, size_t, void *, struct ccec_ctx *, size_t, void *);
ccec_const_cp_t ccckg_ctx_cp(const struct ccckg_ctx *);
int ccckg_init(struct ccckg_ctx *, ccec_const_cp_t, const struct ccdigest_info *, struct ccrng_state *);
int ccckg_owner_finish(struct ccckg_ctx *, size_t, const void *, struct ccec_ctx *, size_t, void *);
int ccckg_owner_generate_share(struct ccckg_ctx *, size_t, const void *, size_t, void *);
size_t ccckg_sizeof_commitment(ccec_const_cp_t, const struct ccdigest_info *);
size_t ccckg_sizeof_ctx(ccec_const_cp_t, const struct ccdigest_info *);
size_t ccckg_sizeof_opening(ccec_const_cp_t, const struct ccdigest_info *);
size_t ccckg_sizeof_share(ccec_const_cp_t, const struct ccdigest_info *);
int cccmac_final_generate(void *, size_t, void *);
int cccmac_init(const struct ccmode_cbc *, void *, size_t, const void *);
int cccmac_one_shot_generate(const struct ccmode_cbc *, size_t, const void *, size_t, const void *, size_t, void *);
int cccmac_update(void *, size_t, const void *);
const struct ccmode_cbc *ccdes3_cbc_decrypt_mode(void);
const struct ccmode_cbc *ccdes3_cbc_encrypt_mode(void);
const struct ccmode_stream *ccdes3_cfb8_decrypt_mode(void);
const struct ccmode_stream *ccdes3_cfb8_encrypt_mode(void);
const struct ccmode_stream *ccdes3_cfb_decrypt_mode(void);
const struct ccmode_stream *ccdes3_cfb_encrypt_mode(void);
const struct ccmode_ctr *ccdes3_ctr_crypt_mode(void);
const struct ccmode_ecb *ccdes3_ecb_decrypt_mode(void);
const struct ccmode_ecb *ccdes3_ecb_encrypt_mode(void);
const struct ccmode_stream *ccdes3_ofb_crypt_mode(void);
unsigned long ccdes_cbc_cksum(const void *, void *, size_t, const void *, size_t, const void *);
const struct ccmode_cbc *ccdes_cbc_decrypt_mode(void);
const struct ccmode_cbc *ccdes_cbc_encrypt_mode(void);
const struct ccmode_stream *ccdes_cfb8_decrypt_mode(void);
const struct ccmode_stream *ccdes_cfb8_encrypt_mode(void);
const struct ccmode_stream *ccdes_cfb_decrypt_mode(void);
const struct ccmode_stream *ccdes_cfb_encrypt_mode(void);
const struct ccmode_ctr *ccdes_ctr_crypt_mode(void);
const struct ccmode_ecb *ccdes_ecb_decrypt_mode(void);
const struct ccmode_ecb *ccdes_ecb_encrypt_mode(void);
int ccdes_key_is_weak(const void *, size_t);
void ccdes_key_set_odd_parity(void *, size_t);
const struct ccmode_stream *ccdes_ofb_crypt_mode(void);
size_t ccdh_ccn_size(const struct cczp *);
int ccdh_compute_shared_secret(const struct ccdh_ctx *, const struct ccdh_ctx *, size_t *, void *, struct ccrng_state *);
void ccdh_ctx_init(const struct cczp *, struct ccdh_ctx *);
struct ccdh_ctx *ccdh_ctx_public(struct ccdh_ctx *);
void ccdh_export_pub(const struct ccdh_ctx *, void *);
size_t ccdh_export_pub_size(const struct ccdh_ctx *);
int ccdh_generate_key(const struct cczp *, struct ccrng_state *, struct ccdh_ctx *);
const struct cczp *ccdh_gp_rfc3526group05(void);
int ccdh_import_pub(const struct cczp *, size_t, const void *, struct ccdh_ctx *);
void ccdigest(const struct ccdigest_info *, size_t, const void *, void *);
void ccdigest_init(const struct ccdigest_info *, void *);
void ccdigest_update(const struct ccdigest_info *, void *, size_t, const void *);
int ccec_blind(struct ccrng_state *, const struct ccec_ctx *, const struct ccec_ctx *, struct ccec_ctx *);
int ccec_compact_export_pub(void *, const struct ccec_ctx *);
int ccec_compact_import_pub(ccec_const_cp_t, size_t, const void *, struct ccec_ctx *);
size_t ccec_compact_import_pub_size(size_t);
const struct cczp *ccec_cp_256(void);
const struct cczp *ccec_cp_384(void);
const struct cczp *ccec_cp_521(void);
size_t ccec_diversify_min_entropy_len(ccec_const_cp_t);
int ccec_diversify_priv_twin(ccec_const_cp_t, const cc_unit *, size_t, const void *, struct ccrng_state *, struct ccec_ctx *);
int ccec_diversify_pub_twin(ccec_const_cp_t, const struct ccec_ctx *, size_t, const void *, struct ccrng_state *, struct ccec_ctx *);
int ccec_generate_blinding_keys(ccec_const_cp_t, struct ccrng_state *, struct ccec_ctx *, struct ccec_ctx *);
int ccec_generate_key(ccec_const_cp_t, struct ccrng_state *, struct ccec_ctx *);
const struct cczp *ccec_get_cp(size_t);
int ccec_get_fullkey_components(const struct ccec_ctx *, size_t *, void *, size_t *, void *, size_t *, void *, size_t *);
int ccec_get_pubkey_components(const struct ccec_ctx *, size_t *, void *, size_t *, void *, size_t *);
bool ccec_keysize_is_supported(size_t);
int ccec_make_pub(size_t, size_t, const void *, size_t, const void *, struct ccec_ctx *);
int ccec_sign(const struct ccec_ctx *, size_t, const void *, size_t *, void *, struct ccrng_state *);
int ccec_unblind(struct ccrng_state *, const struct ccec_ctx *, const struct ccec_ctx *, struct ccec_ctx *);
int ccec_verify(const struct ccec_ctx *, size_t, const void *, size_t, const void *, bool *);
int ccec_x963_export(bool, void *, const struct ccec_ctx *);
int ccec_x963_import_priv(ccec_const_cp_t, size_t, const void *, struct ccec_ctx *);
size_t ccec_x963_import_priv_size(size_t);
int ccec_x963_import_pub(ccec_const_cp_t, size_t, const void *, struct ccec_ctx *);
size_t ccec_x963_import_pub_size(size_t);
int ccecdh_compute_shared_secret(const struct ccec_ctx *, const struct ccec_ctx *, size_t *, void *, struct ccrng_state *);
int ccgcm_aad(const struct ccmode_gcm *, void *, size_t, const void *);
int ccgcm_finalize(const struct ccmode_gcm *, void *, size_t, void *);
int ccgcm_one_shot(const struct ccmode_gcm *, size_t, const void *, size_t, const void *, size_t, const void *, size_t, const void *, void *, size_t, void *);
int ccgcm_reset(const struct ccmode_gcm *, void *);
int ccgcm_set_iv(const struct ccmode_gcm *, void *, size_t, const void *);
int ccgcm_set_iv_legacy(const struct ccmode_gcm *, void *, size_t, const void *);
int ccgcm_update(const struct ccmode_gcm *, void *, size_t, const void *, void *);
int cch2c(const struct cch2c_info *, size_t, const void *, size_t, const void *, struct ccec_ctx *);
int cchkdf(const struct ccdigest_info *, size_t, const void *, size_t, const void *, size_t, const void *, size_t, void *);
int cchkdf_expand(const struct ccdigest_info *, size_t, const void *, size_t, const void *, size_t, void *);
int cchkdf_extract(const struct ccdigest_info *, size_t, const void *, size_t, const void *, void *);
void cchmac(const struct ccdigest_info *, size_t, const void *, size_t, const void *, void *);
void cchmac_final(const struct ccdigest_info *, void *, void *);
void cchmac_init(const struct ccdigest_info *, void *, size_t, const void *);
void cchmac_update(const struct ccdigest_info *, void *, size_t, const void *);
const struct ccdigest_info *ccmd5_di(void);
size_t ccn_bitlen(size_t, const cc_unit *);
int ccn_cmpn(size_t, const cc_unit *, size_t, const cc_unit *);
int ccn_read_uint(size_t, cc_unit *, size_t, const void *);
void ccn_write_int(size_t, const cc_unit *, size_t, void *);
size_t ccn_write_int_size(size_t, const cc_unit *);
void ccn_write_uint(size_t, const cc_unit *, size_t, void *);
size_t ccn_write_uint_padded(size_t, const cc_unit *, size_t, void *);
size_t ccn_write_uint_size(size_t, const cc_unit *);
int ccnistkdf_ctr_hmac(const struct ccdigest_info *, size_t, const void *, size_t, const void *, size_t, const void *, size_t, void *);
int ccnistkdf_ctr_hmac_fixed(const struct ccdigest_info *, size_t, const void *, size_t, const void *, size_t, void *);
size_t ccpad_cts3_decrypt(const struct ccmode_cbc *, const void *, void *, size_t, const void *, void *);
size_t ccpad_cts3_encrypt(const struct ccmode_cbc *, const void *, void *, size_t, const void *, void *);
size_t ccpad_pkcs7_decrypt(const struct ccmode_cbc *, const void *, void *, size_t, const void *, void *);
size_t ccpad_pkcs7_ecb_decrypt(const struct ccmode_ecb *, const void *, size_t, const void *, void *);
size_t ccpad_pkcs7_ecb_encrypt(const struct ccmode_ecb *, const void *, size_t, const void *, void *);
size_t ccpad_pkcs7_encrypt(const struct ccmode_cbc *, const void *, void *, size_t, const void *, void *);
size_t ccpad_xts_decrypt(const struct ccmode_xts *, const void *, void *, size_t, const void *, void *);
void ccpad_xts_encrypt(const struct ccmode_xts *, const void *, void *, size_t, const void *, void *);
int ccpbkdf2_hmac(const struct ccdigest_info *, size_t, const void *, size_t, const void *, uint64_t, size_t, void *);
const struct ccmode_cbc *ccrc2_cbc_decrypt_mode(void);
const struct ccmode_cbc *ccrc2_cbc_encrypt_mode(void);
const struct ccmode_stream *ccrc2_cfb8_decrypt_mode(void);
const struct ccmode_stream *ccrc2_cfb8_encrypt_mode(void);
const struct ccmode_stream *ccrc2_cfb_decrypt_mode(void);
const struct ccmode_stream *ccrc2_cfb_encrypt_mode(void);
const struct ccmode_ctr *ccrc2_ctr_crypt_mode(void);
const struct ccmode_ecb *ccrc2_ecb_decrypt_mode(void);
const struct ccmode_ecb *ccrc2_ecb_encrypt_mode(void);
const struct ccmode_stream *ccrc2_ofb_crypt_mode(void);
const struct ccrc4_info *ccrc4(void);
struct ccrng_state *ccrng(int *);
int ccrng_uniform(struct ccrng_state *, uint64_t, uint64_t *);
struct cczp *ccrsa_ctx_private_zp(const ccrsa_ctx *);
void *ccrsa_ctx_public(void *);
int ccrsa_decrypt_eme_pkcs1v15(const ccrsa_ctx *, size_t *, void *, size_t, const void *);
int ccrsa_decrypt_oaep(const ccrsa_ctx *, const struct ccdigest_info *, size_t *, void *, size_t, const void *, size_t, const void *);
int ccrsa_encrypt_eme_pkcs1v15(const ccrsa_ctx *, struct ccrng_state *, size_t *, void *, size_t, const void *);
int ccrsa_encrypt_oaep(const ccrsa_ctx *, const struct ccdigest_info *, struct ccrng_state *, size_t *, void *, size_t, const void *, size_t, const void *);
int ccrsa_export_priv(const ccrsa_ctx *, size_t, unsigned char *);
size_t ccrsa_export_priv_size(const ccrsa_ctx *);
int ccrsa_export_pub(const ccrsa_ctx *, size_t, unsigned char *);
size_t ccrsa_export_pub_size(const ccrsa_ctx *);
int ccrsa_generate_fips186_key(size_t, ccrsa_ctx *, size_t, const void *, struct ccrng_state *, struct ccrng_state *);
int ccrsa_generate_key(size_t, ccrsa_ctx *, size_t, const void *, struct ccrng_state *);
int ccrsa_get_fullkey_components(const ccrsa_ctx *, void *, size_t *, void *, size_t *, void *, size_t *, void *, size_t *);
int ccrsa_get_pubkey_components(const ccrsa_ctx *, void *, size_t *, void *, size_t *);
int ccrsa_import_priv(ccrsa_ctx *, size_t, const unsigned char *);
size_t ccrsa_import_priv_n(size_t, const unsigned char *);
int ccrsa_import_pub(ccrsa_ctx *, size_t, const unsigned char *);
size_t ccrsa_import_pub_n(size_t, const unsigned char *);
int ccrsa_init_pub(ccrsa_ctx *, const cc_unit *, const cc_unit *);
int ccrsa_make_priv(ccrsa_ctx *, size_t, const void *, size_t, const void *, size_t, const void *);
int ccrsa_make_pub(ccrsa_ctx *, size_t, const void *, size_t, const void *);
int ccrsa_priv_crypt(const ccrsa_ctx *, cc_unit *, const cc_unit *);
int ccrsa_pub_crypt(const ccrsa_ctx *, cc_unit *, const cc_unit *);
int ccrsa_recover_priv(ccrsa_ctx *, size_t, const void *, size_t, const void *, size_t, const void *, struct ccrng_state *);
int ccrsa_sign_pkcs1v15(const ccrsa_ctx *, const unsigned char *, size_t, const void *, size_t *, unsigned char *);
int ccrsa_sign_pss(const ccrsa_ctx *, const struct ccdigest_info *, const struct ccdigest_info *, size_t, struct ccrng_state *, size_t, const void *, size_t *, unsigned char *);
int ccrsa_verify_pkcs1v15_digest(const ccrsa_ctx *, const unsigned char *, size_t, const void *, size_t, const void *, void *);
int ccrsa_verify_pss_digest(const ccrsa_ctx *, const struct ccdigest_info *, const struct ccdigest_info *, size_t, const void *, size_t, const void *, size_t, void *);
const struct ccdigest_info *ccsha1_di(void);
const struct ccdigest_info *ccsha224_di(void);
const struct ccdigest_info *ccsha256_di(void);
const struct ccdigest_info *ccsha384_di(void);
const struct ccdigest_info *ccsha3_224_di(void);
const struct ccdigest_info *ccsha3_256_di(void);
const struct ccdigest_info *ccsha3_384_di(void);
const struct ccdigest_info *ccsha3_512_di(void);
const struct ccdigest_info *ccsha512_di(void);
int ccwrap_auth_decrypt_withiv(const struct ccmode_ecb *, const void *, size_t, const void *, size_t *, void *, const void *);
int ccwrap_auth_encrypt_withiv(const struct ccmode_ecb *, const void *, size_t, const void *, size_t *, void *, const void *);
size_t ccwrap_unwrapped_size(size_t);
size_t ccwrap_wrapped_size(size_t);
size_t ccxts_context_size(const struct ccmode_xts *);
void ccz_add(struct ccz *, const struct ccz *, const struct ccz *);
void ccz_addi(struct ccz *, const struct ccz *, uint32_t);
size_t ccz_bitlen(const struct ccz *);
int ccz_cmp(const struct ccz *, const struct ccz *);
int ccz_cmpi(const struct ccz *, uint32_t);
void ccz_divmod(struct ccz *, struct ccz *, const struct ccz *, const struct ccz *);
int ccz_expmod(struct ccz *, const struct ccz *, const struct ccz *, const struct ccz *);
void ccz_free(struct ccz *);
void ccz_init(const struct ccz_class *, struct ccz *);
bool ccz_is_negative(const struct ccz *);
bool ccz_is_prime(const struct ccz *, unsigned int);
bool ccz_is_zero(const struct ccz *);
void ccz_lsl(struct ccz *, const struct ccz *, size_t);
void ccz_lsr(struct ccz *, const struct ccz *, size_t);
void ccz_mod(struct ccz *, const struct ccz *, const struct ccz *);
void ccz_mul(struct ccz *, const struct ccz *, const struct ccz *);
void ccz_muli(struct ccz *, const struct ccz *, uint32_t);
void ccz_mulmod(struct ccz *, const struct ccz *, const struct ccz *, const struct ccz *);
void ccz_neg(struct ccz *);
int ccz_random_bits(struct ccz *, size_t, struct ccrng_state *);
int ccz_read_radix(struct ccz *, size_t, const char *, unsigned int);
void ccz_read_uint(struct ccz *, size_t, const void *);
void ccz_set(struct ccz *, const struct ccz *);
void ccz_seti(struct ccz *, uint64_t);
size_t ccz_size(void);
void ccz_sub(struct ccz *, const struct ccz *, const struct ccz *);
void ccz_subi(struct ccz *, const struct ccz *, uint32_t);
size_t ccz_trailing_zeros(const struct ccz *);
size_t ccz_write_int_size(const struct ccz *);
int ccz_write_radix(const struct ccz *, size_t, char *, unsigned int);
size_t ccz_write_radix_size(const struct ccz *, unsigned int);
void ccz_write_uint(const struct ccz *, size_t, void *);
size_t ccz_write_uint_size(const struct ccz *);
void ccz_zero(struct ccz *);
size_t cczp_bitlen(const struct cczp *);
size_t cczp_n(const struct cczp *);
cc_unit *cczp_prime(const struct cczp *);
