// SPDX-License-Identifier: MIT OR Apache-2.0
//
// The accessibility modifiers, to Apple's interface: each sets a property of the view's
// accessibility element (its label, value, hint, identifier, traits, visibility, heading
// level, sort priority), on any view or chained on another of these modifiers. Upstream has
// the accessibility tree and its properties, not these.
//
// Generated by userland/SwiftUI/gen-accessibility.py; edit that, not this.

import Foundation
import SwiftUICore


@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibilityLabel(_ label: Text, isEnabled: Bool) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        let t = label
        return accessibility(AccessibilityProperties.LabelKey.self, AccessibilityLabelStorage(texts: [t]), isEnabled: isEnabled)
    }

    nonisolated public func accessibilityLabel(_ labelKey: LocalizedStringKey, isEnabled: Bool) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        let t = Text(labelKey)
        return accessibility(AccessibilityProperties.LabelKey.self, AccessibilityLabelStorage(texts: [t]), isEnabled: isEnabled)
    }

    @_disfavoredOverload
    nonisolated public func accessibilityLabel<S>(_ label: S, isEnabled: Bool) -> ModifiedContent<Self, AccessibilityAttachmentModifier> where S: StringProtocol {
        let t = Text(label)
        return accessibility(AccessibilityProperties.LabelKey.self, AccessibilityLabelStorage(texts: [t]), isEnabled: isEnabled)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibilityLabel(_ label: Text, isEnabled: Bool) -> ModifiedContent<Content, Modifier> {
        let t = label
        return update(AccessibilityProperties.LabelKey.self, replacing: AccessibilityLabelStorage(texts: [t]), isEnabled: isEnabled)
    }

    nonisolated public func accessibilityLabel(_ labelKey: LocalizedStringKey, isEnabled: Bool) -> ModifiedContent<Content, Modifier> {
        let t = Text(labelKey)
        return update(AccessibilityProperties.LabelKey.self, replacing: AccessibilityLabelStorage(texts: [t]), isEnabled: isEnabled)
    }

    @_disfavoredOverload
    nonisolated public func accessibilityLabel<S>(_ label: S, isEnabled: Bool) -> ModifiedContent<Content, Modifier> where S: StringProtocol {
        let t = Text(label)
        return update(AccessibilityProperties.LabelKey.self, replacing: AccessibilityLabelStorage(texts: [t]), isEnabled: isEnabled)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibilityLabel(_ label: Text) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        let t = label
        return accessibility(AccessibilityProperties.LabelKey.self, AccessibilityLabelStorage(texts: [t]), isEnabled: true)
    }

    nonisolated public func accessibilityLabel(_ labelKey: LocalizedStringKey) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        let t = Text(labelKey)
        return accessibility(AccessibilityProperties.LabelKey.self, AccessibilityLabelStorage(texts: [t]), isEnabled: true)
    }

    @_disfavoredOverload
    nonisolated public func accessibilityLabel<S>(_ label: S) -> ModifiedContent<Self, AccessibilityAttachmentModifier> where S: StringProtocol {
        let t = Text(label)
        return accessibility(AccessibilityProperties.LabelKey.self, AccessibilityLabelStorage(texts: [t]), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibilityLabel(_ label: Text) -> ModifiedContent<Content, Modifier> {
        let t = label
        return update(AccessibilityProperties.LabelKey.self, replacing: AccessibilityLabelStorage(texts: [t]), isEnabled: true)
    }

    nonisolated public func accessibilityLabel(_ labelKey: LocalizedStringKey) -> ModifiedContent<Content, Modifier> {
        let t = Text(labelKey)
        return update(AccessibilityProperties.LabelKey.self, replacing: AccessibilityLabelStorage(texts: [t]), isEnabled: true)
    }

    @_disfavoredOverload
    nonisolated public func accessibilityLabel<S>(_ label: S) -> ModifiedContent<Content, Modifier> where S: StringProtocol {
        let t = Text(label)
        return update(AccessibilityProperties.LabelKey.self, replacing: AccessibilityLabelStorage(texts: [t]), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibilityValue(_ valueDescription: Text, isEnabled: Bool) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        let t = valueDescription
        return accessibility(AccessibilityProperties.ValueKey.self, AccessibilityValueStorage(description: t), isEnabled: isEnabled)
    }

    nonisolated public func accessibilityValue(_ valueKey: LocalizedStringKey, isEnabled: Bool) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        let t = Text(valueKey)
        return accessibility(AccessibilityProperties.ValueKey.self, AccessibilityValueStorage(description: t), isEnabled: isEnabled)
    }

    @_disfavoredOverload
    nonisolated public func accessibilityValue<S>(_ value: S, isEnabled: Bool) -> ModifiedContent<Self, AccessibilityAttachmentModifier> where S: StringProtocol {
        let t = Text(value)
        return accessibility(AccessibilityProperties.ValueKey.self, AccessibilityValueStorage(description: t), isEnabled: isEnabled)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibilityValue(_ valueDescription: Text, isEnabled: Bool) -> ModifiedContent<Content, Modifier> {
        let t = valueDescription
        return update(AccessibilityProperties.ValueKey.self, replacing: AccessibilityValueStorage(description: t), isEnabled: isEnabled)
    }

    nonisolated public func accessibilityValue(_ valueKey: LocalizedStringKey, isEnabled: Bool) -> ModifiedContent<Content, Modifier> {
        let t = Text(valueKey)
        return update(AccessibilityProperties.ValueKey.self, replacing: AccessibilityValueStorage(description: t), isEnabled: isEnabled)
    }

    @_disfavoredOverload
    nonisolated public func accessibilityValue<S>(_ value: S, isEnabled: Bool) -> ModifiedContent<Content, Modifier> where S: StringProtocol {
        let t = Text(value)
        return update(AccessibilityProperties.ValueKey.self, replacing: AccessibilityValueStorage(description: t), isEnabled: isEnabled)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibilityValue(_ valueDescription: Text) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        let t = valueDescription
        return accessibility(AccessibilityProperties.ValueKey.self, AccessibilityValueStorage(description: t), isEnabled: true)
    }

    nonisolated public func accessibilityValue(_ valueKey: LocalizedStringKey) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        let t = Text(valueKey)
        return accessibility(AccessibilityProperties.ValueKey.self, AccessibilityValueStorage(description: t), isEnabled: true)
    }

    @_disfavoredOverload
    nonisolated public func accessibilityValue<S>(_ value: S) -> ModifiedContent<Self, AccessibilityAttachmentModifier> where S: StringProtocol {
        let t = Text(value)
        return accessibility(AccessibilityProperties.ValueKey.self, AccessibilityValueStorage(description: t), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibilityValue(_ valueDescription: Text) -> ModifiedContent<Content, Modifier> {
        let t = valueDescription
        return update(AccessibilityProperties.ValueKey.self, replacing: AccessibilityValueStorage(description: t), isEnabled: true)
    }

    nonisolated public func accessibilityValue(_ valueKey: LocalizedStringKey) -> ModifiedContent<Content, Modifier> {
        let t = Text(valueKey)
        return update(AccessibilityProperties.ValueKey.self, replacing: AccessibilityValueStorage(description: t), isEnabled: true)
    }

    @_disfavoredOverload
    nonisolated public func accessibilityValue<S>(_ value: S) -> ModifiedContent<Content, Modifier> where S: StringProtocol {
        let t = Text(value)
        return update(AccessibilityProperties.ValueKey.self, replacing: AccessibilityValueStorage(description: t), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibilityHint(_ hint: Text, isEnabled: Bool) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        let t = hint
        return accessibility(AccessibilityProperties.HintsKey.self, [t], isEnabled: isEnabled)
    }

    nonisolated public func accessibilityHint(_ hintKey: LocalizedStringKey, isEnabled: Bool) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        let t = Text(hintKey)
        return accessibility(AccessibilityProperties.HintsKey.self, [t], isEnabled: isEnabled)
    }

    @_disfavoredOverload
    nonisolated public func accessibilityHint<S>(_ hint: S, isEnabled: Bool) -> ModifiedContent<Self, AccessibilityAttachmentModifier> where S: StringProtocol {
        let t = Text(hint)
        return accessibility(AccessibilityProperties.HintsKey.self, [t], isEnabled: isEnabled)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibilityHint(_ hint: Text, isEnabled: Bool) -> ModifiedContent<Content, Modifier> {
        let t = hint
        return update(AccessibilityProperties.HintsKey.self, replacing: [t], isEnabled: isEnabled)
    }

    nonisolated public func accessibilityHint(_ hintKey: LocalizedStringKey, isEnabled: Bool) -> ModifiedContent<Content, Modifier> {
        let t = Text(hintKey)
        return update(AccessibilityProperties.HintsKey.self, replacing: [t], isEnabled: isEnabled)
    }

    @_disfavoredOverload
    nonisolated public func accessibilityHint<S>(_ hint: S, isEnabled: Bool) -> ModifiedContent<Content, Modifier> where S: StringProtocol {
        let t = Text(hint)
        return update(AccessibilityProperties.HintsKey.self, replacing: [t], isEnabled: isEnabled)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibilityHint(_ hint: Text) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        let t = hint
        return accessibility(AccessibilityProperties.HintsKey.self, [t], isEnabled: true)
    }

    nonisolated public func accessibilityHint(_ hintKey: LocalizedStringKey) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        let t = Text(hintKey)
        return accessibility(AccessibilityProperties.HintsKey.self, [t], isEnabled: true)
    }

    @_disfavoredOverload
    nonisolated public func accessibilityHint<S>(_ hint: S) -> ModifiedContent<Self, AccessibilityAttachmentModifier> where S: StringProtocol {
        let t = Text(hint)
        return accessibility(AccessibilityProperties.HintsKey.self, [t], isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibilityHint(_ hint: Text) -> ModifiedContent<Content, Modifier> {
        let t = hint
        return update(AccessibilityProperties.HintsKey.self, replacing: [t], isEnabled: true)
    }

    nonisolated public func accessibilityHint(_ hintKey: LocalizedStringKey) -> ModifiedContent<Content, Modifier> {
        let t = Text(hintKey)
        return update(AccessibilityProperties.HintsKey.self, replacing: [t], isEnabled: true)
    }

    @_disfavoredOverload
    nonisolated public func accessibilityHint<S>(_ hint: S) -> ModifiedContent<Content, Modifier> where S: StringProtocol {
        let t = Text(hint)
        return update(AccessibilityProperties.HintsKey.self, replacing: [t], isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibilityIdentifier(_ identifier: String, isEnabled: Bool) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        accessibility(AccessibilityProperties.IdentifierKey.self, AccessibilityIdentifierStorage(identifier), isEnabled: isEnabled)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibilityIdentifier(_ identifier: String, isEnabled: Bool) -> ModifiedContent<Content, Modifier> {
        update(AccessibilityProperties.IdentifierKey.self, replacing: AccessibilityIdentifierStorage(identifier), isEnabled: isEnabled)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibilityIdentifier(_ identifier: String) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        accessibility(AccessibilityProperties.IdentifierKey.self, AccessibilityIdentifierStorage(identifier), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibilityIdentifier(_ identifier: String) -> ModifiedContent<Content, Modifier> {
        update(AccessibilityProperties.IdentifierKey.self, replacing: AccessibilityIdentifierStorage(identifier), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibilityHidden(_ hidden: Bool, isEnabled: Bool) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        accessibility(AccessibilityProperties.VisibilityKey.self, hidden ? AccessibilityVisibilityStorage(adding: .hidden) : AccessibilityVisibilityStorage(removing: .hidden), isEnabled: isEnabled)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibilityHidden(_ hidden: Bool, isEnabled: Bool) -> ModifiedContent<Content, Modifier> {
        update(AccessibilityProperties.VisibilityKey.self, replacing: hidden ? AccessibilityVisibilityStorage(adding: .hidden) : AccessibilityVisibilityStorage(removing: .hidden), isEnabled: isEnabled)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibilityHidden(_ hidden: Bool) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        accessibility(AccessibilityProperties.VisibilityKey.self, hidden ? AccessibilityVisibilityStorage(adding: .hidden) : AccessibilityVisibilityStorage(removing: .hidden), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibilityHidden(_ hidden: Bool) -> ModifiedContent<Content, Modifier> {
        update(AccessibilityProperties.VisibilityKey.self, replacing: hidden ? AccessibilityVisibilityStorage(adding: .hidden) : AccessibilityVisibilityStorage(removing: .hidden), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibilityAddTraits(_ traits: AccessibilityTraits) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        accessibility(AccessibilityProperties.TraitsKey.self, AccessibilityTraitStorage(adding: traits), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibilityAddTraits(_ traits: AccessibilityTraits) -> ModifiedContent<Content, Modifier> {
        update(AccessibilityProperties.TraitsKey.self, replacing: AccessibilityTraitStorage(adding: traits), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibilityRemoveTraits(_ traits: AccessibilityTraits) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        accessibility(AccessibilityProperties.TraitsKey.self, AccessibilityTraitStorage(removing: traits), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibilityRemoveTraits(_ traits: AccessibilityTraits) -> ModifiedContent<Content, Modifier> {
        update(AccessibilityProperties.TraitsKey.self, replacing: AccessibilityTraitStorage(removing: traits), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibilitySortPriority(_ sortPriority: Double) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        accessibility(AccessibilityProperties.SortPriorityKey.self, sortPriority, isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibilitySortPriority(_ sortPriority: Double) -> ModifiedContent<Content, Modifier> {
        update(AccessibilityProperties.SortPriorityKey.self, replacing: sortPriority, isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibilityHeading(_ level: AccessibilityHeadingLevel) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        accessibility(AccessibilityProperties.TextHeadingLevelKey.self, level, isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibilityHeading(_ level: AccessibilityHeadingLevel) -> ModifiedContent<Content, Modifier> {
        update(AccessibilityProperties.TextHeadingLevelKey.self, replacing: level, isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibility(label: Text) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        accessibility(AccessibilityProperties.LabelKey.self, AccessibilityLabelStorage(texts: [label]), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibility(label: Text) -> ModifiedContent<Content, Modifier> {
        update(AccessibilityProperties.LabelKey.self, replacing: AccessibilityLabelStorage(texts: [label]), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibility(value: Text) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        accessibility(AccessibilityProperties.ValueKey.self, AccessibilityValueStorage(description: value), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibility(value: Text) -> ModifiedContent<Content, Modifier> {
        update(AccessibilityProperties.ValueKey.self, replacing: AccessibilityValueStorage(description: value), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibility(hint: Text) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        accessibility(AccessibilityProperties.HintsKey.self, [hint], isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibility(hint: Text) -> ModifiedContent<Content, Modifier> {
        update(AccessibilityProperties.HintsKey.self, replacing: [hint], isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibility(hidden: Bool) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        accessibility(AccessibilityProperties.VisibilityKey.self, hidden ? AccessibilityVisibilityStorage(adding: .hidden) : AccessibilityVisibilityStorage(removing: .hidden), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibility(hidden: Bool) -> ModifiedContent<Content, Modifier> {
        update(AccessibilityProperties.VisibilityKey.self, replacing: hidden ? AccessibilityVisibilityStorage(adding: .hidden) : AccessibilityVisibilityStorage(removing: .hidden), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibility(identifier: String) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        accessibility(AccessibilityProperties.IdentifierKey.self, AccessibilityIdentifierStorage(identifier), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibility(identifier: String) -> ModifiedContent<Content, Modifier> {
        update(AccessibilityProperties.IdentifierKey.self, replacing: AccessibilityIdentifierStorage(identifier), isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    nonisolated public func accessibility(sortPriority: Double) -> ModifiedContent<Self, AccessibilityAttachmentModifier> {
        accessibility(AccessibilityProperties.SortPriorityKey.self, sortPriority, isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension ModifiedContent where Modifier == AccessibilityAttachmentModifier {
    nonisolated public func accessibility(sortPriority: Double) -> ModifiedContent<Content, Modifier> {
        update(AccessibilityProperties.SortPriorityKey.self, replacing: sortPriority, isEnabled: true)
    }
}

@available(OpenSwiftUI_v1_0, *)
extension View {
    /// The view as one accessibility element, its children ignored, contained or combined.
    nonisolated public func accessibilityElement(children: AccessibilityChildBehavior = .ignore) -> some View {
        modifier(AccessibilityAttachmentModifier(storage: MutableBox(AccessibilityAttachment()), behavior: children))
    }
}
