/* SPDX-License-Identifier: MIT OR Apache-2.0 */
#include "../preferences.h"
#include <dlfcn.h>
#include <assert.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
struct api {void(*compute)(xpc_object_t,const char*,struct finch_log_preferences*);void(*merge)(xpc_object_t,xpc_object_t,const char*);xpc_object_t(*read)(int,const char*);xpc_object_t(*load)(const char*,const char*);xpc_object_t(*system)(const char*,const char*,bool);uint32_t(*commpage)(uint32_t,int,int,int,int);bool(*development)(void);bool(*atm)(uint32_t*);bool(*match)(uint32_t);void*(*cache)(size_t*);};
static struct api load(void*h){return (struct api){dlsym(h,"_os_log_preferences_compute"),dlsym(h,"_os_log_preferences_merge"),dlsym(h,"_os_trace_read_plist_at"),dlsym(h,"_os_log_preferences_load"),dlsym(h,"_os_log_preferences_load_sysprefs"),dlsym(h,"_os_trace_commpage_compute"),dlsym(h,"_os_trace_is_development_build"),dlsym(h,"_os_trace_atm_diagnostic_config"),dlsym(h,"_os_trace_mode_match_4tests"),dlsym(h,"_os_log_preferences_copy_cache")};}
static uint32_t random_next(uint32_t*s){*s=*s*1664525+1013904223;return *s;}
static xpc_object_t sample(uint32_t*s,unsigned depth){unsigned n=random_next(s);switch(n%6){case 0:return xpc_string_create((const char*[]){"inherit","Debug","false","", "Public","SENSITIVE","Always","None","Thread","Info","off","Private","Process","System","Once","default"}[(n>>8)%16]);case 1:return xpc_bool_create(n&256);case 2:return xpc_int64_create((int64_t)(n>>8)-500000);case 3:return xpc_uint64_create(n);case 4:if(depth){xpc_object_t d=xpc_dictionary_create(NULL,NULL,0);for(unsigned i=0;i<3;i++){char key[16];snprintf(key,sizeof(key),"key%u",i);xpc_object_t p=sample(s,depth-1);xpc_dictionary_set_value(d,key,p);xpc_release(p);}return d;}return xpc_string_create("inherit");default:return xpc_array_create(NULL,0);}}
static xpc_object_t prefs(uint32_t seed){xpc_object_t root=xpc_dictionary_create(NULL,NULL,0);const char*categories[]={"DEFAULT-OPTIONS","category","DynamicTracing","DynamicStackTracing"};const char*keys[]={"Symptoms","Enable-Oversize-Messages","Default-Privacy-Setting","Privacy-Enable-Level","Enable-Private-Data","Signpost-Scope","Supports-Signpost-Introspection","Signpost-Enabled","Signpost-Persisted","Signpost-Backtraces-Enabled","Signpost-Allow-Streaming","Enable-Fault-Crashlogs","Enable-Fault-Crashlog-Excerpts","Install-Log-Persist-Level"};for(unsigned c=0;c<4;c++){xpc_object_t d=xpc_dictionary_create(NULL,NULL,0);for(unsigned i=0;i<14;i++)if(random_next(&seed)%3){xpc_object_t p=sample(&seed,2);xpc_dictionary_set_value(d,keys[i],p);xpc_release(p);}xpc_object_t levels=xpc_dictionary_create(NULL,NULL,0),ttl=xpc_dictionary_create(NULL,NULL,0);for(unsigned i=0;i<3;i++){xpc_object_t p=sample(&seed,0);xpc_dictionary_set_value(levels,(const char*[]){"Enable","Persist","Other"}[i],p);xpc_release(p);p=sample(&seed,0);xpc_dictionary_set_value(ttl,(const char*[]){"Default","Info","Debug"}[i],p);xpc_release(p);}xpc_dictionary_set_value(d,"Level",levels);xpc_dictionary_set_value(d,"TTL",ttl);xpc_release(levels);xpc_release(ttl);xpc_dictionary_set_value(root,categories[c],d);xpc_release(d);}return root;}
static void equal(xpc_object_t x,xpc_object_t y){assert(!!x==!!y);if(x&&!xpc_equal(x,y)){char*a=xpc_copy_description(x),*b=xpc_copy_description(y);fprintf(stderr,"mismatch\n%s\n%s\n",a,b);abort();}}
int main(int argc,char**argv){assert(argc==2);void*h=dlopen("/usr/lib/system/libsystem_trace.dylib",RTLD_NOW|RTLD_LOCAL),*f=dlopen(argv[1],RTLD_NOW|RTLD_LOCAL);assert(h&&f);struct api a[]={load(h),load(f)};Dl_info info;void*symbols[sizeof(struct api)/sizeof(void*)];memcpy(symbols,&a[1],sizeof(symbols));for(unsigned i=0;i<sizeof(symbols)/sizeof(*symbols);i++)assert(symbols[i]&&dladdr(symbols[i],&info)&&strstr(info.dli_fname,argv[1]));unsigned checks=0;const char*categories[]={"category","DynamicTracing","DynamicStackTracing","absent"};
 for(unsigned n=0;n<2500;n++){xpc_object_t p=n?prefs(n):NULL;for(unsigned c=0;c<4;c++){struct {struct finch_log_preferences p;uint64_t canary;} out[2];memset(out,0xa5,sizeof(out));a[0].compute(p,categories[c],&out[0].p);a[1].compute(p,categories[c],&out[1].p);if(memcmp(out,out+1,sizeof(*out))){fprintf(stderr,"compute n%u category%s options%x/%x\n",n,categories[c],out[0].p.options,out[1].p.options);abort();}checks++;}if(p)xpc_release(p);}
 for(unsigned n=1;n<1000;n++){xpc_object_t targets[]={prefs(n),prefs(n)},sources[]={prefs(n+9001),prefs(n+9001)};const char*category=n%5?categories[n%4]:NULL;for(unsigned j=0;j<2;j++)a[j].merge(targets[j],sources[j],category);equal(targets[0],targets[1]);equal(sources[0],sources[1]);for(unsigned j=0;j<2;j++){xpc_release(targets[j]);xpc_release(sources[j]);}checks++;}
 uint32_t seed=7;for(unsigned n=0;n<1000;n++){uint32_t flags=random_next(&seed);for(unsigned mask=0;mask<256;mask++){int r=mask&3,l=mask>>2&3,d=mask>>4&3,f=mask>>6;uint32_t x=a[0].commpage(flags,r,l,d,f),y=a[1].commpage(flags,r,l,d,f);if(x!=y){fprintf(stderr,"commpage %x %u: %x/%x\n",flags,mask,x,y);abort();}checks++;}}
 char directory[]="/tmp/finch-preferences-XXXXXX";assert(mkdtemp(directory));int dir=open(directory,O_RDONLY|O_DIRECTORY);assert(dir>=0);const char*documents[]={"<?xml version=\"1.0\"?><plist version=\"1.0\"><dict><key>Level</key><dict><key>Enable</key><string>Debug</string></dict><key>Number</key><integer>42</integer><key>Bool</key><true/></dict></plist>","<plist version=\"1.0\"><array><string>value</string></array></plist>","not a plist",""};
 const unsigned char binary[]={98,112,108,105,115,116,48,48,211,1,2,3,4,5,8,84,66,111,111,108,85,76,101,118,101,108,86,78,117,109,98,101,114,9,209,6,7,86,69,110,97,98,108,101,85,68,101,98,117,103,16,42,8,15,20,26,33,34,37,44,50,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,52};
 for(unsigned i=0;i<5;i++){int fd=openat(dir,"fixture.plist",O_WRONLY|O_CREAT|O_TRUNC,0600);assert(fd>=0);size_t n=i<4?strlen(documents[i]):sizeof(binary);const void*bytes=i<4?(const void*)documents[i]:binary;assert(write(fd,bytes,n)==(ssize_t)n);close(fd);xpc_object_t p[]={a[0].read(dir,"fixture.plist"),a[1].read(dir,"fixture.plist")};equal(p[0],p[1]);for(unsigned j=0;j<2;j++)if(p[j])xpc_release(p[j]);checks++;}
 assert(!symlinkat("fixture.plist",dir,"link.plist"));for(unsigned j=0;j<2;j++){assert(!a[j].read(dir,"link.plist"));assert(!a[j].read(dir,"missing.plist"));}int large=openat(dir,"large.plist",O_WRONLY|O_CREAT,0600);assert(large>=0&&!ftruncate(large,65537));close(large);for(unsigned j=0;j<2;j++)assert(!a[j].read(dir,"large.plist"));unlinkat(dir,"large.plist",0);unlinkat(dir,"link.plist",0);unlinkat(dir,"fixture.plist",0);close(dir);rmdir(directory);
 const char*systems[]={"com.apple.Home","com.apple.authkit","com.apple.tailspin","com.apple.spindump","finch.nonexistent.test"};for(unsigned i=0;i<5;i++)for(unsigned category=0;category<2;category++)for(unsigned source=0;source<3;source++){xpc_object_t p[2];for(unsigned j=0;j<2;j++)p[j]=source?a[j].system(systems[i],category?"DEFAULT-OPTIONS":NULL,source==2):a[j].load(systems[i],category?"DEFAULT-OPTIONS":NULL);equal(p[0],p[1]);for(unsigned j=0;j<2;j++)if(p[j])xpc_release(p[j]);checks++;}
 assert(a[0].development()==a[1].development());uint32_t config[2]={0xa5a5a5a5,0xa5a5a5a5};assert(a[0].atm(config)==a[1].atm(config+1)&&config[0]==config[1]);for(unsigned bit=0;bit<32;bit++)assert(a[0].match(1u<<bit)==a[1].match(1u<<bit));size_t lengths[2]={0};void*cache[]={a[0].cache(lengths),a[1].cache(lengths+1)};assert(lengths[0]==lengths[1]&&!!cache[0]==!!cache[1]);if(lengths[0])assert(!memcmp(cache[0],cache[1],lengths[0]));free(cache[0]);free(cache[1]);printf("preferences: %u host comparisons passed; no system preferences changed\n",checks);return 0;}
